<div class="page-header">
    <h1>
        Auditorias del Sistema 
        <small>Usuario: <?php eh(strtoupper($usuario->login)) ?></small>
        <a href="../" class="btn" style="float: right">Volver</a>
    </h1>
</div>
<div id="mensajes_flash" >        
    <?php View::content() ?>
</div> 
<?php echo Form::open('admin/auditorias/resultados_usuario/' . $usuario->id) ?>
<div class="row">
    <div class="span3">
        <label for="filtro_tabla_afectada">Tabla Afectada</label>
    </div>
    <div class="span3">
        <label for="filtro_fecha_at">Fecha</label>
    </div>
    <div class="span3">
        <label for="filtro_accion_realizada">Acci&oacute;n Realizada</label>
    </div>
</div>
<div class="row">
    <div class="span3">
        <?php echo Form::select('filtro.tabla_afectada', $tablas_afectadas) ?>
    </div>
    <div class="span3">
        <?php echo Form::date('filtro.fecha_at','span2') ?>
    </div>
    <div class="span3">
        <?php echo Form::text('filtro.accion_realizada') ?>
    </div>
    <div class="span3" style1="white-space: nowrap;">
        <?php echo Form::submit('Aplicar Filtro', 'class="btn btn-primary"') ?>                
        <?php echo Html::linkAction('usuario/' . $usuario->id, 'Mostrar Todos', 'class="btn"') ?>   
    </div>
</div>
<?php echo Form::close() ?>
<div id="scaffold">
    <?php
    $dt = new DataTable($auditorias);
    $dt->addHeaders('Accion Realizada', 'Fecha y Hora', 'Tabla Afectada','IP Usuario');
    $dt->addFields('accion_realizada', 'fecha_at', 'tabla_afectada','ip');
    $dt->url($url);
    echo $dt->render('class="table table-bordered table-striped"');
    ?>
</div>
<!--<style type="text/css" >
    .span4 label{
        text-align: center;
    }

    table thead th:first-child,
    table tbody td:first-child{
        word-wrap: break-word;
        max-width: 500px;
        overflow: hidden;
}
</style>-->
<?php
    Tag::css('datepicker');
    echo Tag::js('datepicker/datepicker');
?>