<?php View::notify(); ?>
<script type="text/javascript">
    $(function() {
        $('table').dwGrid({
            form_search: true,
            form_action: '<?php echo PUBLIC_PATH; ?>solicitudes/solicitud_reembolso/buscar/',
            form_load_data : 'dw-shell-content',
            order_attr: '<?php echo (APP_AJAX) ? 'class="dw-ajax dw-spinner"' : ''; ?>',
            order_action: $.KumbiaPHP.publicPath+"solicitudes/solicitud_reembolso/registro/"
        });
    });
</script>
<div class="container-fluid dw-shell-view">
    <?php View::process($page_module, $page_title, $set_title); ?>

    <div class="btn-toolbar btn-toolbar-top">
        <div class="btn-actions">
            <?php echo DwHtml::button("solicitudes/solicitud_reembolso/agregar", 'agregar', array('class'=>'btn-success'), 'check', APP_AJAX); ?>
            <?php echo DwButton::report("solicitud_reembolso/listado/", 'html', 'Reporte de Reembolsos', 'imprimir'); ?>
        </div>
    </div>
    <div class="dw-overflow">

        <table class="table table-bordered table-hover table-striped table-condensed table-responsive">
            <thead>
                <tr>
                    <th>NUM</th>
                    <th class="col-collapse" data-search="fecha_solicitud">FECHA SOLCITUD</th>
                    <th class="col-collapse" data-search="fecha_recibido">FECHA RECIBIDO </th>
                    <th class="col-collapse" data-search="tcedula">CEDULA TITULAR </th>
                    <th class="col-collapse" data-search="titular">TITULAR</th>
                    <th class="col-collapse" data-search="paciente">PACIENTE</th>
                    <th class="col-collapse" data-search="parentesco">PARENTESCO</th>
                    <th class="col-collapse" data-search="factura">FACTURA</th>
                    <th class="col-collapse" data-search="sede">SEDE</th>
                    <th class="col-collapse" data-search="tipo_nomina">TIPO NOMINA</th>
                    <th class="col-collapse" data-search="tipo_gasto">TIPO GASTO</th>
                    <th class="col-collapse" data-search="monto_solicitado">MONTO SOLICITADO</th>
                    <th class="col-collapse" data-search="monto_pagado">MONTO PAGADO</th>
                    <th class="col-collapse" data-search="total_cancelar">TOTAL CANCELADO</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($solicitud_reembolsos->items as $reemboloso): ?>
                    <tr>
                        <td><?php echo $solicitud_reembolsos->counter; ?></td>
                        <td><?php echo $reemboloso->fecha_solicitud; ?></td>
                        <td><?php echo $reemboloso->fecha_recibido; ?></td>
                        <td><?php echo $reemboloso->tcedula; ?></td>
                        <td><?php echo $reemboloso->titular; ?></td>
                        <td><?php echo $reemboloso->paciente; ?></td>
                        <td><?php echo $reemboloso->parentesco; ?></td>
                        <td><?php echo $reemboloso->factura; ?></td>
                        <td><?php echo $reemboloso->sede; ?></td>
                        <td><?php echo $reemboloso->tipo_nomina; ?></td>
                        <td><?php echo $reemboloso->tipo_gasto; ?></td>
                        <td><?php echo $reemboloso->monto_solicitado; ?></td>
                        <td><?php echo $reemboloso->monto_pagado; ?></td>
                        <td><?php echo $reemboloso->total_cancelar; ?></td>
                    </tr>
                    <?php $solicitud_reembolsos->counter++; ?>
                <?php endforeach; ?>
            </tbody>
        </table>

    </div>

    <?php View::partial('paginators/default', false, array('page'=>$solicitud_reembolsos, 'url'=>"solicitudes/solicitud_reembolso/registro/$order/")); ?>
</div>
