<?php View::notify(); ?>
<script type="text/javascript">
    $(function() {
        $('table').dwGrid({
            order_attr: '<?php echo (APP_AJAX) ? 'class="dw-ajax dw-spinner"' : ''; ?>',
            order_action: $.KumbiaPHP.publicPath+"solicitudes/solicitud_reembolso/registro/"
        });
    });
</script>
<div class="container-fluid dw-shell-view">
    <?php View::process($page_module, $page_title, $set_title); ?>
    <div class="btn-toolbar btn-toolbar-top">
        <div class="btn-actions">
            <?php echo DwHtml::button("solicitudes/solicitud_reembolso/agregar", 'agregar', array('class'=>'btn-success'), 'check', APP_AJAX); ?>
        </div>
    </div>
    <div class="dw-overflow">
        <table class="table table-bordered table-hover table-striped table-condensed table-responsive">
            <thead>
                <tr>
                    <th>NUM</th>
                    <th class="col-collapse" data-search="fecha">FECHA</th>
                    <th class="col-collapse" data-search="codigo">CODIGO</th>
                    <th class="col-collapse" data-search="titular">TITULAR</th>
                    <th class="col-collapse" data-search="beneficiario">BENEFICIARIO</th>
                    <th class="col-collapse" data-search="proveedor">PROVEEDOR</th>
                    <th class="col-collapse" data-search="servicio">SERVICIO</th>
                    <th class="col-collapse" data-search="observacion">OBSERVACION</th>
                    <th class="col-collapse" data-search="tiposolicitud">TIPO SOLICITUD</th>
                    <th class="col-collapse" data-search="estado">ESTADO</th>
                    <th class="btn-actions no-responsive" style="width: 100px;">ACCIONES</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($solicitud_reembolsos->items as $solicitud_reembolso): ?>
                    <?php $key_upd = DwSecurity::getKey($solicitud_reembolso->idsolicitudservicio, 'upd_solicitud_servicio'); ?>
                    <?php $key_del = DwSecurity::getKey($solicitud_reembolso->idsolicitudservicio, 'del_solicitud_servicio'); ?>
                    <tr>
                        <td><?php echo $solicitud_reembolsos->counter; ?></td>
                        <td><?php echo $solicitud_reembolso->fecha_solicitud; ?></td>
                        <td><?php echo $solicitud_reembolso->codigo_solicitud; ?></td>
                        <td><?php echo $solicitud_reembolso->nombre; echo ' '; echo $solicitud_reembolso->apellido;?></td>
                        <td><?php echo $solicitud_reembolso->nombreb; echo ' '; echo $solicitud_reembolso->apellidob;?></td>
                        <td><?php echo $solicitud_reembolso->proveedor; ?></td>
                        <td><?php echo $solicitud_reembolso->servicio; ?></td>
                        <td><?php echo $solicitud_reembolso->observacion; ?></td>
                        <td><?php echo $solicitud_reembolso->tiposolicitud; ?></td>
                        <td><?php echo ($solicitud_reembolso->estado_solicitud == 'G') ? '<span class="label label-important" title="'.$solicitud_reembolso->tiposolicitud.'" rel="tooltip">FACTURADA PARCIAL</span>' : '<span class="label label-success" title="Por cargar Facturas '.$solicitud_reembolso->estado_solicitud.'" rel="tooltip">FACTURADAS</span>' ; ?>
                        </td>
                        <td>
                        <?php echo DwHtml::buttonTable('CARGAR FACTURAS', "solicitudes/solicitud_reembolso/facturar/$key_upd/", null, 'default', 'list'); ?>
                        </td>
                    </tr>
                    <?php $solicitud_reembolsos->counter++; ?>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php View::partial('paginators/default', false, array('page'=>$solicitud_reembolsos, 'url'=>"solicitudes/solicitud_reembolso/listar/$order/")); ?>
</div>
