<div class="page-header">
    <h1><?php eh($titulo) ?></h1>
</div>
<div class="row">
    <div class="span3">
        <?php View::partial('backend/menus/roles') ?>
    </div>
    <div class="span8 span-derecho" >
        <div id="res-form-ajax"><?php View::content() ?></div>
        <?php echo Ajax::form('res-form-ajax', NULL, 'form-horizontal') ?>
        <?php //echo Form::open(NULL, 'post', 'class="form-horizontal"') ?>
        <?php echo Form::hidden('rol.id') ?>
        <div class="control-group">
            <label class="control-label" for="rol_rol">Nombre del rol* : </label>
            <div class="controls">
                <?php echo Form::text('rol.rol') ?>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="rol_plantilla">Plantilla a Usar : </label>
            <div class="controls">
                <?php echo Form::text('rol.plantilla') ?>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="menus_activo">Activo (Visible) : </label>
            <div class="controls">
                <?php echo Form::select('rol.activo', array('1' => 'Si', '0' => 'No')) ?>
            </div>
        </div>
        <hr/>
        <?php //View::partial('backend/privilegios_rol'); ?>
                <div class="form-actions">
            <?php echo Form::submit('Guardar Datos', 'class="btn btn-primary"') ?>
            <?php echo Html::linkAction('', 'Cancelar', 'class="btn"') ?>
            </div>
        <?php echo Form::close() ?>
            </div>
        </div>
        <script type="text/javascript">
            $(function(){
                var url = <?php echo PUBLIC_PATH ?> + "admin/roles/agregar_padre/";
                $("#select_padres select").live('change',function(){
                    var padre = $('option:selected',this).text();
                    if ( $("#roles_padres").html().indexOf(padre) < 0 &&
                        $('option:selected',this).val() != "<?php @eh($rol->id) ?>" ) {
                        $.post(url + $('option:selected',this).val(),{},function(data){
                            $("#roles_padres").append(data);
                        });
                    }
                });

                $("#roles_padres .rol_padre span").live('click',function(){
                    $(this).parent().remove();
                });
<?php if (isset($rol) and $rol->padres) : ?>
<?php foreach (explode(',', $rol->padres) as $e) : ?>
                $.post(url + <?php eh($e) ?>,{},function(data){
                    $("#roles_padres").append(data);
                });
<?php endforeach ?>
<?php endif ?>
});
</script>              
