<div class="page-header">
    <h1>Eliminación de Registros</h1>
</div>
<?php View::content() ?>
<div class="alert-block alert alert-danger">
    <p>¿ Realmente deseas eliminar los Roles <b><?php echo join(', ', $ids) ?></b> del Sistema ?</p>
    <hr/>
    <p>
        <?php echo Html::linkAction('eliminar/' .join(',', $ids), 'Si','class="btn btn-danger"'); ?>
        <?php echo Html::linkAction('', 'No','class="btn btn-inverse"'); ?>
    </p>
</div>
