<div class="page-header">
    <h1>Bienvenido al Proceso de Instalación</h1>
</div>
<h3>Configuración de la conexion a la base de datos</h3>
<?php View::content() ?>
<?php echo Form::open(NULL, 'post', 'class="form-horizontal"') ?>
<div class="control-group">
    <!-- <label class="control-label" for="config_name">Entorno a Configurar : </label>
    <div class="controls">
        <?php echo Ajax::select('entorno', $entornos_bd, 'res-ajax', 'index') ?>
    </div> -->
</div>
<div id="res-ajax">
    <?php require 'index.ajax.phtml'; ?>
</div>
<?php echo Form::close() ?>
