<?php if (Input::isAjax())
    View::content() ?>
    <div class="control-group">
        <label class="control-label" for="config_name">Origen de Datos (dsn) : </label>
        <div class="controls">
        <?php echo Form::text('database.dsn') ?>
    </div>
</div>
<div class="control-group">
    <label class="control-label" for="config_name">Usuario : </label>
    <div class="controls">
        <?php echo Form::text('database.username') ?>
    </div>
</div>
<div class="control-group">
    <label class="control-label" for="config_name">Contraseña : </label>
    <div class="controls">
        <?php echo Form::text('database.password') ?>
    </div>
</div>
<div class="control-group">
    <label class="control-label" for="config_name">Driver de Conexión : </label>
    <div class="controls">
        <?php echo Form::text('database.type') ?>
    </div>
</div>
<div class="form-actions">
    <?php echo Form::submit('Guardar Configuración', 'class="btn btn-primary"') ?>
</div>
