<div class="page-header">
    <h1>Configuraci&oacute;n de la Base de Datos</h1>
</div>
<?php View::content() ?>
<?php echo Form::open(NULL, 'post', 'class="form-horizontal"') ?>
<h5>Tablas de la Base de Datos <?php //eh(Config::get('databases.'))     ?></h5>
<ul>
    <?php foreach ((array) $tablas_existentes as $t): ?> 
        <li><h5><?php eh($t) ?> <small><?php if ( Instalacion::esTablaNecesaria($t) ) echo ' usada en el backend'; ?></small></h5></li>
    <?php endforeach; ?> 
</ul>
<hr />
<p>
    Debe crear las tablas necesarias en la base de datos para el funcionamiento del backend.
</p>
<p>
    Acontinuación ejecute el archivo .sql correspondiente a su servidor
    de base de datos que se encuentra en : <br/><b><?php eh($sql) ?></b> para continuar con la instalación.
</p>
<div class="form-actions">
    <?php echo Html::linkAction('index', 'Volver', 'class="btn"') ?>
    <?php echo Form::submit('Verificar Estado', 'class="btn btn-primary"') ?>
    <?php if (count($tablas_existentes) >= 7) echo Html::linkAction('paso3', 'Saltar Paso', 'class="btn"') ?>
</div>
<?php echo Form::close() ?>