<?php View::notify(); ?>

<div class="container-fluid dw-shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <?php echo DwForm::open('', 'post', array('id'=>'form', 'class'=>'dw-validate')); ?>

        <div class="row-fluid">
        	<?php if(APP_OFFICE) { ?>
            <div class="span4">
            	<?php echo DwForm::dbSelect('departamento.sucursal_id', array('sucursal', 'ciudad'), array('config/sucursal', 'getListadoSucursal'), array('todas'=>'Todas'), array('class'=>'input-xlarge input-required mask-pint show-errors'), NULL, 'Sucursal'); ?>
            </div>
            <?php } ?>
            <div class="span4">
                <?php echo DwForm::text('profesion.nombre', array('class'=>'input-xlarge input-required input-alphanum mask-alphanum show-error'), NULL, 'Nombre'); ?>
            </div>
            <div class="span4">
                <?php echo DwForm::text('profesion.observacion', array('class'=>'input-xlarge input-required input-alphanum mask-alphanum show-error', 'autocomplete'=>'off'), NULL, 'Observacion'); ?>
            </div>
        </div>

        <div class="row-fluid">
            <div class="form-actions">
                <?php echo DwButton::save('Guardar Profesion'); ?>
                <?php echo DwButton::reset('form'); ?>
                <?php echo DwButton::cancel(); ?>
            </div>
        </div>

    <?php echo DwForm::close(); ?>

</div>