<?php View::notify(); ?>
<script type="text/javascript">
    $(function() {
        $('table').dwGrid({
            form_search: true,
            form_action: '<?php echo PUBLIC_PATH; ?>config/departamento/buscar/',
            form_load_data : 'dw-shell-content',
            order_attr: '<?php echo (APP_AJAX) ? 'class="dw-ajax dw-spinner"' : ''; ?>',
            order_action: $.KumbiaPHP.publicPath+"config/departamento/listar/"
        });
    });
</script>

<div class="container-fluid dw-shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <div class="btn-toolbar btn-toolbar-top">
        <div class="btn-actions">
            <?php echo DwHtml::button("config/departamento/agregar/", 'agregar', array('class'=>'btn-success'), 'check', APP_AJAX); ?>
        </div>
    </div>

    <div class="dw-overflow" id="data-result">

        <table class="table table-bordered table-hover table-striped table-condensed table-responsive">
            <thead>
                <tr>
                    <th>NUM</th>
                    <th class="col-collapse" data-search="nombre">NOMBRE</th>
                    <th class="col-collapse" data-search="sucursal">SUCURSAL</th>
                    <th class="col-collapse" data-search="observacion">OBSERVACION</th>
                    <th class="btn-actions no-responsive" style="width: 100px;">ACCIONES</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($departamentos->items as $departamento): ?>
                    <?php $key_upd = DwSecurity::getKey($departamento->id, 'upd_departamento'); ?>
                    <?php $key_del = DwSecurity::getKey($departamento->id, 'del_departamento'); ?>
                    <tr>
                        <td><?php echo $departamentos->counter; ?></td>
                        <td><?php echo $departamento->nombre; ?></td>
                        <td><?php echo $departamento->sucursal; ?></td>
                        <td><?php echo $departamento->observacion; ?></td>
                        <td>
                            <?php echo DwHtml::buttonTable('Modificar Departamento', "config/departamento/editar/$key_upd/", null, 'info', 'edit'); ?>
                            <?php echo DwHtml::buttonTable('Eliminar Departamento', "config/departamento/eliminar/$key_del/", array('class'=>'js-confirm', 'confirm-title'=>'Eliminar departamento', 'confirm-body'=>'Está seguro de eliminar este departamento? <br />Recuerda que esta operación no se puede reversar.'), 'danger', 'ban-circle'); ?>
                        </td>
                    </tr>
                    <?php $departamentos->counter++; ?>
                <?php endforeach; ?>
            </tbody>
        </table>

    </div>

    <?php View::partial('paginators/default', false, array('page'=>$departamentos, 'url'=>"config/departamento/listar/$order/")); ?>

</div>