<div class="page-header">
    <h1>Recursos del Sistema
        <?php echo Html::linkAction('escaner', 'Escanear Recursos por Agregar', 'class="btn btn-primary pull-right hidden-phone"') ?>
    </h1>
</div>
<?php View::content() ?>
<?php
echo Form::open('admin/recursos/eliminar', 'post', 'class="form_lista"');
View::partial('backend/barra_superior_listas', FALSE, array('texto' => 'Crear Recurso'));
$dt = new DataTable($recursos);
$dt->addHeaders(Form::check('seleccionar_todos', 'todos', NULL, FALSE));
$dt->addHeaders('id', 'Modulo', 'Controlador');
$dt->addHeaders('Acción', 'Descripción', 'Estado');
$dt->addHeaders('Editar', 'Eliminar');
$dt->check('recursos_id');
$dt->addFields('id', 'modulo', 'controlador');
$dt->addFields('accion', 'descripcion');
$dt->imgLink('figuras/circulo_rojo.png|figuras/circulo_verde.png',
    'admin/recursos/activar|admin/recursos/desactivar', '', 'activo');
$dt->imgLink('figuras/editar.png', 'admin/recursos/editar');
$dt->imgLinkConfirm('figuras/eliminar.png', 'admin/recursos/eliminar', '', '¿Realmente desea Eliminar Este Recurso?');
echo $dt->render('class="table table-bordered table-striped"');
echo Form::close();
?>