<?php View::notify(); ?>
<div class="container-fluid dw-shell-view">
    <?php View::process($page_module, $page_title, $set_title); ?>
    <?php echo DwForm::open('', 'post', array('id'=>'form', 'class'=>'dw-validate')); ?>

        <div class="row-fluid">
            <div class="span4">
                <?php echo DwForm::dbSelect('cobertura.tipo_cobertura', 'descripcion', array('config/tipo_cobertura', 'getListado'), NULL, array('class'=>'input-xlarge input-required mask-pint show-errors "'), NULL ,'Tipo de Cobertura'); ?>
            </div>
            <div class="span4">
                <?php echo DwForm::text('cobertura.descripcion', array('class'=>'input-xlarge input-required mask-alpha show-error data-toggle="tooltip" title="Descripción de la Cobertura"'), $cobertura->descripcion, 'Descripcion'); ?>
            </div>
            <div class="span4">
                <?php echo DwForm::text('cobertura.monto_cobertura', array('class'=>'input-xlarge input-required mask-anum show-error data-toggle="tooltip" title="Monto de la Cobertura"'), $cobertura->monto_cobertura, 'Monto Disponible'); ?>
            </div>

        </div>
        <div class="row-fluid">
            <div class="span4">
                <?php echo DwForm::date('cobertura.fecha_inicio', array('class'=>'input-required mask-date  readonly input-date show-errors data-toggle="tooltip" title="Fecha de Inicio de la Cobertura"'), $cobertura->fecha_inicio, 'Fecha Inicio'); ?>
            </div>
            <div class="span4">
                <?php echo DwForm::date('cobertura.fecha_fin', array('class'=>'input-required mask-date  readonly input-date show-errors data-toggle="tooltip" title="Fecha del Fin de la Cobertura"'), $cobertura->fecha_fin, 'Fecha Fin'); ?>
            </div>        
            <div class="span4">
                <?php echo DwForm::text('cobertura.observacion', array('class'=>'input-xlarge mask-alpha show-error data-toggle="tooltip" title="Observación de la Cobertura"'), NULL, 'Observación'); ?>
            </div>
        </div>

            <?php echo DwForm::hiddenKey('cobertura.id', $cobertura->id); ?>


        <div class="row-fluid">
            <div class="form-actions">
                <?php echo DwButton::save('Guardar Cobertura'); ?>
                <?php echo DwButton::reset('form'); ?>
                <?php echo DwButton::cancel(); ?>
            </div>
        </div>

    <?php echo DwForm::close(); ?>

</div>