<?php View::notify(); ?>

<div class="container-fluid dw-shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <?php echo DwForm::open('', 'post', array('id'=>'form', 'class'=>'dw-validate')); ?>

        <div class="row-fluid">
            <div class="span6">
                <?php echo DwForm::text('cobertura.descripcion', array('class'=>'input-xxlarge input-required input-alphanum mask-alphanum show-error'), NULL, 'Descripcion'); ?>
            </div>
            <div class="span6">
                <?php echo DwForm::Select('cobertura.tipo_cobertura', array('Seleccione','Grupal', 'Individual'), array('class'=>'input-xxlarge input-required mask-pint show-errors'), NULL, 'Tipo Cobertura'); ?>
            </div>
        </div>
        <div class="row-fluid">
            <div class="span6">
                <?php echo DwForm::date('cobertura.fecha_inicio', array('class'=>'input-required mask-date input-date show-errors'), date("Y-m-d"), 'Fecha Inicio'); ?>
            </div>
            <div class="span6">
                <?php echo DwForm::date('cobertura.fecha_fin', array('class'=>'input-required mask-date input-date show-errors'), date("Y-m-d"), 'Fecha Fin'); ?>
            </div>
        </div>
        <div class="row-fluid">
            <div class="span6">
                <?php echo DwForm::text('cobertura.monto_cobertura', array('class'=>'input-xxlarge input-required input-alphanum mask-alphanum show-error'), NULL, 'Monto'); ?>
            </div>
            <div class="span6">
                <?php echo DwForm::text('cobertura.observacion', array('class'=>'input-xxlarge input-alphanum mask-alphanum show-error'), NULL, 'Observacion'); ?>
            </div>
        </div>

        <div class="row-fluid">
            <div class="form-actions">
                <?php echo DwButton::save('Guardar Cobertura'); ?>
                <?php echo DwButton::reset('form'); ?>
                <?php echo DwButton::cancel(); ?>
            </div>
        </div>

    <?php echo DwForm::close(); ?>

</div>