<?php View::notify(); ?>

<script type="text/javascript">
    var ciudades = <?php echo $ciudades; ?>;
    $(function() {
        $('#ciudad').typeahead({
                source: ciudades, items:5
        });
    });
</script>

<div class="container-fluid dw-shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <?php echo DwForm::open('', 'post', array('id'=>'form', 'class'=>'dw-validate')); ?>

        <div class="row-fluid">
            <div class="span6">
                <?php echo DwForm::text('cobertura.descripcion', array('class'=>'input-xxlarge input-required input-alphanum mask-alphanum show-error'), $cobertura->descripcion, 'Nombre de la Cobertura'); ?>
            </div>
            <div class="span6">
                <?php echo DwForm::Select('cobertura.tipo_cobertura', array('Seleccione','Grupal', 'Individual'), array('class'=>'input-xxlarge input-required mask-pint show-errors'), $cobertura->tipo_cobertura, 'Tipo Cobertura'); ?>
            </div>
           
        </div>
        <div class="row-fluid">
            <div class="span6">
                <?php echo DwForm::date('cobertura.fecha_inicio', array('class'=>'input-required mask-date input-date show-errors'), $cobertura->fecha_inicio, 'Fecha Inicio'); ?>
            </div>
            <div class="span6">
                <?php echo DwForm::date('cobertura.fecha_fin', array('class'=>'input-required mask-date input-date show-errors'), $cobertura->fecha_fin,'Fecha Fin'); ?>
            </div>
        </div>

        <div class="row-fluid">
            <div class="span6">
                <?php echo DwForm::text('cobertura.monto_cobertura', array('class'=>'input-xxlarge input-required input-alphanum mask-alphanum show-error', 'autocomplete'=>'off'), $cobertura->monto_cobertura, 'Monto de Cobertura'); ?>
            </div>
            <div class="span6">
                <?php echo DwForm::text('cobertura.observacion', array('class'=>'input-xxlarge input-alphanum mask-alphanum show-error'),  $cobertura->observacion,'Observacion'); ?>
            </div>
        </div>

        </div>

            <?php echo DwForm::hiddenKey('cobertura.id', $cobertura->id); ?>
        </div>

        <div class="row-fluid">
            <div class="form-actions">
                <?php echo DwButton::save('Guardar Cobertura'); ?>
                <?php echo DwButton::reset('form'); ?>
                <?php echo DwButton::cancel(); ?>
            </div>
        </div>

    <?php echo DwForm::close(); ?>

</div>