<?php View::notify(); ?>

<script type="text/javascript">
    $(function() {
        $('table').dwGrid({
            form_search: true,
            form_action: '<?php echo PUBLIC_PATH; ?>config/cobertura/buscar/',
            form_load_data : 'dw-shell-content',
            order_attr: '<?php echo (APP_AJAX) ? 'class="dw-ajax dw-spinner"' : ''; ?>',
            order_action: $.KumbiaPHP.publicPath+"config/cobertura/listar/"
        });
    });
</script>

<div class="container-fluid dw-shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <div class="btn-toolbar btn-toolbar-top">
        <div class="btn-actions">
            <?php echo DwHtml::button("config/cobertura/agregar/", 'agregar', array('class'=>'btn-success'), 'check', APP_AJAX); ?>
        </div>
    </div>

    <div class="dw-overflow" id="data-result">

        <table class="table table-bordered table-hover table-striped table-condensed table-responsive">
            <thead>
                <tr>
                    <th>NUM</th>
                    <th class="col-collapse" data-search="descripcion">DESCRIPCION</th>
                    <th class="col-collapse" data-search="monto">MONTO COBERTURA</th>
                    <th class="col-collapse" data-search="fecha">FECHA INICIO</th>
                    <th class="col-collapse" data-search="direccion">FECHA FIN</th>
                    <th class="col-collapse" data-search="direccion">OBSERVACION</th>
                    <th class="btn-actions no-responsive" style="width: 100px;">ACCIONES</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($coberturas->items as $cobertura): ?>
                    <?php $key_upd = DwSecurity::getKey($cobertura->id, 'upd_cobertura'); ?>
                    <?php $key_del = DwSecurity::getKey($cobertura->id, 'del_cobertura'); ?>
                    <tr>
                        <td><?php echo $coberturas->counter; ?></td>
                        <td><?php echo $cobertura->descripcion; ?></td>
                        <td><?php echo $cobertura->monto_cobertura; ?></td>
                        <td><?php echo $cobertura->fecha_inicio; ?></td>
                        <td><?php echo $cobertura->fecha_fin; ?></td>
                        <td><?php echo $cobertura->observacion; ?></td>
                        <td>
                            <?php echo DwHtml::buttonTable('Modificar Cobertura', "config/cobertura/editar/$key_upd/", null, 'info', 'edit'); ?>
                            <?php echo DwHtml::buttonTable('Eliminar Cobertura', "config/cobertura/eliminar/$key_del/", array('class'=>'js-confirm', 'confirm-title'=>'Eliminar cobertura', 'confirm-body'=>'Está seguro de eliminar esta cobertura? <br />Recuerda que esta operación no se puede reversar.'), 'danger', 'ban-circle'); ?>
                        </td>
                    </tr>
                    <?php $coberturas->counter++; ?>
                <?php endforeach; ?>
            </tbody>
        </table>

    </div>

    <?php View::partial('paginators/default', false, array('page'=>$coberturas, 'url'=>"config/cobertura/listar/$order/")); ?>

</div>