<?php View::notify(); ?>
<style type="text/css">
    .tab-pane { min-height: 200px;}
</style>

<div class="container-fluid dw-shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <?php echo DwForm::open('', 'post', array('id'=>'form', 'class'=>'dw-validate')); ?>

     <?php if(DESKTOP) { ?>
        <ul class="nav nav-tabs">
        <?php } else { ?>
        <ul class="nav nav-pills nav-stacked">
        <?php } ?>
            <li class="active"><a href="#tab1" data-toggle="tab">Cambio de Contraseña</a></li>
        </ul>
        <div class="tab-content">

            <div class="tab-pane active" id="tab1">
             <div class="row-fluid">
                    <div class="span6">
                        <?php echo DwForm::pass('usuario_clave.password', array('class'=>'input-xxlarge input-required input-pass show-error'), '', 'Contraseña'); ?>
                    </div>
                    <div class="span6">
                        <?php echo DwForm::pass('repassword', array('class'=>'input-xxlarge input-required input-repass show-error'), '', 'Confirmación'); ?>
                    </div>
                </div>
            </div>
                <div class="row-fluid">

                    <?php // echo DwForm::hiddenKey('usuario_clave.usuario_id', $usuario_clave->usuario_id); ?>

                    <div class="form-actions">
                        <?php echo DwButton::save('Guardar usuario'); ?>
                        <?php echo DwButton::reset('form'); ?>
                        <?php echo DwButton::cancel(); ?>
                    </div>
                </div>

            </div>
        </div>
    <?php echo DwForm::close(); ?>
</div>

<
