<?php View::notify(); ?>
<div class="container-fluid dw-shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <?php echo DwForm::open('', 'post', array('id'=>'form', 'class'=>'dw-validate')); ?>
		<div class="row-fluid">
            <div class="span4">
                <?php echo DwForm::text('sucursal.sucursal', array('class'=>'input-xlarge input-required input-alphanum mask-alphanum show-error data-toggle="tooltip" title="Nombre de la Sucursal"'), NULL, 'Nombre de la sucursal','Ejemplo Upsa Piritu, Biceabasto La Colonia'); ?>
            </div>
            <div class="span4">
				<?php echo DwForm::dbSelect('sucursal.pais_id', 'nombre', array('params/pais', 'getListadoPais'), NULL, array('class'=>'input-xlarge input-required input-list show-errors data-toggle="tooltip" title="Seleccione El Pais"'), NULL, 'Pais','Ejemplo Venezuela'); ?>
            </div>       
            <div class="span4">
                <label>Estado</label>
                <div id='div_estado'> <select class="input-xlarge"> <option value=""> Seleccione: </option></select></div>
            </div>
       </div>
        <div class="row-fluid">
            <div class="span4">
                <label>Municipio</label>
                <div id='div_municipio'><select class="input-xlarge"> <option value=""> Seleccione: </option></select></div>
            </div>
            <div class="span4">
                <label>Parroquia</label>
                <div id='div_parroquia'><select class="input-xlarge"> <option value=""> Seleccione: </option></select></div>  
            </div>
             <div class="span4">
                <?php echo DwForm::text('sucursal.direccion', array('class'=>'input-xlarge input-required input-alphanum mask-alphanum show-error data-toggle="tooltip" title="Dirección"'), NULL, 'Dirección'); ?>
            </div>
        </div>
        <div class="row-fluid">
            <div class="span4">
                <?php echo DwForm::tel('sucursal.celular', array('class'=>'input-numeric mask-pint show-error data-toggle="tooltip" title="Telefono Movil"'), NULL, 'Telefono Movil','Ejemplo 04143554584'); ?>
            </div>
            <div class="span4">
                <?php echo DwForm::tel('sucursal.telefono', array('class'=>'input-numeric mask-pint show-error data-toggle="tooltip" title="Telefono Fijo"'), NULL, 'Teléfono Fijo','Ejemplo 02556210536'); ?>
            </div>
            <div class="span4">
                <?php echo DwForm::tel('sucursal.fax', array('class'=>'input-numeric mask-pint show-error data-toggle="tooltip" title="Numero del Fax"'), NULL, 'Fax','Ejempo 02556221023'); ?>
            </div>
        </div>
        <div class="row-fluid">
            <div class="form-actions">
                <?php echo DwButton::save('Guardar sucursal'); ?>
                <?php echo DwButton::reset('form'); ?>
                <?php echo DwButton::cancel(); ?>
            </div>
        </div>
    <?php echo DwForm::close(); ?>
</div>

<!-- Script para obtener por Ajax Los Estados en funcion de los paises  -->
<script type='text/javascript'>
$("#sucursal_pais_id").click(function(){
    var pais_id     =   $('#sucursal_pais_id').val();
        $.ajax({
          type: "POST",
          url: "<?php echo PUBLIC_PATH . 'config/sucursal/getEstadoPais/'; ?>",
          data: "pais_id=" + pais_id,
          success: function(html){
            $("#div_estado").html(html);
          }
        });
});
</script>
