<?php View::notify(); ?>
<script type="text/javascript">
    $(function() {
        $('table').dwGrid({
            form_search: true,
            form_action: '<?php echo PUBLIC_PATH; ?>config/sucursal/buscar/',
            form_load_data : 'dw-shell-content',
            order_attr: '<?php echo (APP_AJAX) ? 'class="dw-ajax dw-spinner"' : ''; ?>',
            order_action: $.KumbiaPHP.publicPath+"config/sucursal/buscar/<?php echo $field.'/'.$value.'/'; ?>"
        });
    });
</script>

<div class="container-fluid dw-shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <div class="btn-toolbar btn-toolbar-top">
        <div class="btn-actions">
            <?php echo DwHtml::button("config/sucursal/agregar/", 'agregar', array('class'=>'btn-success'), 'check', APP_AJAX); ?>
            <?php echo DwHtml::button("config/sucursal/listar/", 'listar', array('class'=>'btn-warning'), 'ok', APP_AJAX); ?>
        </div>
    </div>

    <div class="dw-overflow" id="data-result">

        <table class="table table-bordered table-hover table-striped table-condensed table-responsive">
            <thead>
                <tr>
                    <th>NUM</th>
                    <th class="col-collapse" data-search="sucursal">SUCURSAL</th>
                    <th class="col-collapse" data-search="direccion">DIRECCION</th>
                    <th class="col-collapse" data-search="parroquia">PARROQUIA</th>
                    <th class="col-collapse" data-search="celular">CELULAR</th>
                    <th class="col-collapse" data-search="telefono">TELEFONO</th>
                    <th class="col-collapse" data-search="fax">FAX</th>
                    <th class="btn-actions no-responsive" style="width: 100px;">ACCIONES</th>
                </tr>
            </thead>
            <tbody>
                <?php if($sucursales) { ?>
                <?php foreach($sucursales->items as $sucursal): ?>
                    <?php $key_upd = DwSecurity::getKey($sucursal->id, 'upd_sucursal'); ?>
                    <?php $key_del = DwSecurity::getKey($sucursal->id, 'del_sucursal'); ?>
                    <tr>
                        <td><?php echo $sucursales->counter; ?></td>
                        <td><?php echo ($field=='sucursal') ? DwUtils::resaltar($value, $sucursal->sucursal) : $sucursal->sucursal; ?></td>
                        <td><?php echo ($field=='direccion') ? DwUtils::resaltar($value, $sucursal->direccion) : $sucursal->direccion; ?></td>
                        <td><?php echo ($field=='parroquia') ? DwUtils::resaltar($value, $sucursal->nombre) : $sucursal->nombre; ?></td>
                        <td><?php echo ($field=='celular') ? DwUtils::resaltar($value, $sucursal->celular) : $sucursal->celular; ?></td>
                        <td><?php echo ($field=='telefono') ? DwUtils::resaltar($value, $sucursal->telefono) : $sucursal->telefono; ?></td>
                        <td><?php echo ($field=='fax') ? DwUtils::resaltar($value, $sucursal->fax) : $sucursal->fax; ?></td>
                        <td>
                            <?php echo DwHtml::buttonTable('Modificar sucursal', "config/sucursal/editar/$key_upd/", NULL, 'info', 'edit'); ?>
                            <?php echo DwHtml::buttonTable('Eliminar sucursal', "config/sucursal/eliminar/$key_del/", array('class'=>'js-confirm', 'confirm-title'=>'Eliminar sucursal', 'confirm-body'=>'Está seguro de eliminar esta sucursal? <br />Recuerda que esta operación no se puede reversar.'), 'danger', 'ban-circle'); ?>                      
                        </td>
                    </tr>
                    <?php $sucursales->counter++; ?>
                <?php endforeach; ?>
            </tbody>
            <?php } ?>
        </table>

    </div>

    <?php View::partial('paginators/default', false, array('page'=>$sucursales, 'url'=>"config/sucursal/buscar/$field/$value/$order/")); ?>
</div>
