<?php View::notify(); ?>
<div class="container-fluid dw-shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <?php echo DwForm::open('', 'post', array('id'=>'form', 'class'=>'dw-validate')); ?>

		<div class="row-fluid">
            <div class="span6">
                <?php echo DwForm::text('sucursal.sucursal', array('class'=>'input-xxlarge input-required input-alphanum mask-alphanum show-error'), NULL, 'Nombre de la sucursal'); ?>
            </div>
            <div class="span6">
				<?php echo DwForm::dbSelect('sucursal.pais_id', 'nombre', array('params/pais', 'getListadoPais'), NULL, array('class'=>'input-xxlarge input-required input-list show-errors'), NULL, 'Pais'); ?>
            </div>            
        </div>
        <div class="row-fluid">
            <div class="span6">
                <?php echo DwForm::dbSelect('sucursal.estado_id', 'nombre', array('params/estado', 'getListadoEstado'), NULL, array('class'=>'input-xxlarge input-required input-list show-errors'), NULL, 'Estado'); ?>
            </div>
            <div class="span6">
                <?php echo DwForm::dbSelect('sucursal.municipio_id', 'nombre', array('params/municipio', 'getListadoMunicipio'), NULL, array('class'=>'input-xxlarge input-required input-list show-errors'), NULL, 'Municipio'); ?>				
            </div>
        </div>
        <div class="row-fluid">
            <div class="span6">
				<?php echo DwForm::dbSelect('sucursal.parroquia_id', 'nombre', array('params/parroquia', 'getListadoParroquia'), NULL, array('class'=>'input-xxlarge input-required input-list show-errors'), NULL, 'Parroquia'); ?>				                
                
            </div>
            <div class="span6">
                <?php echo DwForm::text('sucursal.direccion', array('class'=>'input-xxlarge input-required input-alphanum mask-alphanum show-error'), NULL, 'Dirección'); ?>
            </div>
        </div>
        <div class="row-fluid">
            <div class="span4">
                <?php echo DwForm::tel('sucursal.celular', array('class'=>'input-numeric mask-pint show-error'), NULL, 'Celular'); ?>
            </div>
            <div class="span4">
                <?php echo DwForm::tel('sucursal.telefono', array('class'=>'input-numeric mask-pint show-error'), NULL, 'Teléfono'); ?>
            </div>
            <div class="span4">
                <?php echo DwForm::tel('sucursal.fax', array('class'=>'input-numeric mask-pint show-error'), NULL, 'Fax'); ?>
            </div>
        </div>


            <?php echo DwForm::hiddenKey('sucursal.id', $sucursal->id); ?>
        </div>

        <div class="row-fluid">
            <div class="form-actions">
                <?php echo DwButton::save('Guardar sucursal'); ?>
                <?php echo DwButton::reset('form'); ?>
                <?php echo DwButton::cancel(); ?>
            </div>
        </div>
    <?php echo DwForm::close(); ?>
</div>
