<?php View::notify(); ?>

<div class="container-fluid dw-shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <?php echo DwForm::open('', 'post', array('id'=>'form', 'class'=>'dw-validate')); ?>

        <div class="row-fluid">
            <div class="span4">
                <?php echo DwForm::text('recaudo.nombre', array('class'=>'input-xlarge input-required show-error data-toggle="tooltip" title="Ingrese nombre del recaudo"'), NULL, 'Nombre'); ?>
            </div>
            <div class="span4">
                <?php echo DwForm::text('recaudo.tipo', array('class'=>'input-xlarge input-required show-error data-toggle="tooltip" title="Ingrese tipo de recaudo', 'autocomplete'=>'off'), NULL, 'Tipo'); ?>
            </div>
            <div class="span4">
                <?php echo DwForm::text('recaudo.observacion', array('class'=>'input-xlarge show-error data-toggle="tooltip" title="Ingrese observación de recaudo"', 'autocomplete'=>'off'), NULL, 'Observacion'); ?>
            </div>
        </div>

        <div class="row-fluid">
            <div class="form-actions">
                <?php echo DwButton::save('Guardar Recaudo'); ?>
                <?php echo DwButton::reset('form'); ?>
                <?php echo DwButton::cancel(); ?>
            </div>
        </div>

    <?php echo DwForm::close(); ?>

</div>
