<?php View::notify(); ?>

<div class="container-fluid dw-shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <?php echo DwForm::open('', 'post', array('id'=>'form', 'class'=>'dw-validate')); ?>

        <div class="row-fluid">
            <div class="span4">
                <?php echo DwForm::text('recaudo.nombre', array('class'=>'input-xlarge input-required show-error'), $recaudo->nombre, 'Recaudo'); ?>
            </div>
      
            <div class="span4">
                <?php echo DwForm::text('recaudo.tipo', array('class'=>'input-xlarge input-required show-error'), $recaudo->tipo
                , 'Tipo Recaudo'); ?>
            </div>

              <div class="span4">
                <?php echo DwForm::text('recaudo.observacion', array('class'=>'input-xlarge input-alphanum mask-alphanum show-error'), $recaudo->observacion
                , 'Observacion'); ?>
            </div>
        </div>
            <?php echo DwForm::hiddenKey('recaudo.id', $recaudo->id); ?>
        </div>

        <div class="row-fluid">
            <div class="form-actions">
                <?php echo DwButton::save('Guardar recaudo'); ?>
                <?php echo DwButton::reset('form'); ?>
                <?php echo DwButton::cancel(); ?>
            </div>
        </div>

    <?php echo DwForm::close(); ?>
</div>