<?php View::notify(); ?>
<style type="text/css">
    .tab-pane { min-height: 200px;}
</style>

<div class="container-fluid dw-shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <?php echo DwForm::open('', 'post', array('id'=>'form', 'class'=>'dw-validate')); ?>

     <?php if(DESKTOP) { ?>
        <ul class="nav nav-tabs">
        <?php } else { ?>
        <ul class="nav nav-pills nav-stacked">
        <?php } ?>
            <li class="active"><a href="#tab1" data-toggle="tab">Información de cuenta</a></li>
            <li><a href="#tab2" data-toggle="tab">Información personal</a></li>
            <li><a href="#tab3" data-toggle="tab">Cargar imágen</a></li>
        </ul>
        <div class="tab-content">

            <div class="tab-pane active" id="tab1">
                <div class="row-fluid">
                    <div class="span12">
                        <?php echo DwForm::text('usuario.login', array('class'=>'input-large readonly'), $usuario->login, 'Usuario'); ?>
                    </div>
                </div>

                <div class="row-fluid">
                    <div class="span4">
                        <?php echo DwForm::pass('oldpassworsd', array('class'=>'input-large show-error'), '', 'Contraseña anterior'); ?>
                    </div>
                    <div class="span4">
                        <?php echo DwForm::pass('usuario.password', array('class'=>'input-large input-pass show-error'), '', 'Nueva Contraseña'); ?>
                    </div>
                    <div class="span4">
                        <?php echo DwForm::pass('repassword', array('class'=>'input-large input-repass show-error'), '', 'Confirmación Contraseña'); ?>
                    </div>
                </div>
                <div class="row-fluid">
                    <div class="span4">
                    <label>Cambiar Preguntas</label>
                        <?php echo DwForm::check('pregunta', '1','',false); ?>
                    </div>
                </div>
                <div class="row-fluid">
                    <div class="span3">
                         <?php echo DwForm::select('usuario.pregunta1', array(''=>'Seleccione:', '1'=>'¿Cual es el Nombre de tu mascota?', '2'=>'Nombre de tu primer perro','A-'=>'A-', 'A+'=>'A+', 'AB+'=>'AB+', 'AB-'=>'AB-'), array('class'=>'input-large show-error'), NULL, 'Pregunta 1'); ?>
                    </div>
                    <div class="span3">
                        <?php echo DwForm::text('usuario.respuesta1', array('class'=>'input-large '), '','Pregunta nro 1'); ?>
                    </div>
                    <div class="span3">
                         <?php echo DwForm::select('usuario.pregunta2', array(''=>'Seleccione:', '1'=>'¿Cual es el Nombre de tu mascota?', '2'=>'Nombre de tu primer perro','A-'=>'A-', 'A+'=>'A+', 'AB+'=>'AB+', 'AB-'=>'AB-'), array('class'=>'input-large show-error'), NULL, 'Pregunta 1'); ?>
                    </div>
                    <div class="span3">
                        <?php echo DwForm::text('usuario.respuesta2', array('class'=>'input-large'), '','Pregunta nro 2'); ?>
                    </div>
                </div>
            </div>

            <div class="tab-pane" id="tab2">

                <div class="row-fluid">
                    <div class="span4">
                        <?php echo DwForm::text('persona.celular', array('class'=>'input-xlarge input-numeric input-required mask-alphanum show-error'), $usuario->celular, 'Celular'); ?>
                    </div>
                    <div class="span4">
                        <?php echo DwForm::text('persona.telefono', array('class'=>'input-numeric input-xlarge input-required mask-alphanum show-error'), $usuario->telefono, 'Telefono fijo'); ?>
                    </div>
                    <div class="span4">
                        <?php echo DwForm::email('persona.correo_electronico', array('class'=>'input-xlarge input-required mask-alphanum show-error'), $usuario->correo_electronico, 'Correo Electronico'); ?>
                    </div>
                </div>




            </div>

            <div class="tab-pane" id="tab3">

                <div class="row-fluid fileupload-buttonbar">

                    <div class="span6" style="margin-bottom: 20px;">

                        <div class="row-fluid">

                            <div class="span6">
                                <div class="span12">
                                    <span class="btn btn-success fileinput-button">
                                        <i class="icon-plus icon-white"></i> <span>Fotografía...</span>
                                        <input id="fotografia" type="file" name="fotografia" class="input-large input-upload">
                                    </span>
                                </div>

                                <div class="span12" style="margin-left: 0px;">
                                    <div id="upload-progress" class="fileupload-progress fade">
                                        <div class="progress progress-success progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100" style="margin-top: 5px;">
                                            <div class="bar" style="width:0%;"></div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="span6">
                                <div class="dw-picture-profile dw-text-center dw-text-middle dw-shadow-dark" style="margin: 5px auto 0px;">
                                    <?php echo DwHtml::img("upload/personas/$usuario->fotografia", "$usuario->nombre $usuario->apellido", array('id'=>'img-persona')); ?>
                                </div>
                            </div>

                        </div>

                    </div>

                </div>

                <?php echo DwForm::hidden('persona.fotografia', NULL, $usuario->fotografia); ?>
                <?php echo DwForm::hiddenKey('usuario.id', $usuario->id); ?>
            </div>

            <div class="row-fluid">
                <div class="form-actions">
                    <?php echo DwButton::save('Actualizar mis datos'); ?>
                    <?php echo DwButton::reset('form'); ?>
                    <?php echo DwButton::cancel(); ?>
                </div>
            </div>

        </div>

    <?php echo DwForm::close(); ?>

</div>

<?php View::partial('jquery.file-upload'); ?>

<script type="text/javascript">
$(document).ready(function () {
 $('#usuario_pregunta1').attr("disabled", true);
 $('#usuario_respuesta1').attr("disabled", true);
 $('#usuario_pregunta2').attr("disabled", true);
 $('#usuario_respuesta2').attr("disabled", true);
});
</script>

<script type="text/javascript">
$('#pregunta').click(function(){
    if( $('#usuario_pregunta1').prop('disabled') == true ){
        $('#usuario_pregunta1').prop('disabled', '');
        $('#usuario_respuesta1').prop("disabled", '');
        $('#usuario_pregunta2').prop("disabled", '');
        $('#usuario_respuesta2').prop("disabled", '');
    }
    else{
        $('#usuario_pregunta1').attr("disabled", true);
        $('#usuario_respuesta1').attr("disabled", true);
        $('#usuario_pregunta2').attr("disabled", true);
        $('#usuario_respuesta2').attr("disabled", true);
    }
  });
</script>

<script type="text/javascript">

    $('#fotografia').fileupload({
        url: '<?php echo PUBLIC_PATH; ?>sistema/mi_cuenta/upload/',
        dataType: 'json',
        maxFileSize: 2000000, //2MB
        acceptFileTypes: /(\.|\/)(gif|jpe?g|png)$/i,
        start: function() {
            $("#dw-message").empty();
            $('#upload-progress').removeClass('fade');
            $('.bar').parent().removeClass('progress-danger').addClass('progress-success');
            $('[type=submit]').attr('disabled', 'disabled');
        },
        progress: function (e, data) {
            var progress = parseInt(data.loaded / data.total * 100, 10);
            $('.bar').css('width',progress + '%');
        },
        add: function (e, data) {
            var jqXHR = data.submit()
            .done(function (result, textStatus, jqXHR) {
                if(textStatus!='success' || result.error!=null) {
                    $('.bar').parent().removeClass('progress-success').addClass('progress-danger');
                    DwMessage('Oops! el archivo no se ha podido cargar. <br />Detalle del error: '+(result.error!=null) ? result.error : textStatus);
                } else {
                    DwMessage('El archivo se ha cargado correctamente!', 'success');
                    $("#persona_fotografia").val(result.name);
                    $("#img-persona").attr('src', '<?php echo PUBLIC_PATH; ?>img/upload/personas/'+result.name);
                }
            })
            .fail(function (jqXHR, textStatus, errorThrown) {
                if(textStatus!=null){
                    DwMessage('Oops! el archivo no se ha podido cargar. <br />Detalle del error: '+textStatus);
                    $('.bar').parent().removeClass('progress-success').addClass('progress-danger');
                    setTimeout(function() { $('#upload-progress').addClass('fade'); }, 1000);
                } else {
                    DwMessage('Oops! al parecer el archivo no es una imágen válida. <br />Intenta con otro archivo.');
                    $('.bar').parent().removeClass('progress-success').addClass('progress-danger');
                    $('#upload-progress').addClass('fade');
                }
            })
            .always(function () {
                setTimeout(function() { $('#upload-progress').addClass('fade'); $('.bar').css('width','0%'); }, 1000);
                $('[type=submit]').removeAttr('disabled');
            });
        }
    });
</script>

