<?php View::notify(); ?>
<script type="text/javascript">
    $(function() {
        $('table').dwGrid({
            form_search: true,
            form_action: '<?php echo PUBLIC_PATH; ?>config/profesion/buscar/',
            form_load_data : 'dw-shell-content',
            order_attr: '<?php echo (APP_AJAX) ? 'class="dw-ajax dw-spinner"' : ''; ?>',
            order_action: $.KumbiaPHP.publicPath+"config/profesion/listar/"
        });
    });
</script>
<div class="container-fluid dw-shell-view">
    <?php View::process($page_module, $page_title, $set_title); ?>

    <div class="btn-toolbar btn-toolbar-top">
        <div class="btn-actions">
            <?php echo DwHtml::button("config/profesion/agregar/", 'agregar', array('class'=>'btn-success'), 'check', APP_AJAX); ?>
        </div>
    </div>

    <div class="dw-overflow" id="data-result" >

        <table class="table table-bordered table-hover table-striped table-condensed table-responsive">
            <thead>
                <tr>
                    <th>NUM</th>
                    <th class="col-collapse" data-search="profesion">NOMBRE</th>
                    <th class="col-collapse" data-search="observacion">OBSERVACION</th>
                    <th class="btn-actions no-responsive" style="width: 100px;">ACCIONES</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($profesiones->items as $profesion): ?>
                    <?php $key_upd = DwSecurity::getKey($profesion->id, 'upd_profesion'); ?>
                    <?php $key_del = DwSecurity::getKey($profesion->id, 'del_profesion'); ?>
                    <tr>
                        <td><?php echo $profesiones->counter; ?></td>
                        <td><?php echo $profesion->nombre; ?></td>
                        <td><?php echo $profesion->observacion; ?></td>
                        <td>
                            <?php echo DwHtml::buttonTable('Modificar Profeson', "config/profesion/editar/$key_upd/", null, 'info', 'edit'); ?>
                            <?php echo DwHtml::buttonTable('Eliminar Profesion', "config/profesion/eliminar/$key_del/", array('class'=>'js-confirm', 'confirm-title'=>'Eliminar profesion', 'confirm-body'=>'Está seguro de eliminar esta profesion? <br />Recuerda que esta operación no se puede reversar.'), 'danger', 'ban-circle'); ?>
                        </td>
                    </tr>
                    <?php $profesiones->counter++; ?>
                <?php endforeach; ?>
            </tbody>
        </table>

    </div>

    <?php View::partial('paginators/default', false, array('page'=>$profesiones, 'url'=>"config/profesion/listar/$order/")); ?>

</div>