<?php View::notify(); ?>
<div class="container-fluid dw-shell-view">
    
    <?php View::process($page_module, $page_title, $set_title); ?>
            <?php if(Session::get('perfil_id')<=3) { ?>
        

      <div class="row">
      	<div class="span6">
      		<div class="widget stacked">
					
				<div class="widget-header">
					<i class="icon-star"></i>
					<h3>Estadisticas</h3>
				</div> <!-- /widget-header -->
				<div class="widget-content">
                    <div style="width:80%">
                    <h5>Historico de Solicitudes Anuales</h5>
                        <div>
                            <canvas id="canvas" height="450" width="600"></canvas>
                        </div>
                                            <div id="lineLegend"></div>

                    </div>
				</div> <!-- /widget-content -->
					
			</div> <!-- /widget -->	
        </div> <!-- /span6 -->
        <div class="span6">
        			<div class="widget stacked">
					
				<div class="widget-header">
					<i class="icon-signal"></i>
					<h3>Graficos</h3>
				</div> <!-- /widget-header -->
				
				<div class="widget-content">					
                
                
                
                
                
				</div> <!-- /widget-content -->
			
			</div> <!-- /widget -->
        </div>	

<div class="span6">
			<div class="widget stacked widget-table action-table">
					
				<div class="widget-header">
					<i class="icon-th-list"></i>
					<h3>Solicitudes Por Aprobar</h3>
				</div> <!-- /widget-header -->
				
				<div class="widget-content">
					
					<table class="table table-striped table-bordered">
						<thead>
							<tr>
                                <th>Codigo Solicitud</th>
                                <th>Titular</th>
                                <th>Beneficiario</th>
								<th>Proveedor</th>
								<th>Servicio</th>
                                
								<th class="td-actions">Acciones</th>
							</tr>
						</thead>
						<tbody>
                             <?php foreach($solicitud_servicios as $solicitud_servicio): ?>
							<tr>
                        <td><?php echo $solicitud_servicio->codigo_solicitud; ?></td>
                        <td><?php echo strtoupper($solicitud_servicio->nombre); echo ' '; echo strtoupper($solicitud_servicio->apellido);?></td>
                        <td><?php echo strtoupper($solicitud_servicio->nombre); echo ' '; echo strtoupper($solicitud_servicio->apellido);?></td>
                        <td><?php echo strtoupper($solicitud_servicio->proveedor); ?></td>
                        <td><?php echo strtoupper($solicitud_servicio->servicio); ?></td>
								<td class="td-actions">
									<a href="javascript:;" class="btn btn-small btn-warning">
										<i class="btn-icon-only icon-ok"></i>										
									</a>
									
									<a href="javascript:;" class="btn btn-small">
										<i class="btn-icon-only icon-remove"></i>										
									</a>
								</td>
							</tr>
                                            <?php endforeach; ?>

							</tbody>
						</table>
					
				</div> <!-- /widget-content -->
			
			</div> <!-- /widget -->
</div>
        </div>

       </div> <!-- /row -->	
 
    <?php } else { ?>

        <div class="span6">

        			<div class="widget widget-nopad stacked">
						
				<div class="widget-header">
					<i class="icon-list-alt"></i>
					<h3>Solicitudes </h3>
				</div> <!-- /widget-header -->
				
				<div class="widget-content">
					
					<ul class="news-items">
						<li>
							
							<div class="news-item-detail">										
								<a href="javascript:;" class="news-item-title">Duis aute irure dolor in reprehenderit</a>
								<p class="news-item-preview">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore.</p>
							</div>
							
							<div class="news-item-date">
								<span class="news-item-day">08</span>
								<span class="news-item-month">Mar</span>
							</div>
						</li>
						<li>
							<div class="news-item-detail">										
								<a href="javascript:;" class="news-item-title">Duis aute irure dolor in reprehenderit</a>
								<p class="news-item-preview">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore.</p>
							</div>
							
							<div class="news-item-date">
								<span class="news-item-day">08</span>
								<span class="news-item-month">Mar</span>
							</div>
						</li>
						<li>
							<div class="news-item-detail">										
								<a href="javascript:;" class="news-item-title">Duis aute irure dolor in reprehenderit</a>
								<p class="news-item-preview">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore.</p>
							</div>
							
							<div class="news-item-date">
								<span class="news-item-day">08</span>
								<span class="news-item-month">Mar</span>
							</div>
						</li>
					</ul>
					
				</div> <!-- /widget-content -->
			
			</div> <!-- /widget -->	
        </div>


        <?php } ?>
<!-- 
    <p>Sesion ID: <?php  echo Session::get('id'); ?> </p>
+     <p>Sesion TITULAR_ID: <?php  echo Session::get('titular_id'); ?> </p>
+     <p>Sesion LOGIN: <?php  echo Session::get('login'); ?> </p>
+     <p>Sesion TEMA: <?php  echo Session::get('tema'); ?> </p>
+     <p>Sesion AJAX: <?php  echo Session::get('ajax'); ?> </p>
+     <p>Sesion DATAGRID: <?php  echo Session::get('datagrid'); ?> </p>
+     <p>Sesion PERFIL_ID: <?php  echo Session::get('perfil_id'); ?> </p>
+     <p>Sesion IP: <?php  echo Session::get('ip'); ?> </p>
+
+     <p>Sesion : <?php  echo var_dump($_SESSION); ?> </p>
-->	
</div>

	<script>
		var randomScalingFactor = function(){ return Math.round(Math.random()*100)};
		var lineChartData = {
			labels : ["Enero","Febrero","Marzo","Abril","Mayo","Junio","Julio"],
			datasets : [
				{
					label: "Farmacias",
					fillColor : "rgba(210,100,220,0.2)",
					strokeColor : "rgba(210,100,220,1)",
					pointColor : "rgba(210,100,220,1)",
					pointStrokeColor : "#fff",
					pointHighlightFill : "#fff",
					pointHighlightStroke : "rgba(210,100,220,1)",
					data : [randomScalingFactor(),randomScalingFactor(),randomScalingFactor(),randomScalingFactor(),randomScalingFactor(),randomScalingFactor(),randomScalingFactor()],
                    title : 'Farmacias'
				},
				{
					label: "Clinicas",
					fillColor : "rgba(220,220,220,0.2)",
					strokeColor : "rgba(220,220,220,1)",
					pointColor : "rgba(220,220,220,1)",
					pointStrokeColor : "#fff",
					pointHighlightFill : "#fff",
					pointHighlightStroke : "rgba(220,220,220,1)",
					data : [randomScalingFactor(),randomScalingFactor(),randomScalingFactor(),randomScalingFactor(),randomScalingFactor(),randomScalingFactor(),randomScalingFactor()],
                    title : 'Clinicas'
				},

				{
					label: "Reembolsos",
					fillColor : "rgba(151,187,205,0.2)",
					strokeColor : "rgba(151,187,205,1)",
					pointColor : "rgba(151,187,205,1)",
					pointStrokeColor : "#fff",
					pointHighlightFill : "#fff",
					pointHighlightStroke : "rgba(151,187,205,1)",
					data : [randomScalingFactor(),randomScalingFactor(),randomScalingFactor(),randomScalingFactor(),randomScalingFactor(),randomScalingFactor(),randomScalingFactor()],
                    title : 'Reembolsos'
				}
			]

		}

	window.onload = function(){
		var ctx = document.getElementById("canvas").getContext("2d");
		window.myLine = new Chart(ctx).Line(lineChartData, {
			responsive: true
		});
	    legend(document.getElementById("lineLegend"), lineChartData);
  
    
    
    
    }


	</script>















       
