<?php View::notify(); ?>
<div class="container-fluid dw-shell-view">
    
    <?php View::process($page_module, $page_title, $set_title); ?>

      <div class="row">
      	<div class="span6">
      		<div class="widget stacked">
					
				<div class="widget-header">
					<i class="icon-star"></i>
					<h3>Estadisticas</h3>
				</div> <!-- /widget-header -->
				
				<div class="widget-content">
					
					<div class="stats">
						
						<div class="stat">
							<span class="stat-value"><?php echo  $codigodd1; ?></span>									
							Tituares Registrados
						</div> <!-- /stat -->
						
						<div class="stat">
							<span class="stat-value"><?php echo  $codigodd2; ?></span>									
							Beneficiarios Registrados
						</div> <!-- /stat -->
						
						<div class="stat">
							<span class="stat-value"><?php echo  $codigodd; ?></span>									
							Solicitudes
						</div> <!-- /stat -->
						
					</div> <!-- /stats -->
					
					
					<div id="chart-stats" class="stats">
						
						<div class="stat stat-chart">							
							<div id="donut-chart" class="chart-holder"></div> <!-- #donut -->							
						</div> <!-- /substat -->
						
						<div class="stat stat-time">									
							<span class="stat-value"><?php echo  $ct; ?>%</span>
							Promedio de Solicitudes por Beneficiarios
						</div> <!-- /substat -->
						
					</div> <!-- /substats -->
					
				</div> <!-- /widget-content -->
					
			</div> <!-- /widget -->	
        </div> <!-- /span6 -->
        <div class="span6">
        			<div class="widget stacked">
					
				<div class="widget-header">
					<i class="icon-signal"></i>
					<h3>Graficos</h3>
				</div> <!-- /widget-header -->
				
				<div class="widget-content">					
					<div id="area-chart" class="chart-holder"></div>					
				</div> <!-- /widget-content -->
			
			</div> <!-- /widget -->
        </div>	
        <div class="span6">

        			<div class="widget widget-nopad stacked">
						
				<div class="widget-header">
					<i class="icon-list-alt"></i>
					<h3>Solicitudes </h3>
				</div> <!-- /widget-header -->
				
				<div class="widget-content">
					
					<ul class="news-items">
						<li>
							
							<div class="news-item-detail">										
								<a href="javascript:;" class="news-item-title">Duis aute irure dolor in reprehenderit</a>
								<p class="news-item-preview">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore.</p>
							</div>
							
							<div class="news-item-date">
								<span class="news-item-day">08</span>
								<span class="news-item-month">Mar</span>
							</div>
						</li>
						<li>
							<div class="news-item-detail">										
								<a href="javascript:;" class="news-item-title">Duis aute irure dolor in reprehenderit</a>
								<p class="news-item-preview">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore.</p>
							</div>
							
							<div class="news-item-date">
								<span class="news-item-day">08</span>
								<span class="news-item-month">Mar</span>
							</div>
						</li>
						<li>
							<div class="news-item-detail">										
								<a href="javascript:;" class="news-item-title">Duis aute irure dolor in reprehenderit</a>
								<p class="news-item-preview">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore.</p>
							</div>
							
							<div class="news-item-date">
								<span class="news-item-day">08</span>
								<span class="news-item-month">Mar</span>
							</div>
						</li>
					</ul>
					
				</div> <!-- /widget-content -->
			
			</div> <!-- /widget -->	
        </div>
<div class="span6">
			<div class="widget stacked widget-table action-table">
					
				<div class="widget-header">
					<i class="icon-th-list"></i>
					<h3>Estatus de Upsas</h3>
				</div> <!-- /widget-header -->
				
				<div class="widget-content">
					
					<table class="table table-striped table-bordered">
						<thead>
							<tr>
								<th>Engine</th>
								<th>Browser</th>
								<th class="td-actions"></th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td>Trident</td>
								<td>Internet
									 Explorer 4.0</td>
								<td class="td-actions">
									<a href="javascript:;" class="btn btn-small btn-warning">
										<i class="btn-icon-only icon-ok"></i>										
									</a>
									
									<a href="javascript:;" class="btn btn-small">
										<i class="btn-icon-only icon-remove"></i>										
									</a>
								</td>
							</tr>
							<tr>
								<td>Trident</td>
								<td>Internet
									 Explorer 5.0</td>
								<td class="td-actions">
									<a href="javascript:;" class="btn btn-small btn-warning">
										<i class="btn-icon-only icon-ok"></i>										
									</a>
									
									<a href="javascript:;" class="btn btn-small">
										<i class="btn-icon-only icon-remove"></i>										
									</a>
								</td>
							</tr>
							<tr>
								<td>Trident</td>
								<td>Internet
									 Explorer 5.5</td>
								<td class="td-actions">
									<a href="javascript:;" class="btn btn-small btn-warning">
										<i class="btn-icon-only icon-ok"></i>										
									</a>
									
									<a href="javascript:;" class="btn btn-small">
										<i class="btn-icon-only icon-remove"></i>										
									</a>
								</td>
							</tr>
							<tr>
								<td>Trident</td>
								<td>Internet
									 Explorer 5.5</td>
								<td class="td-actions">
									<a href="javascript:;" class="btn btn-small btn-warning">
										<i class="btn-icon-only icon-ok"></i>										
									</a>
									
									<a href="javascript:;" class="btn btn-small">
										<i class="btn-icon-only icon-remove"></i>										
									</a>
								</td>
							</tr>
							<tr>
								<td>Trident</td>
								<td>Internet
									 Explorer 5.5</td>
								<td class="td-actions">
									<a href="javascript:;" class="btn btn-small btn-warning">
										<i class="btn-icon-only icon-ok"></i>										
									</a>
									
									<a href="javascript:;" class="btn btn-small">
										<i class="btn-icon-only icon-remove"></i>										
									</a>
								</td>
							</tr>
							<tr>
								<td>Trident</td>
								<td>Internet
									 Explorer 5.5</td>
								<td class="td-actions">
									<a href="javascript:;" class="btn btn-small btn-warning">
										<i class="btn-icon-only icon-ok"></i>										
									</a>
									
									<a href="javascript:;" class="btn btn-small">
										<i class="btn-icon-only icon-remove"></i>										
									</a>
								</td>
							</tr>
							</tbody>
						</table>
					
				</div> <!-- /widget-content -->
			
			</div> <!-- /widget -->
</div>
        </div>
<div class="span6">
<table class="table table-bordered table-hover table-striped table-condensed table-responsive">
            <thead>
                <tr>
                    <th>NUM</th>
                    <th class="col-collapse" data-search="fecha">FECHA</th>
                    <th class="col-collapse" data-search="codigo">CODIGO</th>
                    <th class="col-collapse" data-search="titular">TITULAR</th>
                    <th class="col-collapse" data-search="beneficiario">BENEFICIARIO</th>
                    <th class="col-collapse" data-search="proveedor">PROVEEDOR</th>
                    <th class="col-collapse" data-search="servicio">SERVICIO</th>
                    <th class="col-collapse" data-search="observacion">OBSERVACION</th>
                    <th class="col-collapse" data-search="tiposolicitud">TIPO SOLICITUD</th>
                    <th class="col-collapse" data-search="estado">ESTADO</th>
                    <th class="btn-actions no-responsive" style="width: 100px;">ACCIONES</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($solicitud_servicios as $solicitud_servicio): ?>
                
                    <tr>
                        <td><?php echo $solicitud_servicios->counter; ?></td>
                        <td><?php echo $solicitud_servicio->fecha_solicitud; ?></td>
                        <td><?php echo $solicitud_servicio->codigo_solicitud; ?></td>
                        <td><?php echo strtoupper($solicitud_servicio->nombre); echo ' '; echo strtoupper($solicitud_servicio->apellido);?></td>
                        <td><?php echo strtoupper($solicitud_servicio->nombre); echo ' '; echo strtoupper($solicitud_servicio->apellido);?></td>
                        <td><?php echo strtoupper($solicitud_servicio->proveedor); ?></td>
                        <td><?php echo strtoupper($solicitud_servicio->servicio); ?></td>
                        <td><?php echo strtoupper($solicitud_servicio->observacion); ?></td>
                        <td><?php echo strtoupper($solicitud_servicio->tiposolicitud); ?></td>
                        <td><?php echo ($solicitud_servicio->estado_solicitud == 'R') ? '<span class="label label-success" title="'.$solicitud_servicio->tiposolicitud.' PENDIENTE POR APROBAR" rel="tooltip">EN ESPERA </span>' : '<span class="label label-important" title="'.$solicitud_servicio->estado_solicitud.' RECHAZADA CON OBSERVACIONES" rel="tooltip">RECHAZADA</span>'; ; ?></td>
                        </td>
                        <td>
                         <?php echo ($solicitud_servicio->estado_solicitud == 'R') ? DwHtml::buttonTable('MODIFICAR', "solicitudes/solicitud_servicio/editar/$key_upd/", null, 'info','edit') : DwHtml::buttonTable('MODIFICAR', "solicitudes/solicitud_servicio/modificar/$key_upd/", null, 'info', 'edit');  ?>
                            <?php echo DwHtml::buttonTable('Eliminar Solicitud', "solicitudes/solicitud_servicio/eliminar/$key_del/", array('class'=>'js-confirm', 'confirm-title'=>'Eliminar solicitud_medicina', 'confirm-body'=>'Está seguro de eliminar este solicitud_medicina? <br />Recuerda que esta operación no se puede reversar.'), 'danger', 'ban-circle'); ?>
                        </td>
                    </tr>
                    <?php $solicitud_servicios->counter++; ?>
                <?php endforeach; ?>
            </tbody>
        </table>

</div>
       </div> <!-- /row -->	
 
    
    
    
    
</div>

















       
