<?php View::notify(); ?>
<style type="text/css">
    .tab-pane { min-height: 200px;}
</style>
<div class="container-fluid dw-shell-view">
    <?php View::process($page_module, $page_title, $set_title); ?>
    <?php echo DwForm::open('', 'post', array('id'=>'form', 'class'=>'dw-validate')); ?>
     <?php if(DESKTOP) { ?>
        <ul class="nav nav-tabs">
        <?php } else { ?>
        <ul class="nav nav-pills nav-stacked">
        <?php } ?>
            <li class="active"><a href="#tab1" data-toggle="tab">Información de la Cuenta</a></li>
        </ul>
        <div class="tab-content">
            <div class="tab-pane active" id="tab1">
                <div class="row-fluid">
                    <div class="span12">
                        <?php echo DwForm::text('usuario.login', array('class'=>'input-xxlarge input-required mask-alphanum show-error input-user'), NULL, 'Usuario login'); ?>
                    </div>
                </div>               
                <div class="row-fluid">
                    <div class="form-actions">
                        <?php echo DwButton::save('Resetar Clave'); ?>
                        <?php echo DwButton::reset('form'); ?>
                        <?php echo DwButton::cancel('sistema/usuario/listar/'); ?>
                    </div>
                </div>
            </div>

        </div>
    <?php echo DwForm::close(); ?>
</div>
