<?php View::notify(); ?>
<div class="container-fluid dw-shell-view">
    <?php View::process($page_module, $page_title, $set_title); ?>
    <?php echo DwForm::open('', 'post', array('id'=>'form', 'class'=>'dw-validate')); ?>
        <div class="row-fluid">
            <div class="span3">
                <?php echo DwForm::text('solicitud_servicio.codigo_solicitud_id', array('class'=>'input-xlarge disabled'), $solicitud_servicio->codigo_solicitud, 'Código:'); ?>
                <?php echo DwForm::hidden('solicitud_servicio.codigo_solicitud', NULL, $solicitud_servicio->codigo_solicitud); ?>
                <?php echo DwForm::hidden('solicitud_servicio.tiposolicitud_id', NULL, '1'); ?>
                <?php echo DwForm::hidden('solicitud_servicio.estado_solicitud', NULL, 'R'); ?>
                <?php ?>
            </div>
            <div class="span3">
                <?php echo DwForm::date('solicitud_servicio.fecha_solicitud', array('class'=>'input-required mask-date readonly input-date show-errors'), $solicitud_servicio->fecha_solicitud, 'Fecha Solicitud'); ?>
            </div>
            <div class="span3">
                <?php echo DwForm::date('solicitud_servicio.fecha_vencimiento', array('class'=>'input-required mask-date input-date show-errors'), $solicitud_servicio->fecha_vencimiento, 'Fecha Vencimiento'); ?>
            </div>
        </div>
        <div class="row-fluid">
            <div class="span3">
                <?php echo DwForm::text('solicitud_servicio.titular', array('class'=>'input-large mask-pint show-error input-required '), $solicitud_servicio->cedula, 'Cedula Titular'); ?>
                <?php echo DwForm::hidden('solicitud_servicio.titular_id', $solicitud_servicio->idtitular); ?>
            </div>
            <div class="span3">
                <?php echo DwForm::text('solicitud_servicio.titular_idnombre', array('class'=>'input-large disabled '), $solicitud_servicio->nombre." ".$solicitud_servicio->apellido, 'Nombre Titular:'); ?>
            </div>
            <div class="span3">
          
            <?php echo DwForm::text('solicitud_servicio.beneficiario_nombre', array('class'=>'input-large disabled '), $solicitud_servicio->nombreb." ".$solicitud_servicio->apellidob, 'Beneficiario:'); ?>
            <?php echo DwForm::hidden('solicitud_servicio.beneficiario_id', $solicitud_servicio->idbeneficiario); ?>
             
            </div>
            <div class="span3">
                <?php echo DwForm::text('solicitud_servicio.servicio', array('class'=>'input-large input-required mask-alpha '), NULL, 'Servicio'); ?>
                <?php echo DwForm::hidden('solicitud_servicio.servicio_id', NULL, $solicitud_servicio->idservicio ); ?>
            </div>
        </div>
        <div class="row-fluid">
            <div class="span3">
                <?php echo DwForm::text('solicitud_servicio.proveedor', array('class'=>'input-large input-required mask-alpha '), NULL, 'Proveedor'); ?>
                <?php echo DwForm::hidden('solicitud_servicio.proveedor_id', NULL, $solicitud_servicio->idproveedor); ?>
            </div>
            <div class="span3">
               <?php echo DwForm::text('solicitud_servicio.medico', array('class'=>'input-large input-required mask-alpha'), $solicitud_servicio->nombrem." ".$solicitud_servicio->apellidom, 'Medico'); ?>
               <?php echo DwForm::hidden('solicitud_servicio.medico_id', $solicitud_servicio->idmedico); ?>
            </div>
            <div class="span6">
                <?php echo DwForm::textarea('solicitud_servicio.observacion', array('class'=>'mask-text show-error input-xxlarge mask-alpha '), NULL, 'Observacion'); ?>
            </div>
            <?php echo DwForm::hiddenKey('solicitud_servicio.id', $solicitud_servicio->id); ?>
        </div>
        <div class="row-fluid">
            <div class="form-actions">
                <?php echo DwButton::save('Guardar Solicitud'); ?>
                <?php echo DwButton::reset('form'); ?>
                <?php echo DwButton::cancel(); ?>
            </div>
        </div>
    <?php echo DwForm::close(); ?>
</div>
<script type="text/javascript" >
$(document).ready(function(){
  select: function ll(event, ui) {
                  $('input#solicitud_servicio_codigo_solicitud').val(ui.item.codid);// Asignacion de Id en Campo
                 // $('textarea#solicitud_servicio_observacion').val(ui.item.id);// Asignacion de Id en Campo
              }
    $('input#solicitud_servicio_titular').autocomplete({
            minLength : 3 , //le indicamos que busque a partir de haber escrito dos o mas caracteres en el input
            source: function(request, response) {
                $.ajax({
                  url: "<?php echo PUBLIC_PATH ?>beneficiarios/titular/autocomplete",
                  data: {'busqueda':request.term},
                  dataType: "json",
                  type: "POST",
                  success: function(data){
                      response(data);
                  }
                });
              },
              select: function(event, ui) {
                  $('input#solicitud_servicio_titular_id').val(ui.item.id);// Asignacion de Id en Campo
                  $('input#solicitud_servicio_titular_idnombre').val(ui.item.idnombre);// Asignacion de Id en Campo
                 // $('textarea#solicitud_servicio_observacion').val(ui.item.id);// Asignacion de Id en Campo
                 
              }
    });
    $('input#solicitud_servicio_beneficiario').autocomplete({
            minLength : 1 , //le indicamos que busque a partir de haber escrito dos o mas caracteres en el input
            source: function(request, response) {
                $.ajax({
                  url: "<?php echo PUBLIC_PATH ?>beneficiarios/beneficiario/autocomplete",
                  data: {'busqueda':request.term},
                  dataType: "json",
                  type: "POST",
                  success: function(data){
                      response(data);
                  }
                });
              },
              select: function(event, ui) {
                  $('input#solicitud_servicio_beneficiario_id').val(ui.item.id);// Asignacion de Id en Campo
                  $('input#solicitud_servicio_beneficiario_idnombre').val(ui.item.idnombre);// Asignacion de Id en Campo
              }
    });
 
    $( "input#solicitud_servicio_proveedor" ).autocomplete({
            minLength : 1 , //le indicamos que busque a partir de haber escrito dos o mas caracteres en el input
            source: function(request, response) {
                $.ajax({
                  url: "<?php echo PUBLIC_PATH ?>proveedorsalud/proveedor/autocomplete",
                  data: {'busqueda':request.term},
                  dataType: "json",
                  type: "POST",
                  success: function(data){
                      response(data);
                  }
                });
              },
              select: function(event, ui) {
                  $('input#solicitud_servicio_proveedor_id').val(ui.item.id);// Asignacion de Id en Campo
              }
    });
    $('input#solicitud_servicio_medico').autocomplete({
            minLength : 1 , //le indicamos que busque a partir de haber escrito dos o mas caracteres en el input
            source: function(request, response) {
                $.ajax({
                  url: "<?php echo PUBLIC_PATH ?>proveedorsalud/medico/autocomplete",
                  data: {'busqueda':request.term},
                  dataType: "json",
                  type: "POST",
                  success: function(data){
                      response(data);
                  }
                });
              },
              select: function(event, ui) {
                  $('input#solicitud_servicio_medico_id').val(ui.item.id);// Asignacion de Id en Campo
              }
    });
    $('input#solicitud_servicio_servicio').autocomplete({
            minLength : 1 , //le indicamos que busque a partir de haber escrito dos o mas caracteres en el input
            source: function(request, response) {
                $.ajax({
                  url: "<?php echo PUBLIC_PATH ?>proveedorsalud/servicio/autocomplete",
                  data: {'busqueda':request.term},
                  dataType: "json",
                  type: "POST",
                  success: function(data){
                      response(data);
                  }
                });
              },
              select: function(event, ui) {
                  $('input#solicitud_servicio_servicio_id').val(ui.item.id);// Asignacion de Id en Campo
                   //$('textarea#solicitud_servicio_observacion').val(ui.item.id);// Asignacion de Id en Campo
              }
    }); 
    $('input#solicitud_servicio_patologia').autocomplete({
            minLength : 3 , //le indicamos que busque a partir de haber escrito dos o mas caracteres en el input
            source: function(request, response) {
                $.ajax({
                  url: "<?php echo PUBLIC_PATH ?>config/patologia/autocomplete",
                  data: {'busqueda':request.term},
                  dataType: "json",
                  type: "POST",
                  success: function(data){
                      response(data);
                  }
                });
              },
              select: function(event, ui) {
                  $('input#solicitud_servicio_patologia_id').val(ui.item.id);// Asignacion de Id en Campo
                   //$('textarea#solicitud_servicio_observacion').val(ui.item.id);// Asignacion de Id en Campo
              }
    }); 
$("#solicitud_servicio_titular").change(function(){
    var titular_id     =   $('#solicitud_servicio_titular_id').val();
        $.ajax({
          type: "POST",
          url: "<?php echo PUBLIC_PATH . 'beneficiarios/beneficiario/getBeneficiarios/'; ?>",
          data: "titular_id=" + titular_id,
          success: function(html){
            $("#div_beneficiario").html(html);
          }
        });
});
});
</script>
