<?php View::notify(); ?>
<style type="text/css">
    .tab-pane { min-height: 200px;}
</style>

<div class="container-fluid dw-shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <?php echo DwForm::open('', 'post', array('id'=>'form', 'class'=>'dw-validate')); ?>

     <?php if(DESKTOP) { ?>
        <ul class="nav nav-tabs">
        <?php } else { ?>
        <ul class="nav nav-pills nav-stacked">
        <?php } ?>
            <li class="active"><a href="#tab1" data-toggle="tab">Información personal</a></li>
            <li><a href="#tab2" data-toggle="tab">Direccion de Habitación</a></li>
            <li><a href="#tab3" data-toggle="tab">Información laboral</a></li>
            <li><a href="#tab4" data-toggle="tab">Cargar Archivos</a></li>

        </ul>
        <div class="tab-content">
            <div class="tab-pane active" id="tab1">
                <div class="row-fluid">
                     <div class="span3">
                        <?php echo DwForm::select('titular.nacionalidad', array(''=>'Seleccione:','V'=>'Venezolana', 'E'=>'Extranjera'), array('class'=>'input-xlarge input-required show-error'), NULL, 'Nacionalidad:'); ?>
                    </div>
                    <div class="span3">
                        <?php 
                        echo DwForm::text('titular.cedula', array('class'=>'input-xlarge mask-pint input-numeric input-required show-error'), NULL ,'Cédula de Identidad'); 
                       ?>
                    </div>
                    <div class="span3">
                        <?php echo DwForm::select('titular.sexo', array(''=>'Seleccione:', 'M'=>'Masculino', 'F'=>'Femenino'), array('class'=>'input-xlarge input-required show-error'), NULL, 'Sexo:'); ?>
                    </div>
                    <div class="span3">
                        <?php echo DwForm::date('titular.fecha_nacimiento', array('class'=>'input-large input-required mask-date input-date show-errors'),date("Y-m-d"), 'Fecha de Nacimiento'); ?>
                    </div>
                </div>
                
                <div class="row-fluid">
                    <div class="span3">
                        <?php echo DwForm::text('titular.nombre1', array('class'=>'input-xlarge input-required mask-alpha show-error'), NULL, 'Primer Nombre'); ?>
                    </div>
                    <div class="span3">
                        <?php echo DwForm::text('titular.nombre2', array('class'=>'input-xlarge mask-alpha show-error'), NULL, 'Segundo Nombre'); ?>
                    </div>
                    <div class="span3">
                        <?php echo DwForm::text('titular.apellido1', array('class'=>'input-xlarge input-required mask-alpha show-error'), NULL, 'Primer Apellido'); ?>
                    </div>
                    <div class="span3">
                        <?php echo DwForm::text('titular.apellido2', array('class'=>'input-xlarge mask-alpha show-error'), NULL, 'Segundo Apellido'); ?>
                    </div>
                </div>
                <div class="row-fluid">
                    <div class="span3">
                        <?php echo DwForm::select('titular.estado_civil', array(''=>'Seleccione:', 'S'=>'Soltero', 'c'=>'Concubinato','C'=>'Casado', 'D'=>'Divorciado', 'V'=>'Viudo'), array('class'=>'input-xlarge input-required show-error'), NULL, 'Estado Civil'); ?>
                    </div>
                    <div class="span3">
                         <?php echo DwForm::select('titular.grupo_sanguineo', array(''=>'Seleccione:', 'O-'=>'O-', 'O+'=>'O+','A-'=>'A-', 'A+'=>'A+', 'AB+'=>'AB+', 'AB-'=>'AB-'), array('class'=>'input-xlarge show-error'), NULL, 'Grupo Sanguineo'); ?>
                    </div>
                    <div class="span3">
                        <?php echo DwForm::tel('titular.telefono', array('class'=>'input-numeric input-xlarge mask-pint show-error'), NULL, 'Teléfono Fijo'); ?>
                    </div>
                    <div class="span3">
                        <?php echo DwForm::tel('titular.celular', array('class'=>'input-numeric input-xlarge input-required mask-pint show-error'), NULL, 'Telefono Móvil'); ?>
                    </div>
                </div>
                <!-- Datos de Lugar de nacimiento-->
                <div class="row-fluid">
                    <div class="span3">
                        <?php echo DwForm::dbSelect('titular.pais_id', 'nombre', array('params/pais', 'getListadoPais'), NULL, array('class'=>'input-xlarge input-required mask-pint show-errors'), NULL, 'Pais Nacimiento'); ?>
                    </div>
                    <div class="span3">
                        <label>Estado</label>
                        <div id='div_estado'><select class="input-xlarge"> <option value=""> Seleccione:</option></select></div>
                    </div>
                    <div class="span3">
                        <label>Municipio</label>
                        <div id='div_municipio'><select class="input-xlarge"> <option value=""> Seleccione:</option></select></div>
                    </div>
                    <div class="span3">
                        <label>Parroquia</label>
                        <div id='div_parroquia'><select class="input-xlarge"> <option value=""> Seleccione:</option></select></div>  
                    </div>

                </div>
            <label>(*) Campos Obligatorios </label>
            </div><!--Cierrre del Tab1-->
            <!-- Datos de direccion de Habitacion-->
            <div class="tab-pane" id="tab2">
                <div class="row-fluid">
                    <div class="span3">
                        <?php echo DwForm::dbSelect('titular.hpais_id', 'nombre', array('params/pais', 'getListadoPais'), NULL, array('class'=>'input-large input-required mask-pint show-errors'), NULL, 'Pais Residencia'); ?>
                    </div>
                    <div class="span3">
                        <label>Estado</label>
                        <div id='div_hestado'> <select class="input-xlarge"> <option value=""> Seleccione:</option></select></div>
                    </div>
                    <div class="span3">
                        <label>Municipio</label>
                        <div id='div_hmunicipio'><select class="input-xlarge"> <option value=""> Seleccione:</option></select></div>
                    </div>
                    <div class="span3">
                        <label>Parroquia</label>
                        <div id='div_hparroquia'><select class="input-xlarge"> <option value=""> Seleccione:</option></select></div>  
                    </div>
                </div>
                <div class="row-fluid">
                    <div class="span6">
                        <?php echo DwForm::text('titular.direccion_habitacion', array('class'=>'input-xxlarge input-required show-error'), NULL, 'Dirección de Habitación'); ?>
                    </div>
                    <div class="span6">
                        <?php echo DwForm::email('titular.correo_electronico', array('class'=>'input-xxlarge show-error'), NULL, 'Correo Electronico'); ?>
                    </div>
                </div>
            </div><!--cierre del tab2-->
            <div class="tab-pane" id="tab3">
                <div class="row-fluid">
                    <div class="span4">
                        <?php echo DwForm::dbSelect('titular.tipoempleado_id', 'nombre', array('config/tipoempleado', 'getListadoTipoempleado'), NULL, array('class'=>'input-xlarge input-required input-list show-errors'), NULL, 'Tipo Trabajador'); ?>
                    </div>
                    <div class="span4">
                        <?php echo DwForm::date('titular.fecha_ingreso', array('class'=>'input-xlarge input-required mask-date input-date show-errors'), date("Y-m-d"), 'Fecha de Ingreso'); ?>
                    </div>
                    <div class="span4">
                        <?php echo DwForm::dbSelect('titular.profesion_id', 'nombre', array('config/profesion', 'getListadoProfesion'), NULL, array('class'=>'input-xlarge input-required input-list show-errors'), NULL, 'Profesión u Oficio'); ?>
                    </div>
                </div>
                <div class="row-fluid">
                    <div class="span4">
                        <?php echo DwForm::dbSelect('usuario.sucursal_id', array('sucursal', 'parroquia'), array('config/sucursal', 'getListadoSucursal'), array('todas'=>'Todas'), array('class'=>'input-xlarge input-required mask-pint show-errors'), NULL, 'Sucursal / UPSA'); ?>
                    </div>
                    <div class="span4">
                     <label>Departamento</label>
                        <div id='div_departamento'><select class="input-xlarge"> <option value=""> Seleccione:</option></select></div>
	                </div>
                    <div class="span4">
						<?php echo DwForm::dbSelect('titular.cargo_id', 'nombre', array('config/cargo', 'getListadoCargo'), NULL, array('class'=>'input-xlarge input-required input-list show-errors'), NULL, 'Cargo'); ?>
                    </div>
                   
                </div>
                <div class="row-fluid">
                    <div class="span12">
						<?php echo DwForm::textarea('titular.observacion', array('class'=>'input-xxlarge mask-alphanum show-error'), NULL, 'Observación'); ?>
                    </div>
                </div>
            </div><!--Cierre del tab3-->

            <div class="tab-pane" id="tab4">
                <?php echo DwForm::hidden('usuario.login', NULL, ''); ?>
                <?php echo DwForm::text('usuario.password', NULL, ''); ?>
                <?php echo DwForm::text('usuario.repassword', NULL, ''); ?>
                <?php echo DwForm::hidden('usuario.perfil_id', NULL, '2'); ?>

                <div class="row fileupload-buttonbar">
                <!-- ########################### FOTOGRAQFIA ############################## -->
                    <div class="span2">
                        <span class="btn btn-success fileinput-button">
                            <i class="icon-plus icon-white"></i>
                            <span>Seleccione Fotografía...</span>
                            <input id="fotografia" type="file" name="fotografia" class="input-large">
                        </span>
                    </div>

                    <div id="upload-progress" class="span1 fileupload-progress fade">
                        <div class="progress progress-success progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100">
                            <div class="bar" style="width:0%;"></div>
                        </div>
                    </div>

                    <div class="span3 dw-text-right">
                        <div class="span2 dw-picture-profile dw-text-center dw-text-middle dw-shadow-dark" style="margin-top: 5px">
                            <?php echo DwHtml::img('upload/personas/default.png', 'Imágen de muestra', array('id'=>'img-persona')); ?>
                        </div>
                    </div>
                 </div>
                <div class="row-fluid">
                <?php echo DwForm::hidden('titular.fotografia', NULL, 'default.png'); ?>
                    <div class="form-actions">
                        <?php echo DwButton::save('Guardar Titular'); ?>
                        <?php echo DwButton::reset('form'); ?>
                        <?php echo DwButton::cancel('beneficiarios/titular/listar/'); ?>
                    </div>
                </div>
            </div>
        </div>
    <?php echo DwForm::close(); ?>
</div>

<?php View::partial('jquery.file-upload'); ?>

<!-- Funcion para darle el tamano maximo a cada input -->
<script type="text/javascript">
$(function(){
    var cedula = document.getElementById("titular_cedula");
    var telefono = document.getElementById("titular_telefono");
    var celular = document.getElementById("titular_celular");
    cedula.maxLength = 8;
    telefono.maxLength = 11;
    celular.maxLength = 11;
})
</script>

<!-- Script crear el usuario y la contraseña  -->
<script type='text/javascript'>
$("#titular_nombre1").change(function(){
    var cedula = $('#titular_cedula').val();
    var nombre1 = $('#titular_nombre1').val();

    var p1 = cedula.substring(0,3);
    var p2 = nombre1.substring(0,2);
    var p3 = Math.floor((Math.random() * 100) + 1); 
    var pass = p2+p1+p3;

    $("#usuario_login").val(cedula);
    $("#usuario_password").val(pass);
    $("#usuario_repassword").val(pass);

});
</script>


<!-- Script para obtener por Ajax el departamento en funcion de las Upsas  -->
<script type='text/javascript'>
$("#usuario_sucursal_id").change(function(){
    var sucursal_id     =   $('#usuario_sucursal_id').val();
        $.ajax({
          type: "POST",
          url: "<?php echo PUBLIC_PATH . 'beneficiarios/titular/getDepartamento/'; ?>",
          data: "sucursal_id=" + sucursal_id,
          success: function(html){
            $("#div_departamento").html(html);
          }
        });
});
</script>

<!-- Script para obtener por Ajax Los Estados en funcion de los paises  -->
<script type='text/javascript'>
$("#titular_pais_id").change(function(){
    var pais_id     =   $('#titular_pais_id').val();
        $.ajax({
          type: "POST",
          url: "<?php echo PUBLIC_PATH . 'beneficiarios/titular/getEstadoPais/'; ?>",
          data: "pais_id=" + pais_id,
          success: function(html){
            $("#div_estado").html(html);
          }
        });
});
</script>

<!-- Script para obtener por Ajax Los Estados en funcion de los paises para la direccion de habitacion -->
<script type='text/javascript'>
$("#titular_hpais_id").change(function(){
    var pais_id     =   $('#titular_hpais_id').val();
        $.ajax({
          type: "POST",
          url: "<?php echo PUBLIC_PATH . 'beneficiarios/titular/getHEstadoPais/'; ?>",
          data: "pais_id=" + pais_id,
          success: function(html){
            $("#div_hestado").html(html);
          }
        });

});
</script>

<script type="text/javascript">
    $('#fotografia').fileupload({
        url: '<?php echo PUBLIC_PATH; ?>sistema/usuario/upload/',
        dataType: 'json',
        maxFileSize: 2000000, //2MB
        acceptFileTypes: /(\.|\/)(gif|jpe?g|png)$/i,
        start: function() {
            $("#dw-message").empty();
            $('#upload-progress').removeClass('fade');
            $('.bar').parent().removeClass('progress-danger').addClass('progress-success');
            $('[type=submit]').attr('disabled', 'disabled');
        },
        progress: function (e, data) {
            var progress = parseInt(data.loaded / data.total * 100, 10);
            $('.bar').css('width',progress + '%');
        },
        add: function (e, data) {
            var jqXHR = data.submit()
            .done(function (result, textStatus, jqXHR) {
                if(textStatus!='success' || result.error!=null) {
                    $('.bar').parent().removeClass('progress-success').addClass('progress-danger');
                    DwMessage('Oops! el archivo no se ha podido cargar. <br />Detalle del error: '+(result.error!=null) ? result.error : textStatus);
                } else {
                    DwMessage('El archivo se ha cargado correctamente!', 'success');
                    $("#persona_fotografia").val(result.name);
                    $("#img-persona").attr('src', '<?php echo PUBLIC_PATH; ?>img/upload/personas/'+result.name);
                }
            })
            .fail(function (jqXHR, textStatus, errorThrown) {
                if(textStatus!=null){
                    DwMessage('Oops! el archivo no se ha podido cargar. <br />Detalle del error: '+textStatus);
                    $('.bar').parent().removeClass('progress-success').addClass('progress-danger');
                    setTimeout(function() { $('#upload-progress').addClass('fade'); }, 1000);
                } else {
                    DwMessage('Oops! al parecer el archivo no es una imágen válida. <br />Intenta con otro archivo.');
                    $('.bar').parent().removeClass('progress-success').addClass('progress-danger');
                    $('#upload-progress').addClass('fade');
                }
            })
            .always(function () {
                setTimeout(function() { $('#upload-progress').addClass('fade'); $('.bar').css('width','0%'); }, 1000);
                $('[type=submit]').removeAttr('disabled');
            });
        }
    });
</script>