<?php View::notify(); ?>
<style type="text/css">
    .tab-pane { min-height: 200px;}
</style>

<div class="container-fluid dw-shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <?php echo DwForm::open('', 'post', array('id'=>'form', 'class'=>'dw-validate')); ?>

     <?php if(DESKTOP) { ?>
        <ul class="nav nav-tabs">
        <?php } else { ?>
        <ul class="nav nav-pills nav-stacked">
        <?php } ?>
            <li class="active"><a href="#tab1" data-toggle="tab">Información personal</a></li>
            <li><a href="#tab2" data-toggle="tab">Direccion de Habitación</a></li>
            <li><a href="#tab3" data-toggle="tab">Información laboral</a></li>
            <li><a href="#tab4" data-toggle="tab">Cargar Archivos</a></li>

        </ul>
        <div class="tab-content">
            <div class="tab-pane active" id="tab1">
                <div class="row-fluid">
                     <div class="span3">
                        <?php echo DwForm::select('persona.nacionalidad', array(''=>'Seleccione:','V'=>'Venezolana', 'E'=>'Extranjera'), array('class'=>'input-xlarge input-required show-error'), NULL, 'Nacionalidad:'); ?>
                    </div>
                    <div class="span3">
                        <?php 
                        echo DwForm::text('persona.cedula', array('class'=>'input-xlarge mask-pint input-numeric input-required show-error'), NULL ,'Cédula de Identidad'); 
                       ?>
                    </div>
                    <div class="span3">
                        <?php echo DwForm::select('persona.sexo', array(''=>'Seleccione:', 'M'=>'Masculino', 'F'=>'Femenino'), array('class'=>'input-xlarge input-required show-error'), NULL, 'Sexo:'); ?>
                    </div>
                    <div class="span3">
                        <?php echo DwForm::date('persona.fecha_nacimiento', array('class'=>'input-large input-required mask-date input-date show-errors'), date("d-m-Y"), 'Fecha de Nacimiento'); ?>
                    </div>
                </div>
                
                <div class="row-fluid">
                    <div class="span3">
                        <?php echo DwForm::text('persona.nombre1', array('class'=>'input-xlarge input-required  show-error'), NULL, 'Primer Nombre'); ?>
                    </div>
                    <div class="span3">
                        <?php echo DwForm::text('persona.nombre2', array('class'=>'input-xlarge show-error'), NULL, 'Segundo Nombre'); ?>
                    </div>
                    <div class="span3">
                        <?php echo DwForm::text('persona.apellido1', array('class'=>'input-xlarge input-required show-error'), NULL, 'Primer Apellido'); ?>
                    </div>
                    <div class="span3">
                        <?php echo DwForm::text('persona.apellido2', array('class'=>'input-xlarge show-error'), NULL, 'Segundo Apellido'); ?>
                    </div>
                </div>
                <div class="row-fluid">
                    <div class="span3">
                        <?php echo DwForm::select('persona.estado_civil', array(''=>'Seleccione:', 'S'=>'Soltero', 'c'=>'Concubinato','C'=>'Casado', 'D'=>'Divorciado', 'V'=>'Viudo'), array('class'=>'input-xlarge input-required show-error'), NULL, 'Estado Civil'); ?>
                    </div>
                    <div class="span3">
                        <?php echo DwForm::text('persona.grupo_sanguineo', array('class'=>'input-xlarge  mask-alphanum show-error'), NULL, 'Grupo Sanguineo'); ?>
                    </div>
                    <div class="span3">
                        <?php echo DwForm::tel('persona.telefono', array('class'=>'input-numeric input-xlarge mask-pint show-error'), NULL, 'Teléfono'); ?>
                    </div>
                    <div class="span3">
                        <?php echo DwForm::tel('persona.celular', array('class'=>'input-numeric input-xlarge mask-pint show-error'), NULL, 'Celular'); ?>
                    </div>
                </div>
                <!-- Datos de Lugar de nacimiento-->
                <div class="row-fluid">
                    <div class="span3">
                        <?php echo DwForm::dbSelect('persona.pais_id', 'nombre', array('params/pais', 'getListadoPais'), NULL, array('class'=>'input-xlarge input-required mask-pint show-errors'), NULL, 'Pais Nacimiento'); ?>
                    </div>
                    <div class="span3">
                        <label>Estado</label>
                        <div id='div_estado'></div>
                    </div>
                    <div class="span3">
                        <label>Municipio</label>
                        <div id='div_municipio'></div>
                    </div>
                    <div class="span3">
                        <label>Parroquia</label>
                        <div id='div_parroquia'></div>  
                    </div>
                </div>
            </div><!--Cierrre del Tab1-->
            <!-- Datos de direccion de Habitacion-->
            <div class="tab-pane" id="tab2">
                <div class="row-fluid">
                    <div class="span3">
                        <?php echo DwForm::dbSelect('persona.hpais_id', 'nombre', array('params/pais', 'getListadoPais'), NULL, array('class'=>'input-large input-required mask-pint show-errors'), NULL, 'Pais Residencia'); ?>
                    </div>
                    <div class="span3">
                        <label>Estado</label>
                        <div id='div_hestado'></div>
                    </div>
                    <div class="span3">
                        <label>Municipio</label>
                        <div id='div_hmunicipio'></div>
                    </div>
                    <div class="span3">
                        <label>Parroquia</label>
                        <div id='div_hparroquia'></div>  
                    </div>
                </div>
                <div class="row-fluid">
                    <div class="span6">
                        <?php echo DwForm::text('persona.direccion_habitacion', array('class'=>'input-xxlarge input-required show-error'), NULL, 'Dirección de Habitación'); ?>
                    </div>
                    <div class="span6">
                        <?php echo DwForm::email('persona.correo_electronico', array('class'=>'input-xxlarge show-error'), NULL, 'Correo Electronico'); ?>
                    </div>
                </div>
            </div><!--cierre del tab2-->
            <div class="tab-pane" id="tab3">
                <div class="row-fluid">
                    <div class="span4">
                        <?php echo DwForm::dbSelect('titular.tipoempleado_id', 'nombre', array('config/tipoempleado', 'getListadoTipoempleado'), NULL, array('class'=>'input-xlarge input-required input-list show-errors'), NULL, 'Tipo Trabajador'); ?>
                    </div>
                    <div class="span4">
                        <?php echo DwForm::date('titular.fecha_ingreso', array('class'=>'input-xlarge input-required mask-date input-date show-errors'), date("d-m-Y"), 'Fecha de Ingreso'); ?>
                    </div>
                    <div class="span4">
                        <?php echo DwForm::dbSelect('titular.profesion_id', 'nombre', array('config/profesion', 'getListadoProfesion'), NULL, array('class'=>'input-xlarge input-required input-list show-errors'), NULL, 'Profesión u Oficio'); ?>
                    </div>
                </div>
                <div class="row-fluid">
                    <div class="span4">
                        <?php echo DwForm::dbSelect('usuario.sucursal_id', array('sucursal', 'parroquia'), array('config/sucursal', 'getListadoSucursal'), array('todas'=>'Todas'), array('class'=>'input-xlarge input-required mask-pint show-errors'), NULL, 'Sucursal / UPSA'); ?>
                    </div>
                    <div class="span4">
                     <label>Departamento</label>
                        <div id='div_departamento'></div>
	                </div>
                    <div class="span4">
						<?php echo DwForm::dbSelect('titular.cargo_id', 'nombre', array('config/cargo', 'getListadoCargo'), NULL, array('class'=>'input-xlarge input-required input-list show-errors'), NULL, 'Cargo'); ?>
                    </div>
                   
                </div>
                <div class="row-fluid">
                    <div class="span12">
						<?php echo DwForm::textarea('titular.observacion', array('class'=>'input-xxlarge input-required mask-alphanum show-error'), NULL, 'Observación'); ?>
                    </div>
                </div>
            </div><!--Cierre del tab3-->

            <div class="tab-pane" id="tab4">

                <div class="row fileupload-buttonbar">
                <!-- ########################### FOTOGRAQFIA ############################## -->
                    <div class="span2">
                        <span class="btn btn-success fileinput-button">
                            <i class="icon-plus icon-white"></i>
                            <span>Seleccione Fotografía...</span>
                            <input id="fotografia" type="file" name="fotografia" class="input-large">
                        </span>
                    </div>

                    <div id="upload-progress" class="span1 fileupload-progress fade">
                        <div class="progress progress-success progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100">
                            <div class="bar" style="width:0%;"></div>
                        </div>
                    </div>

                    <div class="span3 dw-text-right">
                        <div class="span2 dw-picture-profile dw-text-center dw-text-middle dw-shadow-dark" style="margin-top: 5px">
                            <?php echo DwHtml::img('upload/personas/default.png', 'Imágen de muestra', array('id'=>'img-persona')); ?>
                        </div>
                    </div>


                   <!-- ########################### Cedula ############################## -->
                    <div class="span2">
                        <span class="btn btn-success fileinput-button">
                            <i class="icon-plus icon-white"></i>
                            <span>Seleccione Cédula...</span>
                            <input id="imgcedula" type="file" name="imgcedula" class="input-large">
                        </span>
                    </div>

                    <div id="upload-progress1" class="span1 fileupload-progress fade">
                        <div class="progress progress-success progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100">
                            <div class="bar" style="width:0%;"></div>
                        </div>
                    </div>

                    <div class="span3 dw-text-right">
                        <div class="span2 dw-picture-profile dw-text-center dw-text-middle dw-shadow-dark" style="margin-top: 5px">
                            <?php echo DwHtml::img('upload/personas/default.png', 'Imágen de muestra', array('id'=>'imgcedula-persona')); ?>
                        </div>
                    </div>

                </div>


                <div class="row fileupload-buttonbar">
                <!-- ########################### Carnet ############################## -->
                    <div class="span2">
                        <span class="btn btn-success fileinput-button">
                            <i class="icon-plus icon-white"></i>
                            <span>Seleccione Carnet...</span>
                            <input id="carnet" type="file" name="carnet" class="input-large">
                        </span>
                    </div>

                    <div id="upload-progress2" class="span1 fileupload-progress fade">
                        <div class="progress progress-success progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100">
                            <div class="bar" style="width:0%;"></div>
                        </div>
                    </div>

                    <div class="span3 dw-text-right">
                        <div class="span2 dw-picture-profile dw-text-center dw-text-middle dw-shadow-dark" style="margin-top: 5px">
                            <?php echo DwHtml::img('upload/personas/default.png', 'Imágen de muestra', array('id'=>'img-persona')); ?>
                        </div>
                    </div>
                <!-- ########################### Acta de matrimonio ############################## -->
                    <div class="span2">
                        <span class="btn btn-success fileinput-button">
                            <i class="icon-plus icon-white"></i>
                            <span>Acta de Matrimonio...</span>
                            <input id="actamatrimonio" type="file" name="actamatrimonio" class="input-large">
                        </span>
                    </div>

                    <div id="upload-progress3" class="span1 fileupload-progress fade">
                        <div class="progress progress-success progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100">
                            <div class="bar" style="width:0%;"></div>
                        </div>
                    </div>

                    <div class="span3 dw-text-right">
                        <div class="span2 dw-picture-profile dw-text-center dw-text-middle dw-shadow-dark" style="margin-top: 5px">
                            <?php echo DwHtml::img('upload/personas/default.png', 'Imágen de muestra', array('id'=>'img-persona')); ?>
                        </div>
                    </div>
                </div>

                <!-- ########################### Partida de Nacimiento ############################## -->
                <div class="row fileupload-buttonbar">

                    <div class="span2">
                        <span class="btn btn-success fileinput-button">
                            <i class="icon-plus icon-white"></i>
                            <span>Partida de Nacimiento...</span>
                            <input id="partidanacimiento" type="file" name="partidanacimiento" class="input-large">
                        </span>
                    </div>

                    <div id="upload-progress4" class="span1 fileupload-progress fade">
                        <div class="progress progress-success progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100">
                            <div class="bar" style="width:0%;"></div>
                        </div>
                    </div>

                    <div class="span3 dw-text-right">
                        <div class="span2 dw-picture-profile dw-text-center dw-text-middle dw-shadow-dark" style="margin-top: 5px">
                            <?php echo DwHtml::img('upload/personas/default.png', 'Imágen de muestra', array('id'=>'img-persona')); ?>
                        </div>
                    </div>
                </div>

                <div class="row-fluid">
                <?php echo DwForm::hidden('persona.fotografia', NULL, 'default.png'); ?>
                    <div class="form-actions">
                        <?php echo DwButton::save('Guardar Titular'); ?>
                        <?php echo DwButton::reset('form'); ?>
                        <?php echo DwButton::cancel('beneficiarios/titular/listar/'); ?>
                    </div>

                </div>
            </div>

        </div>

    <?php echo DwForm::close(); ?>
</div>

<?php View::partial('jquery.file-upload'); ?>

<!-- Script para obtener por Ajax el departamento en funcion de las Upsas  -->
<script type='text/javascript'>

$("#usuario_sucursal_id").change(function(){
    var sucursal_id     =   $('#usuario_sucursal_id').val();
        $.ajax({
          type: "POST",
          url: "<?php echo PUBLIC_PATH . 'beneficiarios/titular/getDepartamento/'; ?>",
          data: "sucursal_id=" + sucursal_id,
          success: function(html){
            $("#div_departamento").html(html);
          }
        });
});
</script>

<!-- Script para obtener por Ajax Los Estados en funcion de los paises  -->
<script type='text/javascript'>
$("#persona_pais_id").change(function(){
    var pais_id     =   $('#persona_pais_id').val();
        $.ajax({
          type: "POST",
          url: "<?php echo PUBLIC_PATH . 'beneficiarios/titular/getEstadoPais/'; ?>",
          data: "pais_id=" + pais_id,
          success: function(html){
            $("#div_estado").html(html);
          }
        });
});
</script>

<!-- Script para obtener por Ajax Los Estados en funcion de los paises para la direccion de habitacion -->
<script type='text/javascript'>
$("#persona_hpais_id").change(function(){
    var pais_id     =   $('#persona_hpais_id').val();
        $.ajax({
          type: "POST",
          url: "<?php echo PUBLIC_PATH . 'beneficiarios/titular/getHEstadoPais/'; ?>",
          data: "pais_id=" + pais_id,
          success: function(html){
            $("#div_hestado").html(html);
          }
        });
});
</script>



<script type="text/javascript">
    $('#fotografia').fileupload({
        url: '<?php echo PUBLIC_PATH; ?>sistema/usuario/upload/',
        dataType: 'json',
        maxFileSize: 2000000, //2MB
        acceptFileTypes: /(\.|\/)(gif|jpe?g|png)$/i,
        start: function() {
            $("#dw-message").empty();
            $('#upload-progress').removeClass('fade');
            $('.bar').parent().removeClass('progress-danger').addClass('progress-success');
            $('[type=submit]').attr('disabled', 'disabled');
        },
        progress: function (e, data) {
            var progress = parseInt(data.loaded / data.total * 100, 10);
            $('.bar').css('width',progress + '%');
        },
        add: function (e, data) {
            var jqXHR = data.submit()
            .done(function (result, textStatus, jqXHR) {
                if(textStatus!='success' || result.error!=null) {
                    $('.bar').parent().removeClass('progress-success').addClass('progress-danger');
                    DwMessage('Oops! el archivo no se ha podido cargar. <br />Detalle del error: '+(result.error!=null) ? result.error : textStatus);
                } else {
                    DwMessage('El archivo se ha cargado correctamente!', 'success');
                    $("#persona_fotografia").val(result.name);
                    $("#img-persona").attr('src', '<?php echo PUBLIC_PATH; ?>img/upload/personas/'+result.name);
                }
            })
            .fail(function (jqXHR, textStatus, errorThrown) {
                if(textStatus!=null){
                    DwMessage('Oops! el archivo no se ha podido cargar. <br />Detalle del error: '+textStatus);
                    $('.bar').parent().removeClass('progress-success').addClass('progress-danger');
                    setTimeout(function() { $('#upload-progress').addClass('fade'); }, 1000);
                } else {
                    DwMessage('Oops! al parecer el archivo no es una imágen válida. <br />Intenta con otro archivo.');
                    $('.bar').parent().removeClass('progress-success').addClass('progress-danger');
                    $('#upload-progress').addClass('fade');
                }
            })
            .always(function () {
                setTimeout(function() { $('#upload-progress').addClass('fade'); $('.bar').css('width','0%'); }, 1000);
                $('[type=submit]').removeAttr('disabled');
            });
        }
    });
</script>



<!--Esto aun no funca-->
<script type="text/javascript">
$('#imgcedula').fileupload({
        url: '<?php echo PUBLIC_PATH; ?>sistema/usuario/upload/',
        dataType: 'json',
        maxFileSize: 2000000, //2MB
        acceptFileTypes: /(\.|\/)(gif|jpe?g|png)$/i,
        start: function() {
            $("#dw-message").empty();
            $('#upload-progress1').removeClass('fade');
            $('.bar').parent().removeClass('progress-danger').addClass('progress-success');
            $('[type=submit]').attr('disabled', 'disabled');
        },
        progress: function (e, data) {
            var progress = parseInt(data.loaded / data.total * 100, 10);
            $('.bar').css('width',progress + '%');
        },
        add: function (e, data) {
            var jqXHR = data.submit()
            .done(function (result, textStatus, jqXHR) {
                if(textStatus!='success' || result.error!=null) {
                    $('.bar').parent().removeClass('progress-success').addClass('progress-danger');
                    DwMessage('Oops! el archivo no se ha podido cargar. <br />Detalle del error: '+(result.error!=null) ? result.error : textStatus);
                } else {
                    DwMessage('El archivo se ha cargado correctamente!', 'success');
                    $("#persona_imgcedula").val(result.name);
                    $("#imgcedula-persona").attr('src', '<?php echo PUBLIC_PATH; ?>img/upload/personas/'+result.name);
                }
            })
            .fail(function (jqXHR, textStatus, errorThrown) {
                if(textStatus!=null){
                    DwMessage('Oops! el archivo no se ha podido cargar. <br />Detalle del error: '+textStatus);
                    $('.bar').parent().removeClass('progress-success').addClass('progress-danger');
                    setTimeout(function() { $('#upload-progress1').addClass('fade'); }, 1000);
                } else {
                    DwMessage('Oops! al parecer el archivo no es una imágen válida. <br />Intenta con otro archivo.');
                    $('.bar').parent().removeClass('progress-success').addClass('progress-danger');
                    $('#upload-progress1').addClass('fade');
                }
            })
            .always(function () {
                setTimeout(function() { $('#upload-progress1').addClass('fade'); $('.bar').css('width','0%'); }, 1000);
                $('[type=submit]').removeAttr('disabled');
            });
        }
    });
</script>
