<?php View::notify(); ?>

<script type="text/javascript">
    $(function() {
        $('table').dwGrid({
            form_search: true,
            form_action: '<?php echo PUBLIC_PATH; ?>beneficiarios/titular/buscar/',
            form_load_data : 'dw-shell-content',
            order_attr: '<?php echo (APP_AJAX) ? 'class="dw-ajax dw-spinner"' : ''; ?>',
            order_action: $.KumbiaPHP.publicPath+"beneficiarios/titular/buscar/<?php echo $field.'/'.$value.'/'; ?>"
        });
    });
</script>

<div class="container-fluid dw-shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <div class="btn-toolbar btn-toolbar-top">
        <div class="btn-actions">
            <?php echo DwHtml::button("beneficiarios/titular/agregar/", 'agregar', array('class'=>'btn-success'), 'check', APP_AJAX); ?>
            <?php echo DwHtml::button("beneficiarios/titular/listar/", 'listar', array('class'=>'btn-warning'), 'ok', APP_AJAX); ?>
        </div>
    </div>

    <div class="dw-overflow" id="data-result">

        <table class="table table-bordered table-hover table-striped table-condensed table-responsive">
            <thead>
                <tr>
                    <th>NUM</th>
                    <th class="col-collapse" data-search="cedula">CEDULA</th>
                    <th class="col-collapse" data-search="nombre1">NOMBRE</th>
                    <th class="col-collapse" data-search="apellido1">APELLIDO</th>
                    <th class="col-collapse" data-search="nomina">NOMINA</th>
                    <th class="col-collapse" data-search="departamento">DEPARTAMENTO</th>
                    <?if(APP_OFFICE) { //Si está activa la opción de oficinas ?>
                    <th class="col-collapse" data-search="sucursal">SUCURSAL</th>
                    <? } ?>
                    <th class="col-collapse" data-search="estado_usuario">ESTADO</th>
                    <th class="btn-actions no-responsive" style="width: 100px;">ACCIONES</th>
                </tr>
            </thead>
            <tbody>
                <?php if($titulares) { ?>
                <?php foreach($titulares->items as $titular): ?>
                    <?php $key_upd = DwSecurity::getKey($titular->idtitular, 'upd_usuario'); ?>
                    <?php $key_ina = DwSecurity::getKey($titular->idtitular, 'bloquear_usuario'); ?>
                    <?php $key_rea = DwSecurity::getKey($titular->idtitular, 'reactivar_usuario'); ?>
                    <tr>
                        <td><?php echo $titulares->counter; ?></td>
                        <td><?php echo ($field=='cedula') ? DwUtils::resaltar($value, $titular->cedula) : $titular->cedula; ?></td>
                        <td><?php echo ($field=='nombre1') ? DwUtils::resaltar($value, $titular->nombre1) : $titular->nombre1; ?></td>
                        <td><?php echo ($field=='apellido1') ? DwUtils::resaltar($value, $titular->apellido1) : $titular->apellido1; ?></td>
                        <td><?php echo ($field=='nomina') ? DwUtils::resaltar($value, $titular->tipoe) : $titular->tipoe; ?></td>
                        <td><?php echo ($field=='departamento') ? DwUtils::resaltar($value, $titular->departamento) : $titular->departamento; ?></td>
                        <?if(APP_OFFICE) { //Si está activa la opción de oficinas ?>
                        <td><?php echo ($field=='sucursal') ? DwUtils::resaltar($value, $titular->sucursal) : $titular->sucursal; ?></td>
                        <? } ?>
                        <td><?php echo ($titular->estado_usuario == EstadoUsuario::ACTIVO) ? '<span class="label label-success">Activo</span>' : '<span class="label label-important">Bloqueado</span>'; ; ?></td>
                        <td>
                            <?php echo DwHtml::buttonTable('Modificar usuario', "sistema/usuario/editar/$key_upd/", null, 'info', 'edit'); ?>
                            <?php if($titular->estado_usuario == EstadoUsuario::ACTIVO) { ?>
                                <?php echo DwHtml::buttonTable('Bloquear usuario', "sistema/usuario/estado/bloquear/$key_ina/", null, 'success', 'flag'); ?>
                            <?php } else { ?>
                                <?php echo DwHtml::buttonTable('Reactivar usuario', "sistema/usuario/estado/reactivar/$key_rea/", null, 'danger', 'flag'); ?>
                            <?php } ?>
                        </td>
                    </tr>
                    <?php $titulares->counter++; ?>
                <?php endforeach; ?>
            </tbody>
            <?php } ?>
        </table>

    </div>

    <?php View::partial('paginators/default', false, array('page'=>$titulares, 'url'=>"beneficiarios/titular/buscar/$field/$value/$order/")); ?>

</div>
