<?php View::notify(); ?>
<style type="text/css">
    .tab-pane { min-height: 200px;}
</style>

<div class="container-fluid dw-shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <?php echo DwForm::open('', 'post', array('id'=>'form', 'class'=>'dw-validate')); ?>

     <?php if(DESKTOP) { ?>
        <ul class="nav nav-tabs">
        <?php } else { ?>
        <ul class="nav nav-pills nav-stacked">
        <?php } ?>
             <li class="active"><a href="#tab1" data-toggle="tab">Información personal</a></li>
            <li><a href="#tab2" data-toggle="tab">Direccion de Habitación</a></li>
            <li><a href="#tab3" data-toggle="tab">Información laboral</a></li>
            <li><a href="#tab4" data-toggle="tab">Cargar Archivos</a></li>
        </ul>
        <div class="tab-content">
        <div class="tab-pane active" id="tab1">
                <div class="row-fluid">
                     <div class="span3">
                        <?php echo DwForm::select('titular.nacionalidad', array(''=>'Seleccione:','V'=>'Venezolana', 'E'=>'Extranjera'), array('class'=>'input-xlarge input-required show-error'), $titular->nacionalidad, 'Nacionalidad:'); ?>
                    </div>
                    <div class="span3">
                        <?php 
                        echo DwForm::text('titular.cedula', array('class'=>'input-xlarge mask-pint input-numeric input-required show-error'), $titular->cedula ,'Cédula de Identidad'); 
                       ?>
                    </div>
                    <div class="span3">
                        <?php echo DwForm::select('titular.sexo', array(''=>'Seleccione:', 'M'=>'Masculino', 'F'=>'Femenino'), array('class'=>'input-xlarge input-required show-error'), $titular->sexo, 'Sexo:'); ?>
                    </div>
                    <div class="span3">
                        <?php echo DwForm::date('titular.fecha_nacimiento', array('class'=>'input-large input-required mask-date input-date show-errors'),date("Y-m-d"), $titular->fecha_nacimiento, 'Fecha de Nacimiento'); ?>
                    </div>
                </div>
                
                <div class="row-fluid">
                    <div class="span3">
                        <?php echo DwForm::text('titular.nombre1', array('class'=>'input-xlarge input-required mask-alpha show-error'), $titular->nombre1, 'Primer Nombre'); ?>
                    </div>
                    <div class="span3">
                        <?php echo DwForm::text('titular.nombre2', array('class'=>'input-xlarge mask-alpha show-error'), $titular->nombre2, 'Segundo Nombre'); ?>
                    </div>
                    <div class="span3">
                        <?php echo DwForm::text('titular.apellido1', array('class'=>'input-xlarge input-required mask-alpha show-error'), $titular->apellido1, 'Primer Apellido'); ?>
                    </div>
                    <div class="span3">
                        <?php echo DwForm::text('titular.apellido2', array('class'=>'input-xlarge mask-alpha show-error'), $titular->apellido2, 'Segundo Apellido'); ?>
                    </div>
                </div>
                <div class="row-fluid">
                    <div class="span3">
                        <?php echo DwForm::select('titular.estado_civil', array(''=>'Seleccione:', 'S'=>'Soltero', 'c'=>'Concubinato','C'=>'Casado', 'D'=>'Divorciado', 'V'=>'Viudo'), array('class'=>'input-xlarge input-required show-error'), $titular->estado_civil, 'Estado Civil'); ?>
                    </div>
                    <div class="span3">
                         <?php echo DwForm::select('titular.grupo_sanguineo', array(''=>'Seleccione:', 'O-'=>'O-', 'O+'=>'O+','A-'=>'A-', 'A+'=>'A+', 'AB+'=>'AB+', 'AB-'=>'AB-'), array('class'=>'input-xlarge show-error'), $titular->grupo_sanguineo, 'Grupo Sanguineo'); ?>
                    </div>
                    <div class="span3">
                        <?php echo DwForm::tel('titular.telefono', array('class'=>'input-numeric input-xlarge mask-pint show-error'), $titular->telefono, 'Teléfono Fijo'); ?>
                    </div>
                    <div class="span3">
                        <?php echo DwForm::tel('titular.celular', array('class'=>'input-numeric input-xlarge input-required mask-pint show-error'), $titular->celular, 'Telefono Móvil'); ?>
                    </div>
                </div>
                <!-- Datos de Lugar de nacimiento-->
                <div class="row-fluid">
                    <div class="span3">
                        <?php echo DwForm::dbSelect('titular.pais_id', 'nombre', array('params/pais', 'getListadoPais'), NULL, array('class'=>'input-xlarge input-required mask-pint show-errors'), $titular->pais_id, 'Pais Nacimiento'); ?>
                    </div>
                    <div class="span3">
                        <label>Estado</label>
                        <div id='div_estado'><select class="input-xlarge"> <option value=""> Seleccione:</option></select></div>
                    </div>
                    <div class="span3">
                        <label>Municipio</label>
                        <div id='div_municipio'><select class="input-xlarge"> <option value=""> Seleccione:</option></select></div>
                    </div>
                    <div class="span3">
                        <label>Parroquia</label>
                        <div id='div_parroquia'><select class="input-xlarge"> <option value=""> Seleccione:</option></select></div>  
                    </div>

                </div>
            <label>(*) Campos Obligatorios </label>
            </div><!--Cierrre del Tab1-->
            <!-- Datos de direccion de Habitacion-->
            <div class="tab-pane" id="tab2">
                <div class="row-fluid">
                    <div class="span3">
                        <?php echo DwForm::dbSelect('titular.hpais_id', 'nombre', array('params/pais', 'getListadoPais'), NULL, array('class'=>'input-large input-required mask-pint show-errors'), NULL, 'Pais Residencia'); ?>
                    </div>
                    <div class="span3">
                        <label>Estado</label>
                        <div id='div_hestado'> <select class="input-xlarge"> <option value=""> Seleccione:</option></select></div>
                    </div>
                    <div class="span3">
                        <label>Municipio</label>
                        <div id='div_hmunicipio'><select class="input-xlarge"> <option value=""> Seleccione:</option></select></div>
                    </div>
                    <div class="span3">
                        <label>Parroquia</label>
                        <div id='div_hparroquia'><select class="input-xlarge"> <option value=""> Seleccione:</option></select></div>  
                    </div>
                </div>
                <div class="row-fluid">
                    <div class="span6">
                        <?php echo DwForm::text('titular.direccion_habitacion', array('class'=>'input-xxlarge input-required show-error'), $titular->direccion_habitacion, 'Dirección de Habitación'); ?>
                    </div>
                    <div class="span6">
                        <?php echo DwForm::email('titular.correo_electronico', array('class'=>'input-xxlarge show-error'), $titular->correo_electronico, 'Correo Electronico'); ?>
                    </div>
                </div>
            </div><!-- *************** cierre del tab2 **************************** -->
            <div class="tab-pane" id="tab3">
                <div class="row-fluid">
                    <div class="span4">
                        <?php echo DwForm::dbSelect('titular.tipoempleado_id', 'nombre', array('config/tipoempleado', 'getListadoTipoempleado'), NULL, array('class'=>'input-xlarge input-required input-list show-errors'), $titular->tipoempleado_id, 'Tipo Trabajador'); ?>
                    </div>
                    <div class="span4">
                        <?php echo DwForm::date('titular.fecha_ingreso', array('class'=>'input-xlarge input-required mask-date input-date show-errors'), date("Y-m-d"), 'Fecha de Ingreso'); ?>
                    </div>
                    <div class="span4">
                        <?php echo DwForm::dbSelect('titular.profesion_id', 'nombre', array('config/profesion', 'getListadoProfesion'), NULL, array('class'=>'input-xlarge input-required input-list show-errors'), $titular->profesion_id, 'Profesión u Oficio'); ?>
                    </div>
                </div>
                <div class="row-fluid">
                    <div class="span4">
                        <?php echo DwForm::dbSelect('usuario.sucursal_id', array('sucursal', 'parroquia'), array('config/sucursal', 'getListadoSucursal'), array('todas'=>'Todas'), array('class'=>'input-xlarge input-required mask-pint show-errors'), NULL, 'Sucursal / UPSA'); ?>
                    </div>
                    <div class="span4">
                     <label>Departamento</label>
                        <div id='div_departamento'><select class="input-xlarge"> <option value=""> Seleccione:</option></select></div>
                    </div>
                    <div class="span4">
                        <?php echo DwForm::dbSelect('titular.cargo_id', 'nombre', array('config/cargo', 'getListadoCargo'), NULL, array('class'=>'input-xlarge input-required input-list show-errors'), NULL, 'Cargo'); ?>
                    </div>
                   
                </div>
                <div class="row-fluid">
                    <div class="span12">
                        <?php echo DwForm::textarea('titular.observacion', array('class'=>'input-xxlarge mask-alphanum show-error'), NULL, 'Observación'); ?>
                    </div>
                </div>
            </div><!-- ************************* Cierre del tab3 ********************* -->
            <div class="tab-pane" id="tab4">
                <div class="row fileupload-buttonbar">
                    <div class="span2">
                        <span class="btn btn-success fileinput-button">
                            <i class="icon-plus icon-white"></i>
                            <span>Seleccionar fotografía...</span>
                            <input id="fotografia" type="file" name="fotografia" class="input-large">
                        </span>
                    </div>

                    <div id="upload-progress" class="span4 fileupload-progress fade">
                        <div class="progress progress-success progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100">
                            <div class="bar" style="width:0%;"></div>
                        </div>
                    </div>

                    <div class="span5 dw-text-right">
                        <div class="span5 dw-picture-profile dw-text-center dw-text-middle dw-shadow-dark" style="margin-top: 5px">
                            <?php echo DwHtml::img("upload/personas/$usuario->fotografia", "$usuario->nombre $usuario->apellido", array('id'=>'img-persona')); ?>
                        </div>
                    </div>

                </div>

                <div class="row-fluid">

                    <?php echo DwForm::hiddenKey('usuario.id', $usuario->id); ?>
                    <?php echo DwForm::hidden('persona.fotografia', NULL, 'default.png'); ?>

                    <div class="form-actions">
                        <?php echo DwButton::save('Guardar usuario'); ?>
                        <?php echo DwButton::reset('form'); ?>
                        <?php echo DwButton::cancel(); ?>
                    </div>
                </div>

            </div>

        </div>

    <?php echo DwForm::close(); ?>

</div>

<?php View::partial('jquery.file-upload'); ?>

<script type="text/javascript">
    $('#fotografia').fileupload({
        url: '<?php echo PUBLIC_PATH; ?>sistema/usuario/upload/',
        dataType: 'json',
        maxFileSize: 2000000, //2MB
        acceptFileTypes: /(\.|\/)(gif|jpe?g|png)$/i,
        start: function() {
            $("#dw-message").empty();
            $('#upload-progress').removeClass('fade');
            $('.bar').parent().removeClass('progress-danger').addClass('progress-success');
            $('[type=submit]').attr('disabled', 'disabled');
        },
        progress: function (e, data) {
            var progress = parseInt(data.loaded / data.total * 100, 10);
            $('.bar').css('width',progress + '%');
        },
        add: function (e, data) {
            var jqXHR = data.submit()
            .done(function (result, textStatus, jqXHR) {
                if(textStatus!='success' || result.error!=null) {
                    $('.bar').parent().removeClass('progress-success').addClass('progress-danger');
                    DwMessage('Oops! el archivo no se ha podido cargar. <br />Detalle del error: '+(result.error!=null) ? result.error : textStatus);
                } else {
                    DwMessage('El archivo se ha cargado correctamente!', 'success');
                    $("#persona_fotografia").val(result.name);
                    $("#img-persona").attr('src', '<?php echo PUBLIC_PATH; ?>img/upload/personas/'+result.name);
                }
            })
            .fail(function (jqXHR, textStatus, errorThrown) {
                if(textStatus!=null){
                    DwMessage('Oops! el archivo no se ha podido cargar. <br />Detalle del error: '+textStatus);
                    $('.bar').parent().removeClass('progress-success').addClass('progress-danger');
                    setTimeout(function() { $('#upload-progress').addClass('fade'); }, 1000);
                } else {
                    DwMessage('Oops! al parecer el archivo no es una imágen válida. <br />Intenta con otro archivo.');
                    $('.bar').parent().removeClass('progress-success').addClass('progress-danger');
                    $('#upload-progress').addClass('fade');
                }
            })
            .always(function () {
                setTimeout(function() { $('#upload-progress').addClass('fade'); $('.bar').css('width','0%'); }, 1000);
                $('[type=submit]').removeAttr('disabled');
            });
        }
    });
</script>
