<label>Municipio<span class="req">*</span></label>
<?php
    echo Form::dbSelect("titular.hmunicipio_id", 'nombre', array('municipio','buscar',$estado_id), '           -  Seleccione  -           ');
?>		
 
<script type='text/javascript'>
$("#titular_hmunicipio_id").change(function(){
    var municipio_id     =   $('#titular_hmunicipio_id').val();
        $.ajax({
          type: "POST",
          url: "<?php echo PUBLIC_PATH . 'beneficiarios/titular/getHParroquiaMunicipio/'; ?>",
          data: "municipio_id=" + municipio_id,
          success: function(html){
            $("#div_hparroquia").html(html);
          }
        });
});
</script>