<?php View::notify(); ?>

<script type="text/javascript">
    $(function() {
        $('table').dwGrid({
            form_search: true,
            form_action: '<?php echo PUBLIC_PATH; ?>beneficiarios/titular/buscar/',
            form_load_data : 'dw-shell-content',
            order_attr: '<?php echo (APP_AJAX) ? 'class="dw-ajax dw-spinner"' : ''; ?>',
            order_action: $.KumbiaPHP.publicPath+"beneficiarios/titular/listar/"
        });
    });
</script>

<div class="container-fluid dw-shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <div class="btn-toolbar btn-toolbar-top">
        <div class="btn-actions">
            <?php echo DwHtml::button("beneficiarios/titular/agregar/", 'agregar', array('class'=>'btn-success'), 'check', APP_AJAX); ?>
        </div>
    </div>

    <div class="dw-overflow" id="data-result">

        <table class="table table-bordered table-hover table-striped table-condensed table-responsive">
            <thead>
                <tr>
                    <th>NUM</th>
                    <th class="col-collapse" data-search="cedula">CEDULA</th>
                    <th class="col-collapse" data-search="nombre1">NOMBRE</th>
                    <th class="col-collapse" data-search="apellido1">APELLIDO</th>
                    <th class="col-collapse" data-search="nomina">NOMINA</th>
                    <th class="col-collapse" data-search="departamento">DEPARTAMENTO</th>
                    <?if(APP_OFFICE) { //Si está activa la opción de oficinas ?>
                    <th class="col-collapse" data-search="sucursal">SUCURSAL</th>
                    <? } ?>
                    <th class="col-collapse" data-search="estado_usuario">ESTADO</th>
                    <th class="btn-actions no-responsive" style="width: 150px;">ACCIONES</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($titulares->items as $titular): ?>
                    <?php $key_shw = DwSecurity::getKey($titular->id, 'shw_titular'); ?>
                    <?php $key_upd = DwSecurity::getKey($titular->id, 'upd_titular'); ?>
                    <?php $key_ina = DwSecurity::getKey($titular->id, 'bloquear_usuario'); ?>
                    <?php $key_rea = DwSecurity::getKey($titular->id, 'reactivar_usuario'); ?>
                    <tr>
                        <td><?php echo $titulares->counter; ?></td>
                        <td><?php echo $titular->cedula; ?></td>
                        <td><?php echo $titular->nombre1; ?></td>
                        <td><?php echo $titular->apellido1; ?></td>
                        <td><?php echo $titular->tipoe; ?></td>
                        <td><?php echo $titular->departamento; ?></td>
                        <?if(APP_OFFICE) { //Si está activa la opción de oficinas ?>
                        <td><?php echo empty($titular->sucursal) ? 'Todas' : $titular->sucursal; ?></td>
                        <? } ?>
                        <td><?php // echo ($usuario->estado_usuario == EstadoUsuario::ACTIVO) ? '<span class="label label-success" title="'.$usuario->descripcion.'" rel="tooltip">Activo</span>' : '<span class="label label-important" title="'.$usuario->descripcion.'" rel="tooltip">Bloqueado</span>'; ; ?></td>
                        <td>
                            <?php echo DwHtml::buttonTable('Ver titular', "beneficiarios/titular/ver/$key_shw/", NULL, 'warning', 'search'); ?>
                            <?php echo DwHtml::buttonTable('Modificar titular', "beneficiarios/titular/editar/$key_upd/", NULL, 'info', 'edit'); ?>
                            
                        </td>
                    </tr>
                    <?php $titulares->counter++; ?>
                <?php endforeach; ?>
            </tbody>
        </table>

    </div>

    <?php View::partial('paginators/default', false, array('page'=>$titulares, 'url'=>"beneficiarios/titular/listar/$order/")); ?>

<?php echo Form::text('autocomplete') ?>
 
<script type="text/javascript" > 
    $(document).ready(function(){
        $('input#autocomplete').autocomplete({
 
            minLength : 1 , //le indicamos que busque a partir de haber escrito dos o mas caracteres en el input
 
            source : function( request , response ){
 
                var url = "<?php echo PUBLIC_PATH ?>beneficiarios/titular/autocomplete";   //url donde buscará los estados
 
                $.post(url, { 'busqueda' : request.term }, response, 'json');
 
                //busqueda es la varible que mandaremos por post con el contenido del input
            }
        });
    });
</script>

</div>
