<?php View::notify(); ?>
<script type="text/javascript">
    $(function() {
        $('table').dwGrid({
            form_search: true,
            form_action: '<?php echo PUBLIC_PATH; ?>beneficiarios/titular/buscar/',
            form_load_data : 'dw-shell-content',
            order_attr: '<?php echo (APP_AJAX) ? 'class="dw-ajax dw-spinner"' : ''; ?>',
            order_action: $.KumbiaPHP.publicPath+"beneficiarios/titular/listar/"
        });
    });
</script>

<div class="container-fluid dw-shell-view">
    <?php View::process($page_module, $page_title, $set_title); ?>
    <div class="btn-toolbar btn-toolbar-top">
        <div class="btn-actions">
            <?php echo DwHtml::button("beneficiarios/titular/agregar/", 'agregar', array('class'=>'btn-success'), 'check', APP_AJAX); ?>
            <?php echo DwButton::report("titular/listar/", 'html', 'Reporte de Titulares', 'imprimir'); ?>
            <? echo DwHtml::buttonTable('Listado General', "beneficiarios/titular/reportetitularbeneficiario/", NULL, 'success', 'search');
            ?>
        </div>
    </div>

    <div class="dw-overflow" id="data-result">

        <table class="table table-bordered table-hover table-striped table-condensed table-responsive">
            <thead>
                <tr>
                    <th>NUM</th>
                    <th class="col-collapse" data-search="cedula">CÉDULA</th>
                    <th class="col-collapse" data-search="nombre">NOMBRE</th>
                    <th class="col-collapse" data-search="apellido">APELLIDO</th>
                    <th class="col-collapse" data-search="nomina">NOMINA</th>
                    <th class="col-collapse" data-search="departamento">DEPARTAMENTO</th>
                    <th class="col-collapse" data-search="sucursal">SUCURSAL</th>
                    <th class="col-collapse" data-search="estado">ESTADO</th>
                    <th class="btn-actions no-responsive" style="width: 200px;">ACCIONES</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($titulares->items as $titular): ?>
                    <?php $key_shw = DwSecurity::getKey($titular->idtitular, 'shw_titular'); ?>
                    <?php $key_upd = DwSecurity::getKey($titular->idtitular, 'upd_titular'); ?>
                    <?php $key_ina = DwSecurity::getKey($titular->idtitular, 'excluir_usuario'); ?>
                    <?php $key_rea = DwSecurity::getKey($titular->idtitular, 'reactivar_usuario'); ?>
                    <tr>
                        <td><?php echo $titulares->counter; ?></td>
                        <td><?php echo $titular->cedula; ?></td>
                        <td><?php echo $titular->nombre1; ?></td>
                        <td><?php echo $titular->apellido1; ?></td>
                        <td><?php echo $titular->tipoe; ?></td>
                        <td><?php echo $titular->departamento; ?></td>
                        <td><?php echo $titular->sucursal; ?></td>
                        <td><?php if ($titular->estado == 1){ echo '<span class="label label-success">Activo</span>'; } else{ echo '<span class="label label-important">Inactivo</span>'; } ?></td>
                        <td>
                            <?php if ($titular->estado==1){ 
                            echo DwHtml::buttonTable('Agregar Beneficiarios', "beneficiarios/beneficiario/agregar/$key_shw/", NULL, 'success', 'user'); 
                            echo DwHtml::buttonTable('Ver titular', "beneficiarios/titular/reportetitular/$key_shw/", NULL, 'warning', 'search');
                            echo DwHtml::buttonTable('Modificar titular', "beneficiarios/titular/editar/$key_upd/", NULL, 'info', 'edit'); 
                            }
                            if((Session::get('perfil_id')<=3) && ($titular->estado==1) ){ 
                                echo DwHtml::buttonTable('Excluir Titular', "beneficiarios/titular/excluir/$key_ina/", array('class'=>'js-confirm', 'confirm-title'=>'Excluir Titular', 'confirm-body'=>'¿Está seguro de Excluir el Titular? <br/>'), 'danger', 'repeat');
                            }
                            if((Session::get('perfil_id')<=3) && ($titular->estado!=1) ){ 
                                echo DwHtml::buttonTable('Reactivar Titular', "beneficiarios/titular/reactivar/$key_rea/", array('class'=>'js-confirm', 'confirm-title'=>'Reactivar Titular', 'confirm-body'=>'¿Está seguro de Reactivar el Titular? <br />'), 'success', 'repeat');
                            }
                           ?>
                        </td>
                    </tr>
                    <?php $titulares->counter++; ?>
                <?php endforeach; ?>
            </tbody>
        </table>

    </div>

    <?php View::partial('paginators/default', false, array('page'=>$titulares, 'url'=>"beneficiarios/titular/listar/$order/")); ?>
