<?php $res = Load::model('usuarios')->find('limit: 8', 'order: id DESC'); ?>
<?php $actual = Form::getFieldValue('usuario.id') //vriable con el id del registro que se edita ?>

<ul class="nav nav-tabs nav-stacked backend_menu_lateral visible-desktop">
    <li class="<?php if (!$actual) echo 'active'; ?>">
        <?php echo Html::linkAction("crear", 'Agregar Nuevo'); ?>
    </li>
    <?php foreach ($res as $e): ?>
        <li class="<?php if ($e->id == $actual) echo 'active'; ?>">
            <?php $content = Html::gravatar($e->email,'gravatar',35); ?>
            <?php $content .= h(strtoupper($e->login)); ?>
            <?php $content .= "<h6>" . h($e->nombres) . "</h6>" ?>
            <?php echo Html::linkAction("editar/$e->id", "$content<div style=\"clear: both\"></div>"); ?>
        </li>
    <?php endforeach; ?>
    <li>
        <?php echo Html::linkAction("", 'Ver Todos...'); ?>
    </li>
</ul>