<h1 style="margin-bottom: 20px;">Bienvenido al KumbiaPHP Backend</h1>

<?php View::content() ?>
<a class="thumbnail span3 pull-right" style="margin: 0 20px 20px;"><?php echo Html::img('backend/Admin1.png', 'Backend'); ?></a>
<p>
    EL backend es el módulo de administración y configuración de una aplicación,
    a traves de el podremos gestionar las diferentes partes de la misma, desde el control
    de los usuarios de sistemas y sus privilegios, hasta llevar auditorias sobre
    las acciones que realizan los mismos dentro de la aplicación.
</p>
<br/>
<!--<br/>
<br/>
<br/>
<br/>
<br/>-->
<h4 style="margin-bottom: 20px;">Entre las principales caracteristicas del backend podemos mencionar:</h4>
<ul class="bienvenida">
    <li>
        <?php echo Html::img('backend/usuarios.gif', 'usuarios') ?>
        Gestión de Usuarios
    </li>
    <li>
        <?php echo Html::img('backend/perfil_profesional.jpg', 'perfiles') ?>
        Gestión de Roles (Perfiles de Usuario)
    </li>
    <li>
        <?php echo Html::img('backend/recursos.png', 'recursos') ?>
        Gestión de Recursos (Módulos de la Aplicación)
    </li>
    <li>
        <?php echo Html::img('backend/permisos.jpg', 'permisos') ?>
        Gestión de Privilegios (Permisos de los usuarios a los diferentes Modulos de la Aplicación)
    </li>
    <li>
        <?php echo Html::img('backend/auditorias.jpg', 'auditorias') ?>
        Módulo de Auditorias (Revisión de las acciones realizadas por los usuarios en la Aplicación)
    </li>
    <li>
        <?php echo Html::img('backend/config.jpg', 'Configuración') ?>
        Configuración general de la Aplicación.
    </li>
</ul>

<div style="clear: both;"></div>