<?php View::notify(); ?>
<script type="text/javascript">
    $(function() {
        $('table').dwGrid({
            form_search: true,
            form_action: '<?php echo PUBLIC_PATH; ?>config/patologia/buscar/',
            form_load_data : 'dw-shell-content',
            order_attr: '<?php echo (APP_AJAX) ? 'class="dw-ajax dw-spinner"' : ''; ?>',
            order_action: $.KumbiaPHP.publicPath+"config/patologia/listar/"
        });
    });
</script>
<div class="container-fluid dw-shell-view">
    <?php View::process($page_module, $page_title, $set_title); ?>
    <div class="btn-toolbar btn-toolbar-top">
        <div class="btn-actions">
            <?php echo DwHtml::button("config/patologia/agregar/", 'agregar', array('class'=>'btn-success'), 'check', APP_AJAX); ?>
        </div>
    </div>
    <div class="dw-overflow" id="data-result">

        <table class="table table-bordered table-hover table-striped table-condensed table-responsive">
            <thead>
                <tr>
                    <th>NUM</th>
                    <th class="col-collapse" data-search="codigo">CODIGO</th>
                    <th class="col-collapse" data-search="nombre">NOMBRE</th>
                    <th class="col-collapse" data-search="observacion">OBSERVACION</th>
                    <th class="btn-actions no-responsive" style="width: 150px;">ACCIONES</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($patologias->items as $patologia): ?>
                    <?php $key_upd = DwSecurity::getKey($patologia->id, 'upd_patologia'); ?>
                    <?php $key_del = DwSecurity::getKey($patologia->id, 'del_patologia'); ?>
                    <tr>
                        <td><?php echo $patologias->counter; ?></td>
                        <td><?php echo $patologia->codigo; ?></td>
                        <td><?php echo $patologia->descripcion; ?></td>
                        <td><?php echo $patologia->observacion; ?></td>
                        <td>
                            <?php echo DwHtml::buttonTable('Modificar Patologia', "config/patologia/editar/$key_upd/", null, 'info', 'edit'); ?>
                            <?php 
                            if($patologia->activo){
                                echo DwHtml::buttonTable('Desactivar Patologia', "config/patologia/desactivar/$key_upd/", array('class'=>'js-confirm', 'confirm-title'=>'Desactivar Patologia', 'confirm-body'=>'Está seguro de Desactivar esta Patologia? <br />Recuerda que esta operación no se puede reversar.'), 'warning', 'ban-circle');
                            }
                            else{
                                echo DwHtml::buttonTable('Activar Patologia', "config/patologia/activar/$key_upd/", array('class'=>'js-confirm', 'confirm-title'=>'Desactivar Patologia', 'confirm-body'=>'Está seguro de Activar esta Patologia?.'), 'success', 'plus-sign');
                            }
                            ?>
                            <?php echo DwHtml::buttonTable('Eliminar Patologia', "config/patologia/eliminar/$key_del/", array('class'=>'js-confirm', 'confirm-title'=>'Eliminar patologia', 'confirm-body'=>'Está seguro de eliminar esta patologia? <br />Recuerda que esta operación no se puede reversar.'), 'danger', 'remove'); ?>
                        </td>
                    </tr>
                    <?php $patologias->counter++; ?>
                <?php endforeach; ?>
            </tbody>
        </table>

    </div>

    <?php View::partial('paginators/default', false, array('page'=>$patologias, 'url'=>"config/patologia/listar/$order/")); ?>

</div>
