<?php View::notify(); ?>

<div class="container-fluid dw-shell-view">
    <?php View::process($page_module, $page_title, $set_title); ?>

    <?php echo DwForm::open('', 'post', array('id'=>'form', 'class'=>'dw-validate')); ?>
        
        <div class="row-fluid">
            <div class="span6">
                <?php echo DwForm::text('solicitud_servicio.codigo_solicitud', array('class'=>'input-xxlarge '),NULL, 'Código:'); ?>
            </div>
            <div class="span6">
                <?php echo DwForm::text('solicitud_servicio.fecha_solicitud', array('class'=>'input-xxlarge  show-error'), date("Y/m/d"), 'Fecha Solicitud'); ?>
            </div>
        </div>
        <div>
        
        <div class="row-fluid">
            <div class="span6">
                <?php echo DwForm::dbSelect('solicitud_servicio.tiposolicitud_id', 'nombre_corto', array('config/tiposolicitud', 'getListadoTiposolicitud'), NULL, array('class'=>'input-xxlarge input-required mask-pint show-errors'), NULL, 'Tipo de Solicitud'); ?>
            </div>
            <div class="span6">
                <?php echo DwForm::dbSelect('solicitud_servicio.titular_id', 'nombre1', array('beneficiarios/titular', 'getListadoTitular'), NULL, array('class'=>'input-xxlarge input-required mask-pint show-errors'), NULL, 'Titular'); ?>
                <?php echo DwForm::text('solicitud_servicio.titular_id', array('class'=>'input-xxlarge input-required '), NULL, 'Cedula Titular'); ?>
            </div>
        </div>

        <div class="row-fluid">
            <div class="span6">
                <?php echo DwForm::text('solicitud_servicio.beneficiario_id', array('class'=>'input-xxlarge input-required '), NULL, 'Cedula Beneficiario'); ?>
            </div>
            <div class="span6">
                <?php echo DwForm::text('solicitud_servicio.nombre', array('class'=>'input-xxlarge input-required show-error'), NULL, 'Nombre'); ?>
            </div>
        </div>
        <div>
        <div class="row-fluid">
            <div class="span6">
                <?php echo DwForm::text('solicitud_servicio.persona_autorizada', array('class'=>'input-xxlarge input-required '), NULL, 'Cedula Titular'); ?>
            </div>
            <div class="span6">
                <?php echo DwForm::text('solicitud_servicio.persona_cedula', array('class'=>'input-xxlarge input-required show-error'), NULL, 'Nombre'); ?>
            </div>
        </div>
        <div>
        <div class="row-fluid">
            <div class="span6">
                <?php echo DwForm::dbSelect('solicitud_servicio.proveedor_id', 'nombre_corto', array('proveedorsalud/proveedor', 'getListadoProveedor'), NULL, array('class'=>'input-xxlarge input-required mask-pint show-errors'), NULL, 'Proveedor'); ?>
            </div>

            <div class="span6">
                <?php echo DwForm::radio('solicitud_servicio.tipo_tratamiento', 'T', 'Temporal'); ?>
                <?php echo DwForm::radio('solicitud_servicio.tipo_tratamiento', 'P','Permanente'); ?>
            </div>
        </div>
        <div class="row-fluid">
            <div class="span6">
                <?php echo DwForm::dbSelect('solicitud_servicio.patologia_id', 'descripcion', array('config/patologia', 'getListadoPatologia'), NULL, array('class'=>'input-xxlarge input-required mask-pint show-errors'), NULL, 'Patologia'); ?>
            </div>
            <div class="span6">
                <?php echo DwForm::dbSelect('solicitud_servicio.patologia_id', 'descripcion', array('config/patologia', 'getListadoPatologia'), NULL, array('class'=>'input-xxlarge input-required mask-pint show-errors'), NULL, 'Patologia'); ?>
            </div>
        </div>
        
        <div class="row-fluid">
            

        </div>


        <div class="row-fluid">
            <div class="form-actions">
                <?php echo DwButton::save('Guardar Solicitud'); ?>
                <?php echo DwButton::reset('form'); ?>
                <?php echo DwButton::cancel(); ?>
            </div>
        </div>

    <?php echo DwForm::close(); ?>
</div>
