<?php View::notify(); ?>

<div class="container-fluid dw-shell-view">
    <?php View::process($page_module, $page_title, $set_title); ?>

    <?php echo DwForm::open('', 'post', array('id'=>'form', 'class'=>'dw-validate')); ?>

        <div class="row-fluid">
            <div class="span6">
                <?php echo DwForm::dbSelect('solicitud_servicio.tiposolicitud_id', 'nombre', array('config/tiposolicitud', 'getListadoTiposolicitud'), NULL, array('class'=>'input-xxlarge input-required mask-pint show-errors'), NULL, 'Tipo de Solicitud'); ?>
            </div>
            <div class="span6">
                <?php echo DwForm::text('solicitud_servicio.fecha_solicitud', array('class'=>'input-xxlarge  show-error'), date("Y/m/d"), 'Fecha Solicitud'); ?>
            </div>
        </div>
        <div>
        
        <div class="row-fluid">
            <div class="span6">
            <?php echo DwForm::text('solicitud_servicio.codigo_solicitud', array('class'=>'input-xxlarge '),NULL, 'Código:'); ?>
            </div>
            <div class="span6">
                <?php echo DwForm::text('solicitud_servicio.fecha_solicitud', array('class'=>'input-xxlarge  show-error'), date("Y/m/d"), 'Fecha Vencimiento'); ?>
            </div>
        </div>

        <div class="row-fluid">
            <div class="span6">
                <?php //echo DwForm::dbSelect('solicitud_servicio.titular_id', 'cedula', array('beneficiarios/titular', 'getListadoTitular'), NULL, array('class'=>'input-xxlarge input-required input-list show-errors'), NULL, 'Titular'); ?>
                <?php echo DwForm::text('solicitud_servicio.titular_id', array('class'=>'input-xxlarge input-required '), NULL, 'Cedula Titular'); ?>
            </div>
            <div class="span6">

            </div>
        </div>
        <div>
        <div class="row-fluid">
            <div class="span6">
                <?php echo DwForm::text('solicitud_servicio.beneficiario_id', array('class'=>'input-xxlarge input-required '), NULL, 'Cedula Beneficiario'); ?>
            </div>
            <div class="span6">
                <?php echo DwForm::text('solicitud_servicio.proveedor_id', array('class'=>'input-xxlarge input-required '), NULL, 'Proveedor'); ?>
            </div>
        </div>
        <div>
         </div>
        <div class="row-fluid">
            <div class="span6">
               <?php echo DwForm::text('solicitud_servicio.medico_id', array('class'=>'input-xxlarge input-required '), NULL, 'Medico'); ?>

                <?php // DwForm::dbSelect('solicitud_servicio.patologia_id', 'descripcion', array('config/patologia', 'getListadoPatologia'), NULL, array('class'=>'input-xxlarge input-required mask-pint show-errors'), NULL, 'Patologia'); ?>
            </div>
            <div class="span6">
                <?php echo DwForm::text('solicitud_servicio.servicio_id', array('class'=>'input-xxlarge input-required '), NULL, 'Servicio'); ?>
                <?php //echo DwForm::dbSelect('solicitud_servicio.patologia_id', 'descripcion', array('config/patologia', 'getListadoPatologia'), NULL, array('class'=>'input-xxlarge input-required mask-pint show-errors'), NULL, 'Patologia'); ?>
            </div>
        </div>
        <div class="row-fluid">
            <div class="span6">

               <?php echo DwForm::text('solicitud_servicio.patologia_id', array('class'=>'input-xxlarge input-required '), NULL, 'Patologia'); ?>

                <?php // DwForm::dbSelect('solicitud_servicio.patologia_id', 'descripcion', array('config/patologia', 'getListadoPatologia'), NULL, array('class'=>'input-xxlarge input-required mask-pint show-errors'), NULL, 'Patologia'); ?>
            </div>
            <div class="span6">
                <?php echo DwForm::textarea('solicitud_servicio.observacion_id', array('class'=>'input-required mask-text show-error input-xxlarge'), NULL, 'Observacion'); ?>
                <?php //echo DwForm::dbSelect('solicitud_servicio.patologia_id', 'descripcion', array('config/patologia', 'getListadoPatologia'), NULL, array('class'=>'input-xxlarge input-required mask-pint show-errors'), NULL, 'Patologia'); ?>
            </div>
        </div>

        
        <div class="row-fluid">
            

        </div>
        <div class="row-fluid">
            <div class="form-actions">
                <?php echo DwButton::save('Guardar Solicitud'); ?>
                <?php echo DwButton::reset('form'); ?>
                <?php echo DwButton::cancel(); ?>
            </div>
        </div>

    <?php echo DwForm::close(); ?>
</div>
<script type="text/javascript" >
    $(document).ready(function(){
        $('input#solicitud_servicio_beneficiario_id').autocomplete({
 
            minLength : 1 , //le indicamos que busque a partir de haber escrito dos o mas caracteres en el input
 
            source : function( request , response ){
 
                var url = "<?php echo PUBLIC_PATH ?>beneficiarios/titular/autocomplete";   //url donde buscará los estados
 
                $.post(url, { 'busqueda' : request.term }, response, 'json');
 
                //busqueda es la varible que mandaremos por post con el contenido del input
            }
        });

        $('input#solicitud_servicio_titular_id').autocomplete({
 
            minLength : 1 , //le indicamos que busque a partir de haber escrito dos o mas caracteres en el input
 
            source : function( request , response ){
 
                var url = "<?php echo PUBLIC_PATH ?>beneficiarios/titular/autocomplete";   //url donde buscará los estados
 
                $.post(url, { 'busqueda' : request.term }, response, 'json');
 
                //busqueda es la varible que mandaremos por post con el contenido del input
            }
        });

        $('input#solicitud_servicio_patologia_id').autocomplete({
 
            minLength : 1 , //le indicamos que busque a partir de haber escrito dos o mas caracteres en el input
 
            source : function( request , response ){
 
                var url = "<?php echo PUBLIC_PATH ?>config/patologia/autocomplete";   //url donde buscará los estados
 
                $.post(url, { 'busqueda' : request.term }, response, 'json');
 
                //busqueda es la varible que mandaremos por post con el contenido del input
            }
        });
$('input#solicitud_servicio_proveedor_id').autocomplete({
 
            minLength : 1 , //le indicamos que busque a partir de haber escrito dos o mas caracteres en el input
 
            source : function( request , response ){
 
                var url = "<?php echo PUBLIC_PATH ?>proveedorsalud/proveedor/autocomplete";   //url donde buscará los estados
 
                $.post(url, { 'busqueda' : request.term }, response, 'json');
 
                //busqueda es la varible que mandaremos por post con el contenido del input
            }
        });
$('input#solicitud_servicio_medico_id').autocomplete({
 
            minLength : 1 , //le indicamos que busque a partir de haber escrito dos o mas caracteres en el input
 
            source : function( request , response ){
 
                var url = "<?php echo PUBLIC_PATH ?>proveedorsalud/medico/autocomplete";   //url donde buscará los estados
 
                $.post(url, { 'busqueda' : request.term }, response, 'json');
 
                //busqueda es la varible que mandaremos por post con el contenido del input
            }
        });
$('input#solicitud_servicio_patologia_id').autocomplete({
 
            minLength : 1 , //le indicamos que busque a partir de haber escrito dos o mas caracteres en el input
 
            source : function( request , response ){
 
                var url = "<?php echo PUBLIC_PATH ?>config/patologia/autocomplete";   //url donde buscará los estados
 
                $.post(url, { 'busqueda' : request.term }, response, 'json');
 
                //busqueda es la varible que mandaremos por post con el contenido del input
            }
        });


    });
</script>
