<?php View::notify(); ?>
<script type="text/javascript">
    $(function() {
        $('table').dwGrid({
            order_attr: '<?php echo (APP_AJAX) ? 'class="dw-ajax dw-spinner"' : ''; ?>',
            order_action: $.KumbiaPHP.publicPath+"solicitudes/solicitud_servicio/contabilizar/"
        });
    });
</script>
<div class="container-fluid dw-shell-view">
    <?php View::process($page_module, $page_title, $set_title); ?>
    <div class="btn-toolbar btn-toolbar-top">
    </div>
    <div class="dw-overflow">
        <table class="table table-bordered table-hover table-striped table-condensed table-responsive">
            <thead>
                <tr>
                    <th>NUM</th>
                    <th class="col-collapse" data-search="fecha">FECHA</th>
                    <th class="col-collapse" data-search="codigo">CODIGO</th>
                    <th class="col-collapse" data-search="titular">TITULAR</th>
                    <th class="col-collapse" data-search="beneficiario">BENEFICIARIO</th>
                    <th class="col-collapse" data-search="proveedor">PROVEEDOR</th>
                    <th class="col-collapse" data-search="servicio">SERVICIO</th>
                    <th class="col-collapse" data-search="patologia">PATOLOGIA</th>
                    <th class="col-collapse" data-search="observacion">OBSERVACION</th>
                    <th class="col-collapse" data-search="tiposolicitud">TIPO SOLICITUD</th>
                    <th class="col-collapse" data-search="estado">ESTADO</th>
                    <th class="btn-actions no-responsive" style="width: 100px;">ACCIONES</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($solicitud_servicios->items as $solicitud_servicio): ?>
                    <?php $key_upd = DwSecurity::getKey($solicitud_servicio->id, 'upd_solicitud_servicio'); ?>
                    <?php $key_del = DwSecurity::getKey($solicitud_servicio->id, 'del_solicitud_servicio'); ?>
                    <tr>
                        <td><?php echo $solicitud_servicios->counter; ?></td>
                        <td><?php echo $solicitud_servicio->fecha_solicitud; ?></td>
                        <td><?php echo $solicitud_servicio->codigo_solicitud; ?></td>
                        <td><?php echo $solicitud_servicio->nombre; echo ' '; echo $solicitud_servicio->apellido;?></td>
                        <td><?php echo $solicitud_servicio->nombre; echo ' '; echo $solicitud_servicio->apellido;?></td>
                        <td><?php echo $solicitud_servicio->proveedor; ?></td>
                        <td><?php echo $solicitud_servicio->servicio; ?></td>
                        <td><?php echo $solicitud_servicio->patologia; ?></td>
                        <td><?php echo $solicitud_servicio->observacion; ?></td>
                        <td><?php echo $solicitud_servicio->tiposolicitud; ?></td>
                        <td><?php echo ($solicitud_servicio->estado_solicitud == 'C') ? '<span class="label label-success" title="'.$solicitud_servicio->tiposolicitud.'" rel="tooltip">Contabilizada</span>' : '<span class="label label-important" title="'.$solicitud_servicio->estado_solicitud.'" rel="tooltip">Por Contabilizar</span>' ; ?>
                        </td>
                        <td>
                        <?php echo ($solicitud_servicio->estado_solicitud == 'C') ? DwHtml::buttonTable('Reversar Solicitud', "solicitudes/solicitud_servicio/modificar/$key_upd/", null, 'warning', 'repeat') : DwHtml::buttonTable('*Contabilizar Solicitud', "solicitudes/solicitud_servicio/contabilizar/$key_upd/", null, 'default', 'list'); ?>
                        </td>
                    </tr>
                    <?php $solicitud_servicios->counter++; ?>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php View::partial('paginators/default', false, array('page'=>$solicitud_servicios, 'url'=>"solicitudes/solicitud_servicio/contabilizar/$order/")); ?>
</div>
