<?php View::notify(); ?>
<div class="container-fluid dw-shell-view">
    <?php View::process($page_module, $page_title, $set_title); ?>
    <?php echo DwForm::open('', 'post', array('id'=>'form', 'class'=>'dw-validate')); ?>
    <div class="row-fluid">
       <table class="table table-bordered table-hover table-striped table-condensed table-responsive">
            <thead>
                <tr>
                    <th class="col-collapse" data-search="fecha">FECHA SOLICITUD</th>
                    <th class="col-collapse" data-search="codigo">CODIGO</th>
                    <th class="col-collapse" data-search="titular">FECHA VENCIMIENTO</th>
                    <th class="col-collapse" data-search="beneficiario">CEDULA TITULAR</th>
                    <th class="col-collapse" data-search="beneficiario">NOMBRES TITULAR</th>
                    <th class="col-collapse" data-search="proveedor">BENEFICIARIO</th>
                    <th class="col-collapse" data-search="servicio">SERVICIO</th>
                    <th class="col-collapse" data-search="observacion">PROVEEDOR</th>
                    <th class="col-collapse" data-search="beneficiario">MEDICO</th>
                    <th class="col-collapse" data-search="tiposolicitud">ORSERVACION</th>
                </tr>
            </thead>
            <tbody>
               <tr>
               <td> <?php echo $solicitud_servicio->fecha_solicitud ?></td>
                <td> <?php echo $solicitud_servicio->codigo_solicitud ?></td>
                <td> <?php echo $solicitud_servicio->fecha_vencimiento ?></td>
                <td> <?php echo $solicitud_servicio->cedula ?></td>
                <td> <?php echo $solicitud_servicio->nombre." ".$solicitud_servicio->apellido; ?></td>
                <td> <?php echo $solicitud_servicio->nombreb." ".$solicitud_servicio->apellidob; ?></td>
                <td> <?php echo $solicitud_servicio->servicio; ?></td>
                <td> <?php echo $solicitud_servicio->proveedor; ?></td>
                <td> <?php echo $solicitud_servicio->nombrem." ".$solicitud_servicio->apellidom; ?></td>
                <td> <?php echo ($solicitud_servicio->observacion); ?></td>
               </tr>
            </tbody>
        </table>
        <div class="row-fluid" > 
        <?php $combobit =""; foreach($sol as $solicitud_servicio_patologia): 
          $combobit .=" <option value='".$solicitud_servicio_patologia->id."'>".$solicitud_servicio_patologia->descripcion."</option>"; endforeach; ?>
        </div>
     <div id="page-wrap">
     <div id="header">FACTURA </div>
        <div id="customer">
            <table id="meta">
                <tr>
                    <td class="meta-head">Nro de Factura</td>
                    <td> <input type="text" id="" class="input-medium" name="nro_factura"> </td>
                </tr>
                  <tr>
                    <td class="meta-head">Nro de Control</td>
                    <td> <input type="text" id="" class="input-medium" name="nro_control"> </td>
                </tr>
                <tr>
                    <td class="meta-head">Fecha</td>
                    <td><input type="text" id="" class="input-medium" name="fecha_factura"></td>
                </tr>
                <tr>
                    <td class="meta-head">Monto Total</td>
                    <td><div class="due"></div></td>
                </tr>
            </table>
        </div>
        
        <table id="items">
          <tr>
              <th>Articulo</th>
              <th>Descripcion</th>
              <th>Costo Unitario</th>
              <th>Cantidad</th>
              <th>Precio</th>
              <th></th>
          </tr>
          
          <tr class="item-row">
              <td class="item-name"><div class="delete-wpr"> <input type="text" class="input-medium"><a class="delete" href="javascript:;" title="Remove row">X</a></div></td>
              <td class="description"> <input type="text" class="input-xlarge"></td>
              <td><input type="text" class="cost input-small"></td>
              <td><input type="text" class="qty input-small"></td>
              <td><span class="price"></span></td>
          </tr>
          <tr id="hiderow">
            <td colspan="5"><a id="addrow" href="javascript:;" title="Add a row">Agregar Articulo</a></td>
          </tr>
          <tr>
              <td colspan="2" class="blank"> </td>
              <td colspan="1" class="blank"> </td>
              <td colspan="2" class="total-line">Subtotal</td>
              <td class="total-value"><div id="subtotal"></div></td>
          </tr>
          <tr>
              <td colspan="2" class="blank"> </td>
              <td colspan="1" class="blank"> </td>
              <td colspan="2" class="total-line">Total</td>
              <td class="total-value"><div id="total"></div></td>
          </tr>
          <tr>
              <td colspan="2" class="blank"> </td>
              <td colspan="1" class="blank"> </td>
              <td colspan="2" class="total-line">Monto a cancelar</td>

              <td class="total-value"><input type="text" class="input-small" id="paid"></td>
          </tr>
        </table>
    </div>

    </div>
    <div class="row-fluid">
        <div class="form-actions">
            <?php echo DwButton::save('Siguiente'); ?>
            <?php echo DwButton::reset('form'); ?>
            <?php echo DwButton::cancel(); ?>
        </div>
    </div>
    <?php echo DwForm::close(); ?>
</div>

<script type="text/javascript">
function update_combo() {
  var combo = "<?php echo $combobit; ?>"


}



</script>

