 <?php
 // LImpia el bufer (evita los errores de: Some data has already been output ) 
ob_end_clean(); 
Load::lib('pdf_cabecera_solicitud');
$pdf=new PDF('P','mm','letter');
//Definiendo las fechas
$pdf->Open();
$pdf->AliasNbPages();
$pdf->AddPage();
$pdf->SetFont('Times','B',10);
$pdf->SetFillColor(255);
$pdf->SetTextColor(000);
$pdf->SetMargins(8,8,8,8);
//Imprimiendo las fechas
$Fecha=$fecha_sol;
    $elDia=substr($Fecha,8,2);
    $elMes=substr($Fecha,5,2);
    $elYear=substr($Fecha,0,4);
$pdf->Cell(152);
$pdf->Cell(45,6,'FECHA',1,1,'C',true);
$pdf->Cell(154);
$pdf->Cell(15,6,utf8_decode("DÍA"),1,0,'C',true);
$pdf->Cell(15,6,'MES',1,0,'C',true);
$pdf->Cell(15,6,utf8_decode("AÑO"),1,1,'C',true);
$pdf->Cell(154);
$pdf->Cell(15,6,$elDia,1,0,'C',true);
$pdf->Cell(15,6,$elMes,1,0,'C',true);
$pdf->Cell(15,6,$elYear,1,1,'C',true);
//datos del titular.
$pdf->Cell(199,6,'DATOS DEL TITULAR ',1,1,'C',true);
$pdf->Cell(80,6,'APELLIDO(S) Y NOMBRE(S)',1,0,'C',true);
$pdf->Cell(46,6,utf8_decode('CÉDULA DE IDENTIDAD'),1,0,'C',true);
$pdf->Cell(28,6,'SEXO',1,0,'C',true);
$pdf->Cell(45,6,utf8_decode('TELÉFONOS'),1,1,'C',true); 
//Variables
$pdf->SetFont('Times','',9);
$pdf->Cell(80,6,utf8_decode($nombres.' '.$apellidos),1,0,'C',true);
$pdf->Cell(46,6,$nacionalidad."-".$cedula,1,0,'C',true);
$pdf->Cell(28,6,$sexo,1,0,'C',true);//sexo
if($telefono!=''){
    $pdf->Cell(45,6,$telefono.' / '.$celular,1,1,'C',true);
}else{
    $pdf->Cell(45,6,$celular,1,1,'C',true);
}
$pdf->SetFont('Times','B',10);
$pdf->Cell(126);
$pdf->Cell(28,6,utf8_decode('UPSA/SEDE'),1,0,'C',true);
$pdf->Cell(45,6,$upsa,1,1,'C',true);//sexo


$pdf->Ln(3);
$pdf->SetFont('Times','B',10);  
$pdf->Cell(199,6,utf8_decode("DATOS DEL BENEFICIARIO"),1,1,'C',true);
$pdf->SetFont('Times','',9);
$pdf->Cell(199,6,utf8_decode('Dirección: '),1,1,'L',true);

$pdf->Cell(28,6,utf8_decode('Pais: '),1,0,'L',true);   
$pdf->Cell(34,6,utf8_decode('Estado: '),1,0,'L',true);
$pdf->Cell(63,6,utf8_decode('Parroquia: '),1,0,'L',true);
$pdf->Cell(74,6,'E-mail: '.' ',1,1,'L',true);
$pdf->SetFont('Times','B',9);

//datos de beneficiarios

$pdf->Ln(3);
$pdf->SetFont('Times','B',10);  


$pdf->Cell(199,6,'MOTIVO DE LA CONSULTA: ','C',1,'L',true);
$pdf->Cell(199,6,'','T',1,'L',true);
$pdf->Cell(199,6,'','T',1,'L',true);
$pdf->Cell(199,6,'','T',1,'L',true);


    $pdf->SetFont('Times','B',10);
    $pdf->Ln(2);
    $pdf->Cell(99,6,'TITULAR',0,0,'L',true);
    $pdf->Cell(35,6,'REGISTRADO POR:  ',0,0,'L',true);
    $pdf->SetFont('Times','',10);
    $pdf->Cell(65,6,'COORDINADOR',0,1,'L',true);
    $pdf->SetFont('Times','B',10);
    $pdf->Cell(99,6,'FIRMA Y HUELLA',0,0,'L',true);
    $pdf->Cell(100,6,'FIRMA Y SELLO',0,1,'L',true); 
    $pdf->Cell(99,6,' ','0',0,'L',true);
    $pdf->Cell(100,6,' ','0',1,'L',true);
    $pdf->Cell(100,6,' ','0',1,'L',true);
    $pdf->Cell(100,6,' ','0',1,'L',true);








$pdf->Output();

?>
