<?php View::notify(); ?>
<div class="container-fluid dw-shell-view">
    <?php View::process($page_module, $page_title, $set_title); ?>
    <?php echo DwForm::open('', 'post', array('id'=>'form', 'class'=>'dw-validate')); ?>
        <div class="row-fluid">
       <table class="table table-bordered table-hover table-striped table-condensed table-responsive">
            <thead>
                <tr>
                    <th class="col-collapse" data-search="fecha">FECHA SOLICITUD</th>
                    <th class="col-collapse" data-search="codigo">CODIGO</th>
                    <th class="col-collapse" data-search="titular">FECHA VENCIMIENTO</th>
                    <th class="col-collapse" data-search="beneficiario">CEDULA TITULAR</th>
                    <th class="col-collapse" data-search="beneficiario">NOMBRES TITULAR</th>
                    <th class="col-collapse" data-search="proveedor">BENEFICIARIO</th>
                    <th class="col-collapse" data-search="servicio">SERVICIO</th>
                    <th class="col-collapse" data-search="observacion">PROVEEDOR</th>
                    <th class="col-collapse" data-search="beneficiario">MEDICO</th>
                    <th class="col-collapse" data-search="tiposolicitud">ORSERVACION</th>
                </tr>
            </thead>
            <tbody>
               <tr>
               <td> <?php echo $solicitud_servicio->fecha_solicitud ?></td>
                <td> <?php echo $solicitud_servicio->codigo_solicitud ?></td>
                <td> <?php echo $solicitud_servicio->fecha_vencimiento ?></td>
                <td> <?php echo $solicitud_servicio->cedula ?></td>
                <td> <?php echo $solicitud_servicio->nombre." ".$solicitud_servicio->apellido; ?></td>
                <td> <?php echo $solicitud_servicio->nombreb." ".$solicitud_servicio->apellidob; ?></td>
                <td> <?php echo $solicitud_servicio->servicio; ?></td>
                <td> <?php echo $solicitud_servicio->proveedor; ?></td>
                <td> <?php echo $solicitud_servicio->nombrem." ".$solicitud_servicio->apellidom; ?></td>
                <td> <?php echo $solicitud_servicio->observacion; ?></td>
               </tr>
            </tbody>
        </table> 
         <?php  $key_upd = DwSecurity::getKey($solicitud_servicio->id, 'upd_solicitud_servicio'); ?> 
         <?php echo DwForm::hidden('solicitud_servicio.id', NULL, $key_upd); ?>
        <div class="row-fluid">
            <div class="span6">
                <?php echo DwForm::textarea('solicitud_servicio.motivo', array('class'=>'input-xxlarge mask-alphanum show-error'), NULL, 'Motivo de Consulta'); ?>
            </div>
            <div class="span6"> 
                <?php echo DwForm::textarea('solicitud_servicio.diagnostico', array('class'=>'input-xxlarge mask-alphanum show-error'), NULL, 'Diagnostico'); ?>
            </div>
        </div>
        <div class="row-fluid">
            <div class="span12">
              <input name="agregar" type="button" id="agregar" value="Agregar" title="Agregar Patologia" onclick="if(!crear(this)){return false;}" />
            </div>
            

              <input class="input-xxlarge mask-alphanum" name="solicitud_servicio.patologia" id="solicitud_servicio_patologia"  type="text" onfocus = "if(this.value=='Buscar Medicinas') {this.value=''; this.style.color='#000'}" onblur="if(this.value==''){this.value='Buscar Patologia'; this.style.color='#909090'}" />
             

             <input type="hidden" name="solicitud_servicio_patologia_id" id="solicitud_servicio_patologia_id" >
               
            <!-- DIV PARA AGREGAR LAS PATOLOGIAS CON EL METODO DE ANDRES XD -->

            <div id="ocultar" style="display:none;" class="row-fluid">
            <div id="capa_datos"></div>
            </div>

        </div>

    </div>
        <div class="row-fluid">
            <div class="form-actions">
                <?php echo DwButton::save('Siguiente'); ?>
                <?php echo DwButton::reset('form'); ?>
                <?php echo DwButton::cancel(); ?>
            </div>
        </div>
    <?php echo DwForm::close(); ?>
</div>

<script type="text/javascript" >
$(document).ready(function(){
  select: function ll(event, ui) {
            $('input#solicitud_servicio_codigo_solicitud').val(ui.item.codid);// Asignacion de Id en Campo
            // $('textarea#solicitud_servicio_observacion').val(ui.item.id);// Asignacion de Id en Campo
              }
    $('input#solicitud_servicio_patologia').autocomplete({
        minLength : 3 , //le indicamos que busque a partir de haber escrito dos o mas caracteres en el input
            source: function(request, response) {
                $.ajax({
                    url: "<?php echo PUBLIC_PATH ?>config/patologia/autocomplete",
                    data: {'busqueda':request.term},
                    dataType: "json",
                    type: "POST",
                    success: function(data){
                        response(data);
                    }
                });
            },
            select: function(event, ui) {
            $('input#solicitud_servicio_patologia_id').val(ui.item.id);// Asignacion de Id en Campo
            //$('textarea#solicitud_servicio_observacion').val(ui.item.id);// Asignacion de Id en Campo
            }
        }); 
});
</script>

<script type="text/javascript" >
//funcion para borrar los objetos creados.
function borrar(obj) {  
  field = document.getElementById('capa_datos'); 
  field.removeChild(document.getElementById(obj));    
  icremento--; 
   if(icremento==1){
      $("#ocultar").css("display", "none"); 
  }
  return true;
}


var icremento =1;
function crear(obj) {
    if(icremento>5){
        $("#capa_datos").css({                     
                "margin": "auto",
                "text-align":"center",
                "width": "auto",
                "height": "124px",      
                "padding": "2px",
                "border-radius": "4px",
                "overflow": "auto"
            })
    }

    var patologia = document.getElementById('solicitud_servicio_patologia').value;   
    var patologia_id = document.getElementById('solicitud_servicio_patologia_id').value;
//para validar que no repita el patologia en el arreglo.
   for(var i=0;i<document.getElementsByName('patologia_id[]').length;i++)
    {                               
        if (document.getElementsByName('patologia_id[]')[i].value==patologia_id){
            alert('Estas intentando agregar una patologia con caracteristicas iguales.\nVerifica los datos!');
            return false;
        }                 
    } 
      field = document.getElementById('capa_datos'); 
      contenedor = document.createElement('div'); 
      contenedor.id = 'div'+icremento; 
      field.appendChild(contenedor); 
    //patologia id
      boton = document.createElement('input'); 
      boton.type = 'hidden'; 
      boton.name = 'patologia_id'+'[]';
      boton.vAlign= "middle";
      boton.id ='patologia_id'+'[]';
      boton.value =  document.getElementById('solicitud_servicio_patologia_id').value;    
      
      contenedor.appendChild(boton); 
    //cantidad Campo de texto
      boton = document.createElement('input'); 
      boton.type = 'text'; 
      boton.name = 'patologia'+'[]';
      boton.id = 'cant';
      boton.vAlign= "middle";
      boton.value =  document.getElementById('solicitud_servicio_patologia').value;
      boton.readOnly = true;
      boton.size='4';
      boton.className ="input-xxlarge"
      contenedor.appendChild(boton); 
        //Boton de borrado 
      boton = document.createElement('input');
      boton.vAlign= "middle";

      boton.type = 'button'; 
      boton.width= '15';
      boton.height= '15';
      boton.src = "";
      boton.name = 'div'+icremento;
      boton.value = "Eliminar"
      boton.onclick = function () {borrar(this.name)} 
      contenedor.appendChild(boton); 
      icremento++;    
    $("#ocultar").css("display", "block");
    return true;    
}

</script>