<?php View::notify(); ?>

<div class="container-fluid dw-shell-view">
    
    <div class="hero-unit">
        <h1><small>Sistema Autogestionado de Salud - E.M.S. Arroz del Alba S.A.</small></h1>
        <p class="">El SAS es una Aplicación Informatica para la Gestión del Sistema Autogestionado de Salud.</p>
        <p class="">Por medio del SAS podrás gestionar de manera 
            rápida y segura las solicitudes de medicinas, ordenes medicas, reembolso y mucho más!.</p>
        <p class="dw-text-right">
            <a class="btn btn-primary btn-large" href="https://github.com/ArrozAlba/SASv2" target="_blank"><i class="icon-expand icon-github icon-2x"></i> Ver proyecto en GitHub</a>
        </p>
    </div>
        
    <div class="row-fluid">
        <div class="span4">
            <h4><i class="icon-expand icon-fullscreen icon-2x"></i> 100% Responsivo</h4>
            Basado en Bootstrap de Twitter, provee un diseño adaptado a todo tipo de pantalla.
        </div>
        <div class="span4">
            <h4><i class="icon-expand icon-ok icon-2x"></i> 100% Customizable</h4>
            Puedes personalizar el backend con temas, apariencias y variables de configuración
        </div>
        <div class="span4">
            <h4><i class="icon-expand icon-group icon-2x"></i> 100% OpenSource</h4>
            El SAS está licenciado bajo la GPLv2, lo cual te provee de toda una libertad a nivel de programación
        </div>
    </div>
    
    <div class="row-fluid">
        <div class="span4">
            <h4><i class="icon-expand icon-cogs icon-2x"></i> Arquitectura MVC</h4>
            Realizado bajo el patrón de diseño MVC y construido con la solidez de KumbiaPHP
        </div>
        <div class="span4">
            <h4><i class="icon-expand icon-magic icon-2x"></i> RICH App </h4>
            El SAS está construido para ser utilizado en su totalidad con AJAX, aunque si lo prefieres, también responde a peticiones normales
        </div>
        <div class="span4">
            <h4><i class="icon-expand icon-asterisk icon-2x"></i> Características</h4>
            <ul>
                <li>Rápido escalado</li>
                <li>Diseño orientado al usuario final</li>
                <li>Rápido, sencillo y estable gracias al poder de KumbiaPHP</li>
                <li>Control de auditorías y sucesos del sistema</li>
            </ul>
        </div>
    </div>              
    
</div>
