<?php View::notify(); ?>
<style type="text/css">
    .tab-pane { min-height: 200px;}
</style>

<div class="container-fluid dw-shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <?php echo DwForm::open('', 'post', array('id'=>'form', 'class'=>'dw-validate')); ?>

     <?php if(DESKTOP) { ?>
        <ul class="nav nav-tabs">
        <?php } else { ?>
        <ul class="nav nav-pills nav-stacked">
        <?php } ?>
            <li class="active"><a href="#tab1" data-toggle="tab">Información personal</a></li>
        </ul>
        <div class="tab-content">

            <div class="tab-pane active" id="tab1">

                <div class="row-fluid">
                    <div class="span6">
                        <?php echo DwForm::text('usuario.login', array('class'=>'input-xxlarge input-required mask-alphanum show-error input-user'), NULL, 'Usuario'); ?>
                    </div>
                    <div class="span6">
                        <?php echo DwForm::dbSelect('usuario.perfil_id', 'perfil', array('sistema/perfil', 'getListadoPerfil', Perfil::ACTIVO), NULL, array('class'=>'input-xxlarge input-required input-list show-errors'), NULL, 'Perfil'); ?>
                    </div>
                </div>

                <div class="row-fluid">
                    <?php if(APP_OFFICE) { ?>
                    <div class="span6">
                        <?php echo DwForm::dbSelect('usuario.sucursal_id', array('sucursal', 'parroquia'), array('config/sucursal', 'getListadoSucursal'), array('todas'=>'Todas'), array('class'=>'input-xxlarge input-required mask-pint show-errors'), NULL, 'Sucursal / UPSA'); ?>
                    </div>
                    <?php } ?>
                    <div class="span6">
                        <?php echo DwForm::email('usuario.email', array('class'=>'input-xxlarge mask-email show-error'), NULL, 'Email'); ?>
                    </div>
                </div>
                <div class="row-fluid">
                    <div class="span6">
                        <?php echo DwForm::number('usuario.datagrid', array('class'=>'input-numeric show-error input-required'), 30, 'Cantidad de datos por página', 'Esta información se utiliza en los listados de informaciones y reportes'); ?>
                    </div>
                </div>

                <div class="row-fluid">
                    <div class="span6">
                        <?php echo DwForm::pass('usuario_clave.password', array('class'=>'input-xxlarge input-required input-pass show-error'), '', 'Contraseña'); ?>
                    </div>
                    <div class="span6">
                        <?php echo DwForm::pass('repassword', array('class'=>'input-xxlarge input-required input-repass show-error'), '', 'Confirmación'); ?>
                    </div>

                </div>
                <div class="row-fluid">
                    <input type="text" value="<?= $usuario->id ?>" > 

                    <?php $key_upd = DwSecurity::getKey($usuario->id, 'upd_usuario'); ?>
                    
                    <?php //echo DwForm::hidden('usuario.titular_id', NULL, NULL); ?>

                    <div class="form-actions">
                        <?php echo DwButton::save('Guardar usuario'); ?>
                        <?php echo DwButton::reset('form'); ?>
                        <?php echo DwButton::cancel('sistema/usuario/listar/'); ?>
                    </div>

                </div>
            </div>
                
        </div>
  <?php echo DwForm::close(); ?>
</div>