<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset='<?php echo APP_CHARSET ?>' />
        <title><?php echo Config::get('config.application.name') ?></title>
        <?php
        Tag::css('backend/bootstrap');
        Tag::css('backend/estilos');
        echo Html::includeCss();
        echo Tag::js('jquery/jquery.min');
        echo Tag::js('jquery/jquery.kumbiaphp');
        echo Tag::js('bootstrap/bootstrap');
        echo Tag::js('global');
        ?>
    </head>
    <body>
        <?php View::partial('backend/cabecera_app') ?>
        <div class="container">
            <div id="contenido" class="content">
                <b>ERROR 404</b> pagina no encontrada
            </div>
            <?php View::partial('backend/pie') ?>
        </div>
    </body>
</html>