<?php View::notify(); ?>
<style type="text/css">
    .tab-pane { min-height: 200px;}
</style>

<div class="container-fluid dw-shell-view">
    <?php View::process($page_module, $page_title, $set_title); ?>
    <?php echo DwForm::openMultipart('', array('class'=>'dw-validate')); ?>
        <?php if(DESKTOP) { ?>
        <ul class="nav nav-tabs">
        <?php } else { ?>
        <ul class="nav nav-pills nav-stacked">
        <?php } ?>
            <li class="active"><a href="#tab1" data-toggle="tab">Información general</a></li>
            <li><a href="#tab3" data-toggle="tab">Cargar logo</a></li>
        </ul>
        <div class="tab-content">
            <div class="tab-pane active" id="tab1">
                <div class="row-fluid">
                    <div class="span6">
                        <?php echo DwForm::text('empresa.razon_social', array('class'=>'input-xxlarge input-required show-error data-toggle="tooltip" title="Ingrese razón social de la empresa'), NULL, 'Razón social'); ?>
                    </div>
                    <div class="span6">
                        <?php echo DwForm::text('empresa.rif', array('class'=>'input-xxlarge input-required mask-alphanum show-error data-toggle="tooltip" title="Ingrese Rif de la empresa"'), NULL, 'RIF'); ?>
					</div>
                </div>
                <div class="row-fluid">
                    <div class="span6">
                        <?php echo DwForm::text('empresa.representante_legal', array('class'=>'input-xxlarge input-required mask-alpha show-error data-toggle="tooltip" title="Ingrese representante legal de la empresa"'), NULL, 'Representante legal'); ?>
                    </div>
                    <div class="span6">
                        <?php echo DwForm::tel('empresa.telefono', array('class'=>'input-xxlarge input-required show-error data-toggle="tooltip" title="Ingrese telefono de la empresa"'), NULL, 'Telefono'); ?>
                    </div>
                </div>
                <div class="row-fluid">
                    <div class="span6"> 
                        <?php echo DwForm::tel('sucursal.celular', array('class'=>'input-numeric input-xxlarge mask-pint show-error data-toggle="tooltip" title="Ingrese celular de la sucursal"'), NULL, 'Celular'); ?>
                    </div>
                    <div class="span6">
                        <?php echo DwForm::tel('empresa.fax', array('class'=>'input-xxlarge show-error data-toggle="tooltip" title="ingrese fax de la empresa"'), NULL, 'Fax'); ?>
                    </div>
                </div>
                <div class="row-fluid">
                    <div class="span6">
                            <?php echo DwForm::dbSelect('empresa.pais_id', 'nombre', array('params/pais', 'getListadoPais'), NULL, array('class'=>'input-xxlarge input-required mask-pint show-errors'), $empresa->pais_id, 'País'); ?>
                    </div>
                    <div class="span6">
                        <div id='div_estado'><?php echo DwForm::dbSelect('empresa.estado_id', 'nombre', array('params/estado', 'getListadoEstado'), $empresa->estado_id, array('class'=>'input-xxlarge input-required mask-pint show-errors'), NULL, 'Estado'); ?></div>
                     </div>
                </div>
                <div class="row-fluid">
                    <div class="span6">
                        <div id='div_municipio'><?php echo DwForm::dbSelect('empresa.municipio_id', 'nombre', array('params/municipio', 'getListadoMunicipio'), $empresa->municipio_id, array('class'=>'input-xxlarge input-required mask-pint show-errors'), NULL, 'Municipio'); ?></div>
                    </div>
                    <div class="span6">
                        <div id='div_parroquia'><?php echo DwForm::dbSelect('empresa.parroquia_id', 'nombre', array('params/parroquia', 'getListadoParroquia'), $empresa->parroquia_id, array('class'=>'input-xxlarge input-required mask-pint show-errors'), NULL, 'Parroquia'); ?></div>
                    </div>
                </div>
                <div class="row-fluid">
                    <div class="span6">
                        <?php echo DwForm::email('empresa.email', array('class'=>'input-xxlarge input-required mask-email show-error data-toggle="tooltip" title="Ingrese Email de la empresa"'), NULL, 'Email'); ?>
                    </div>
                    <div class="span6">
                        <?php echo DwForm::tel('empresa.pagina_web', array('class'=>'input-xxlarge input-required show-error data-toggle="tooltip" title="Ingrese pagina web de la empresa"'), NULL, 'Pagina Web'); ?>
                    </div>
                </div>
                <div class="row-fluid">
                    <div class="span12">
                        <?php echo DwForm::text('sucursal.direccion', array('class'=>'input-xxlarge input-required input-alphanum mask-alphanum show-error data-toggle="tooltip" title="Ingrese direccion de la sucursal"'), NULL, 'Dirección'); ?>
                    </div>
                 </div>
            </div>

                    <?php if(!empty($sucursal->id)) { ?>
                    <?php echo DwForm::hidden('sucursal.id', NULL, $sucursal->id); ?>
                    <?php } ?>
            <div class="tab-pane" id="tab3">

                <div class="row fileupload-buttonbar">

                    <div class="span2">
                        <span class="btn btn-success fileinput-button">
                            <i class="icon-plus icon-white"></i>
                            <span>Cargar logo...</span>
                            <input id="logo" type="file" name="logo">
                        </span>
                    </div>

                    <div id="upload-progress" class="span4 fileupload-progress fade">
                        <div class="progress progress-success progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100">
                            <div class="bar" style="width:0%;"></div>
                        </div>
                    </div>

                    <div class="span5 dw-text-right">
                        <div class="span5 dw-picture-profile dw-text-center dw-text-middle dw-shadow-dark" style="margin-top: 5px">
                            <?php echo DwHtml::img('upload/empresa/'.$empresa->logo, $empresa->razon_social, array('id'=>'img-empresa')); ?>
                        </div>
                    </div>

                </div>

            </div>

            <div class="row-fluid">

                <?php echo DwForm::hiddenKey('empresa.id', $empresa->id); ?>
                <?php echo DwForm::hidden('empresa.logo', NULL, $empresa->logo); ?>

                <div class="form-actions">
                    <?php echo DwButton::save('Guardar información'); ?>
                    <?php echo DwButton::reset('form'); ?>
                    <?php echo DwButton::cancel(); ?>
                </div>
            </div>

        </div>

    <?php echo DwForm::close(); ?>

</div>
<?php View::partial('jquery.file-upload'); ?>

<!-- Script para obtener por Ajax Los Estados en funcion de los paises  -->
<script type='text/javascript'>
$("#empresa_pais_id").click(function(){
    var pais_id     =   $('#empresa_pais_id').val();
        $.ajax({
          type: "POST",
          url: "<?php echo PUBLIC_PATH . 'config/empresa/getEstadoPais/'; ?>",
          data: "pais_id=" + pais_id,
          success: function(html){
            $("#div_estado").html(html);
          }
        });
});
</script>


<script type="text/javascript">
    $('#logo').fileupload({
        url: '<?php echo PUBLIC_PATH; ?>config/empresa/upload/',
        dataType: 'json',
        maxFileSize: 2000000, //2MB
        acceptFileTypes: /(\.|\/)(gif|jpe?g|png)$/i,
        start: function() {
            $("#dw-message").empty();
            $('#upload-progress').removeClass('fade');
            $('.bar').parent().removeClass('progress-danger').addClass('progress-success');
            $('[type=submit]').attr('disabled', 'disabled');
        },
        progress: function (e, data) {
            var progress = parseInt(data.loaded / data.total * 100, 10);
            $('.bar').css('width',progress + '%');
        },
        add: function (e, data) {
            var jqXHR = data.submit()
            .done(function (result, textStatus, jqXHR) {
                if(textStatus!='success' || result.error!=null) {
                    $('.bar').parent().removeClass('progress-success').addClass('progress-danger');
                    DwMessage('Oops! el archivo no se ha podido cargar. <br />Detalle del error: '+(result.error!=null) ? result.error : textStatus);
                } else {
                    DwMessage('El archivo se ha cargado correctamente!', 'success');
                    $("#empresa_logo").val(result.name);
                    $("#img-empresa").attr('src', '<?php echo PUBLIC_PATH; ?>img/upload/empresa/'+result.name);
                }
            })
            .fail(function (jqXHR, textStatus, errorThrown) {
                if(textStatus!=null){
                    DwMessage('Oops! el archivo no se ha podido cargar. <br />Detalle del error: '+textStatus);
                    $('.bar').parent().removeClass('progress-success').addClass('progress-danger');
                    setTimeout(function() { $('#upload-progress').addClass('fade'); }, 1000);
                } else {
                    DwMessage('Oops! al parecer el archivo no es una imágen válida. <br />Intenta con otro archivo.');
                    $('.bar').parent().removeClass('progress-success').addClass('progress-danger');
                    $('#upload-progress').addClass('fade');
                }
            })
            .always(function () {
                setTimeout(function() { $('#upload-progress').addClass('fade'); $('.bar').css('width','0%'); }, 1000);
                $('[type=submit]').removeAttr('disabled');
            });
        }
    });
</script>
