<?php View::notify(); ?>

<div class="container-fluid dw-shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <?php echo DwForm::open('', 'post', array('id'=>'form', 'class'=>'dw-validate')); ?>

        <div class="row-fluid">
            <div class="span6">
                <?php echo DwForm::select('medico.nacionalidad', array(''=>'Seleccione:','V'=>'Venezolana', 'E'=>'Extranjera'), array('class'=>'input-xxlarge input-required show-error data-toggle="tooltip" title="Seleccione la nacionalidad del médico"'), NULL, 'Nacionalidad:'); ?>
            </div>
             <div class="span6">
                <?php echo DwForm::text('medico.cedula', array('class'=>'input-xxlarge input-required show-error data-toggle="tooltip" title="Ingrese el número de cédula del médico"'), NULL, 'Cédula:'); ?>
            </div>
        </div>

        <div class="row-fluid">
            <div class="span6">
                <?php echo DwForm::text('medico.rmpps', array('class'=>'input-xxlarge input-required show-error data-toggle="tooltip" title="Ingrese el número de registro del médico en el Ministerio del Poder Popular para la Salud"'), NULL, 'RMPPS:'); ?>
            </div>
            <div class="span6">
                <?php echo DwForm::text('medico.rif', array('class'=>'input-xxlarge input-required show-error data-toggle="tooltip" title="Ingrese el número de RIF del médico"'), NULL, 'RIF:'); ?>
            </div>
        </div>
        <div class="row-fluid">
            <div class="span6">
                <?php echo DwForm::text('medico.nombre1', array('class'=>'input-xxlarge input-required show-error data-toggle="tooltip" title="Ingrese el primer nombre del médico"'), NULL, 'Primer Nombre:'); ?>
            </div>
            <div class="span6">
                <?php echo DwForm::text('medico.nombre2', array('class'=>'input-xxlarge show-error data-toggle="tooltip" title="Ingrese el segundo nombre del médico"'), NULL, 'Segundo Nombre:'); ?>
            </div>
        </div>
        <div class="row-fluid">
            <div class="span6">
                <?php echo DwForm::text('medico.apellido1', array('class'=>'input-xxlarge input-required show-error data-toggle="tooltip" title="Ingrese el primer apellido del médico"'), NULL, 'Primer Apellido:'); ?>
            </div>
            <div class="span6">
                <?php echo DwForm::text('medico.apellido2', array('class'=>'input-xxlarge show-error data-toggle="tooltip" title="Ingrese el segundo apellido del médico"'), NULL, 'Segundo Apellido:'); ?>
            </div>
        </div>
        <div class="row-fluid">
            <div class="span6">
                <?php echo DwForm::text('medico.telefono', array('class'=>'input-xxlarge input-required show-error data-toggle="tooltip" title="Ingrese el número de teléfono fijo del médico"'), NULL, 'Teléfono Fijo:'); ?>
            </div>
            <div class="span6">
                <?php echo DwForm::text('medico.celular', array('class'=>'input-xxlarge show-error data-toggle="tooltip" title="Ingrese el número de teléfono móvil del médico"'), NULL, 'Teléfono Móvil:'); ?>
            </div>
        </div>

        <div class="row-fluid">
            <div class="span6">
                <?php echo DwForm::select('medico.sexo', array(''=>'Seleccione:', 'M'=>'Masculino', 'F'=>'Femenino'), array('class'=>'input-xxlarge input-required show-error data-toggle="tooltip" title="Seleccione el sexo del médico"'), NULL, 'Sexo:'); ?>
            </div>
             
            <div class="span6">
                <?php echo DwForm::email('medico.correo_electronico', array('class'=>'input-xxlarge show-error data-toggle="tooltip" title="Ingrese la dirección de corre electrónico del médico"'), NULL, 'Correo Electrónico:'); ?>
            </div>
        </div>
        <div class="row-fluid">
            <div class="span6">
                <?php echo DwForm::textarea('medico.observacion', array('class'=>'input-xxlarge show-error data-toggle="tooltip" title="Ingrese observación acerca del médico"'), NULL, 'Observación:'); ?>
            </div>
        </div>
        <div class="row-fluid">
            <div class="form-actions">
                <?php echo DwButton::save('Guardar Médico'); ?>
                <?php echo DwButton::reset('form'); ?>
                <?php echo DwButton::cancel(); ?>
            </div>
        </div>

    <?php echo DwForm::close(); ?>

</div>
