<?php View::notify(); ?>

<div class="container-fluid dw-shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <?php echo DwForm::open('', 'post', array('id'=>'form', 'class'=>'dw-validate')); ?>

        <div class="row-fluid">
            <div class="span6">
                <?php echo DwForm::select('medico.nacionalidad', array(''=>'Seleccione:','V'=>'Venezolana', 'E'=>'Extranjera'), array('class'=>'input-xxlarge input-required show-error'), $medico->nacionalidad, 'Nacionalidad:'); ?>
            </div>
             <div class="span6">
                <?php echo DwForm::text('medico.cedula', array('class'=>'input-xxlarge input-required show-error'), $medico->cedula, 'Cédula'); ?>
            </div>
        </div>

        <div class="row-fluid">
            <div class="span6">
                <?php echo DwForm::text('medico.rmpps', array('class'=>'input-xxlarge input-required show-error'), $medico->rmpps, 'RMPPS'); ?>
            </div>
            <div class="span6">
                <?php echo DwForm::text('medico.rif', array('class'=>'input-xxlarge input-required show-error'), $medico->rif, 'RIF'); ?>
            </div>
        </div>
        <div class="row-fluid">
            <div class="span6">
                <?php echo DwForm::text('medico.nombre1', array('class'=>'input-xxlarge input-required show-error'), $medico->nombre1, 'Primer Nombre'); ?>
            </div>
            <div class="span6">
                <?php echo DwForm::text('medico.nombre2', array('class'=>'input-xxlarge show-error'), $medico->nombre2, 'Segundo Nombre'); ?>
            </div>
        </div>
        <div class="row-fluid">
            <div class="span6">
                <?php echo DwForm::text('medico.apellido1', array('class'=>'input-xxlarge input-required show-error'), $medico->apellido1, 'Primer Apellido'); ?>
            </div>
            <div class="span6">
                <?php echo DwForm::text('medico.apellido2', array('class'=>'input-xxlarge show-error'), $medico->apellido2, 'Segundo Apellido'); ?>
            </div>
        </div>
        <div class="row-fluid">
            <div class="span6">
                <?php echo DwForm::text('medico.telefono', array('class'=>'input-xxlarge input-required show-error'), $medico->telefono, 'Telefono'); ?>
            </div>
            <div class="span6">
                <?php echo DwForm::text('medico.celular', array('class'=>'input-xxlarge show-error'), $medico->celular, 'Celular'); ?>
            </div>
        </div>

        <div class="row-fluid">
            <div class="span6">
                <?php echo DwForm::select('medico.sexo', array(''=>'Seleccione:', 'M'=>'Masculino', 'F'=>'Femenino'), array('class'=>'input-xxlarge input-required show-error'), $medico->sexo, 'Sexo:'); ?>
            </div>
             
            <div class="span6">
                <?php echo DwForm::email('medico.correo_electronico', array('class'=>'input-xxlarge show-error'), $medico->correo_electronico, 'Correo Electronico'); ?>
            </div>
        </div>
        <div class="row-fluid">
            <div class="span6">
                <?php echo DwForm::textarea('medico.observacion', array('class'=>'input-xxlarge show-error'), $medico->observacion, 'Observación'); ?>
            </div>
        </div>
            <?php echo DwForm::hiddenKey('medico.id', $medico->id); ?>
        </div>

        <div class="row-fluid">
            <div class="form-actions">
                <?php echo DwButton::save('Guardar Observación'); ?>
                <?php echo DwButton::reset('form'); ?>
                <?php echo DwButton::cancel(); ?>
            </div>
        </div>

    <?php echo DwForm::close(); ?>

</div>