<div class="page-header">
    <h1>
        Edición del Usuario
        <small><?php eh(strtoupper($usuario->login)) ?></small>
    </h1>
</div>
<div class="row">
    <div class="span3">
        <?php View::partial('backend/menus/usuarios') ?>
    </div>
    <div class="span8 span-derecho">
        <div id="res-form-ajax"><?php View::content() ?></div>
        <?php echo Ajax::form('res-form-ajax', NULL, 'form-horizontal') ?>
        <?php //echo Form::open(NULL, 'post', 'class="form-horizontal"') ?>
        <?php echo Form::hidden('usuario.id') ?>
        <div class="control-group">
            <label class="control-label" for="usuario_roles_id">Roles del Usuario* : </label><br/><br/>
            <div class="controls">
                <?php //echo Form::dbSelect('usuario.roles_id', 'rol','') ?>
                <ul>
                    <?php foreach ($roles as $e): ?>
                        <li><?php echo Form::check("rolesUser.$e->id", $e->id), ' ', h($e->rol) ?></li>
                    <?php endforeach; ?>
                    </ul>
                </div>
            </div>
            <div class="control-group">
                <label class="control-label" for="usuario_activo">Activo : </label>
                <div class="controls">
                <?php echo Form::select('usuario.activo', array('1' => 'Si', '0' => 'No')) ?>
                    </div>
                </div>
                <div class="form-actions">
            <?php echo Form::submit('Guardar Datos', 'class="btn btn-primary"') ?>
            <?php echo Html::linkAction('', 'Cancelar', 'class="btn"') ?>
                    </div>
        <?php echo Form::close() ?>
    </div>
</div>