<?php View::notify(); ?>
<style type="text/css">
    .tab-pane { min-height: 200px;}
</style>

<div class="container-fluid dw-shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <?php echo DwForm::open('', 'post', array('id'=>'form', 'class'=>'dw-validate')); ?>

     <?php if(DESKTOP) { ?>
        <ul class="nav nav-tabs">
        <?php } else { ?>
        <ul class="nav nav-pills nav-stacked">
        <?php } ?>
            <li class="active"><a href="#tab1" data-toggle="tab">Beneficiarios de {Nombre del titular} </a></li>
            <li><a href="#tab2" data-toggle="tab">Agregar beneficiario </a></li>
            <li><a href="#tab3" data-toggle="tab">Cargar Archivos</a></li>
        </ul>
        <div class="tab-content">
           <div class="tab-pane active" id="tab1">
            <div class="dw-overflow" id="data-result">
                <table class="table table-bordered table-hover table-striped table-condensed table-responsive">
                    <thead>
                        <tr>
                            <th>NUM</th>
                            <th class="col-collapse" data-search="cedula">CEDULA</th>
                            <th class="col-collapse" data-search="nombre1">NOMBRES</th>
                            <th class="col-collapse" data-search="apellido1">APELLIDOS</th>
                            <th class="col-collapse" data-search="titular">TIPO BENFICIARIO</th>
                            <th class="col-collapse" data-search="titular">SEXO</th>
                            <th class="col-collapse" data-search="parentesco">PARENTESCO</th>
                            <th class="btn-actions no-responsive" style="width: 150px;">PARTICIPACION</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        $counter=1;
                         foreach($bene as $bn): ?>
                            <tr>
                                <td><?php echo $counter; ?></td>
                                <td><?php echo $bn->cedula; ?></td>
                                <td><?php echo $bn->nombre1." ".$bn->nombre2; ?></td>
                                <td><?php echo $bn->apellido1." ".$bn->apellido2;?></td>
                                <td><?php echo strtoupper($bn->descripcion); ?></td>
                                <td><?php switch ($bn->sexo){
                                            case 'F':
                                                echo "FEMENINO";
                                                break;
                                            case 'M':
                                                echo "MASCULINO";
                                                break;
                                    }?></td>
                                <td><?php switch ($bn->parentesco){ //ES MEJORABLE ESTA PARTE DEL CODIGO PERO TENGO SUEÑO Y ES LO QUE SE ME OCURRIO PA RESOLVER
                                    case 'P':
                                        echo "PADRE";
                                        break;
                                    case 'M':
                                        echo "MADRE";
                                        break;
                                    case 'H':
                                        echo "HIJO";
                                        break;
                                    case 'HA':
                                        echo "HERMANA";
                                        break;
                                    case 'HO':
                                        echo "HERMANO";
                                        break;
                                    case 'TA':
                                        echo "TIA";
                                        break;
                                    case 'TO':
                                        echo "TIO";
                                        break;
                                    case 'O':
                                        echo "OTRO";
                                        break;
                                    case 'EA':
                                        echo "ESPOSA";
                                        break;
                                    case 'EO':
                                        echo "ESPOSO";
                                        break;
                                    case 'C':
                                        echo "CONCUBINO";
                                        break;
                               }
                                ?></td>
                                <td><?php echo $bn->participacion."%"; ?></td>
                            </tr>
                             <?php $counter++; ?>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>

            <div class="form-actions">
                        <?php echo DwButton::cancel('beneficiarios/titular/listar/'); ?>
                    </div>
            </div><!--Cierre tab1-->
            <div class="tab-pane" id="tab2">

             <?php echo DwForm::hidden('beneficiario.titular_id', NULL, $idtitular); ?>
                <div class="row-fluid">
                    <div class="span4">
                        <?php echo DwForm::dbSelect('beneficiario.beneficiario_tipo_id', 'descripcion', array('config/beneficiario_tipo', 'getListadoTipobeneficiario'), NULL, array('class'=>'input-xlarge input-required show-errors'), NULL, 'Tipo Beneficiario'); ?>
                    </div>
                     <div class="span4">
                        <?php echo DwForm::select('beneficiario.parentesco', array(''=>'Seleccione:', 'P'=>'Padre', 'M'=>'Madre', 'H'=>'Hijo','EO'=>'Esposo', 'EA'=>'Esposa', 'HA'=>'Hermana', 'HO'=>'Hermano', 'TA'=>'Tia', 'TO'=>'Tio', 'C'=>'Concubino', 'O'=>'Otro'), array('class'=>'input-xlarge input-required show-error'), NULL, 'Parentesco'); ?>
                    </div>
                    <div class="span4">
                        <?php echo DwForm::select('persona.sexo', array(''=>'Seleccione:','M'=>'Masculino', 'F'=>'Femenino'), array('class'=>'input-xlarge input-required show-error'), NULL, 'Sexo:'); ?>
                    </div>

                </div>
                <div class="row-fluid">
                    <div class="span3">
                        <?php echo DwForm::select('persona.nacionalidad', array(''=>'Seleccione:','V'=>'Venezolana', 'E'=>'Extranjera'), array('class'=>'input-xlarge input-required show-error'), NULL, 'Nacionalidad:'); ?>
                    </div>
                    <div class="span3">
                        <?php echo DwForm::text('persona.cedula', array('class'=>'input-xlarge mask-pint input-numeric input-required show-error'), NULL, 'Cedula de Identidad'); ?>
                    </div>
                    <div class="span3">
                        <?php echo DwForm::select('persona.estado_civil', array(''=>'Seleccione:', 'S'=>'Soltero', 'c'=>'Concubinato','C'=>'Casado', 'D'=>'Divorciado', 'V'=>'Viudo'), array('class'=>'input-xlarge input-required show-error'), NULL, 'Estado Civil'); ?>
                    </div>
                    <div class="span3">
                        <?php echo DwForm::date('persona.fecha_nacimiento', array('class'=>'input-large input-required mask-date input-date show-errors'), date("Y-m-d"), 'Fecha de Nacimiento'); ?>
                    </div>
                </div>
                <div class="row-fluid">
                    <div class="span3">
                        <?php echo DwForm::text('persona.nombre1', array('class'=>'input-xlarge input-required show-error'), NULL, 'Primer Nombre'); ?>
                    </div>
                    <div class="span3">
                        <?php echo DwForm::text('persona.nombre2', array('class'=>'input-xlarge  mask-alphanum show-error'), NULL, 'Segundo Nombre'); ?>
                    </div>
                    <div class="span3">
                        <?php echo DwForm::text('persona.apellido1', array('class'=>'input-xlarge input-required show-error'), NULL, 'Primer Apellido'); ?>
                    </div>
                    <div class="span3">
                        <?php echo DwForm::text('persona.apellido2', array('class'=>'input-xlarge mask-alphanum show-error'), NULL, 'Segundo Apellido'); ?>
                    </div>
                </div>
                <div class="row-fluid">
                    <div class="span3">
                        <?php echo DwForm::tel('beneficiario.participacion', array('class'=>'input-xlarge input-numeric input-required mask-pint show-error'), NULL, 'Participación'); ?>
                    </div>
                    <div class="span3">
                        <?php echo DwForm::text('persona.grupo_sanguineo', array('class'=>'input-xlarge mask-alphanum show-error'), NULL, 'Grupo Sanguineo'); ?>
                    </div>
                    <div class="span3">
                        <?php echo DwForm::tel('persona.celular', array('class'=>'input-xlarge input-numeric mask-pint show-error'), NULL, 'Celular'); ?>
                    </div>
                    <div class="span3">
                        <?php echo DwForm::tel('persona.telefono', array('class'=>'input-xlarge input-numeric mask-pint show-error'), NULL, 'Teléfono'); ?>
                    </div>
                </div>
                <div class="row-fluid">

                </div>


             <div class="row-fluid">
                <?php echo DwForm::hidden('persona.fotografia', NULL, 'default.png'); ?>
                    <div class="form-actions">
                        <?php echo DwButton::save('Guardar beneficiario'); ?>
                        <?php echo DwButton::reset('form'); ?>
                        <?php echo DwButton::cancel('beneficiarios/beneficiario/listar/'); ?>
                    </div>
            </div>
            

    <?php echo DwForm::close(); ?>

            </div><!--Cierre del tab2-->

            <div class="tab-pane" id="tab3">

            <div class="row fileupload-buttonbar">
                <!-- ########################### FOTOGRAQFIA ############################## -->
                    <div class="span2">
                        <span class="btn btn-success fileinput-button">
                            <i class="icon-plus icon-white"></i>
                            <span>Seleccione Fotografía...</span>
                            <input id="fotografia" type="file" name="fotografia" class="input-large">
                        </span>
                    </div>

                    <div id="upload-progress" class="span1 fileupload-progress fade">
                        <div class="progress progress-success progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100">
                            <div class="bar" style="width:0%;"></div>
                        </div>
                    </div>

                    <div class="span3 dw-text-right">
                        <div class="span2 dw-picture-profile dw-text-center dw-text-middle dw-shadow-dark" style="margin-top: 5px">
                            <?php echo DwHtml::img('upload/personas/default.png', 'Imágen de muestra', array('id'=>'img-persona')); ?>
                        </div>
                    </div>


                   <!-- ########################### Cedula ############################## -->
                    <div class="span2">
                        <span class="btn btn-success fileinput-button">
                            <i class="icon-plus icon-white"></i>
                            <span>Seleccione Cédula...</span>
                            <input id="cedula" type="file" name="cedula" class="input-large">
                        </span>
                    </div>

                    <div id="upload-progress" class="span1 fileupload-progress fade">
                        <div class="progress progress-success progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100">
                            <div class="bar" style="width:0%;"></div>
                        </div>
                    </div>

                    <div class="span3 dw-text-right">
                        <div class="span2 dw-picture-profile dw-text-center dw-text-middle dw-shadow-dark" style="margin-top: 5px">
                            <?php echo DwHtml::img('upload/personas/default.png', 'Imágen de muestra', array('id'=>'img-persona')); ?>
                        </div>
                    </div>

                </div>


                <div class="row fileupload-buttonbar">
                <!-- ########################### Carnet ############################## -->
                    <div class="span2">
                        <span class="btn btn-success fileinput-button">
                            <i class="icon-plus icon-white"></i>
                            <span>Seleccione Carnet...</span>
                            <input id="carnet" type="file" name="carnet" class="input-large">
                        </span>
                    </div>

                    <div id="upload-progress" class="span1 fileupload-progress fade">
                        <div class="progress progress-success progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100">
                            <div class="bar" style="width:0%;"></div>
                        </div>
                    </div>

                    <div class="span3 dw-text-right">
                        <div class="span2 dw-picture-profile dw-text-center dw-text-middle dw-shadow-dark" style="margin-top: 5px">
                            <?php echo DwHtml::img('upload/personas/default.png', 'Imágen de muestra', array('id'=>'img-persona')); ?>
                        </div>
                    </div>
                <!-- ########################### Acta de matrimonio ############################## -->
                    <div class="span2">
                        <span class="btn btn-success fileinput-button">
                            <i class="icon-plus icon-white"></i>
                            <span>Acta de Matrimonio...</span>
                            <input id="actamatrimonio" type="file" name="actamatrimonio" class="input-large">
                        </span>
                    </div>

                    <div id="upload-progress" class="span1 fileupload-progress fade">
                        <div class="progress progress-success progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100">
                            <div class="bar" style="width:0%;"></div>
                        </div>
                    </div>

                    <div class="span3 dw-text-right">
                        <div class="span2 dw-picture-profile dw-text-center dw-text-middle dw-shadow-dark" style="margin-top: 5px">
                            <?php echo DwHtml::img('upload/personas/default.png', 'Imágen de muestra', array('id'=>'img-persona')); ?>
                        </div>
                    </div>
                </div>

                <!-- ########################### Partida de Nacimiento ############################## -->
                <div class="row fileupload-buttonbar">

                    <div class="span2">
                        <span class="btn btn-success fileinput-button">
                            <i class="icon-plus icon-white"></i>
                            <span>Partida de Nacimiento...</span>
                            <input id="partidanacimiento" type="file" name="partidanacimiento" class="input-large">
                        </span>
                    </div>

                    <div id="upload-progress" class="span1 fileupload-progress fade">
                        <div class="progress progress-success progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100">
                            <div class="bar" style="width:0%;"></div>
                        </div>
                    </div>

                    <div class="span3 dw-text-right">
                        <div class="span2 dw-picture-profile dw-text-center dw-text-middle dw-shadow-dark" style="margin-top: 5px">
                            <?php echo DwHtml::img('upload/personas/default.png', 'Imágen de muestra', array('id'=>'img-persona')); ?>
                        </div>
                    </div>
                </div>

              

            </div>
        </div>
</div>

<?php View::partial('jquery.file-upload'); ?>

<script type="text/javascript">
    $('#fotografia').fileupload({
        url: '<?php echo PUBLIC_PATH; ?>sistema/usuario/upload/',
        dataType: 'json',
        maxFileSize: 2000000, //2MB
        acceptFileTypes: /(\.|\/)(gif|jpe?g|png)$/i,
        start: function() {
            $("#dw-message").empty();
            $('#upload-progress').removeClass('fade');
            $('.bar').parent().removeClass('progress-danger').addClass('progress-success');
            $('[type=submit]').attr('disabled', 'disabled');
        },
        progress: function (e, data) {
            var progress = parseInt(data.loaded / data.total * 100, 10);
            $('.bar').css('width',progress + '%');
        },
        add: function (e, data) {
            var jqXHR = data.submit()
            .done(function (result, textStatus, jqXHR) {
                if(textStatus!='success' || result.error!=null) {
                    $('.bar').parent().removeClass('progress-success').addClass('progress-danger');
                    DwMessage('Oops! el archivo no se ha podido cargar. <br />Detalle del error: '+(result.error!=null) ? result.error : textStatus);
                } else {
                    DwMessage('El archivo se ha cargado correctamente!', 'success');
                    $("#persona_fotografia").val(result.name);
                    $("#img-persona").attr('src', '<?php echo PUBLIC_PATH; ?>img/upload/personas/'+result.name);
                }
            })
            .fail(function (jqXHR, textStatus, errorThrown) {
                if(textStatus!=null){
                    DwMessage('Oops! el archivo no se ha podido cargar. <br />Detalle del error: '+textStatus);
                    $('.bar').parent().removeClass('progress-success').addClass('progress-danger');
                    setTimeout(function() { $('#upload-progress').addClass('fade'); }, 1000);
                } else {
                    DwMessage('Oops! al parecer el archivo no es una imágen válida. <br />Intenta con otro archivo.');
                    $('.bar').parent().removeClass('progress-success').addClass('progress-danger');
                    $('#upload-progress').addClass('fade');
                }
            })
            .always(function () {
                setTimeout(function() { $('#upload-progress').addClass('fade'); $('.bar').css('width','0%'); }, 1000);
                $('[type=submit]').removeAttr('disabled');
            });
        }
    });
</script>
