<?php View::notify(); ?>
<style type="text/css">
    .tab-pane { min-height: 200px;}
</style>
<div class="container-fluid dw-shell-view">
    <?php View::process($page_module, $page_title, $set_title); ?>
    <?php echo DwForm::open('', 'post', array('id'=>'form', 'class'=>'dw-validate')); ?>
     <?php if(DESKTOP) { ?>
        <ul class="nav nav-tabs">
        <?php } else { ?>
        <ul class="nav nav-pills nav-stacked">
        <?php } ?>
            <li class="active"><a href="#tab1" data-toggle="tab">Beneficiarios de <?php echo $titulares->apellido1." ".$titulares->nombre1; ?>  </a></li>
            <li><a href="#tab2" data-toggle="tab">Agregar beneficiario </a></li>
            <li><a href="#tab3" data-toggle="tab">Cargar Archivos</a></li>
        </ul>
        <div class="tab-content">
           <div class="tab-pane active" id="tab1">
           <?php echo DwForm::hidden('metodo', NULL, 'agregar'); ?>
            <div class="dw-overflow" id="data-result">
                <table class="table table-bordered table-hover table-striped table-condensed table-responsive">
                    <thead>
                        <tr>
                            <th>NUM</th>
                            <th class="col-collapse" data-search="cedula">CÉDULA</th>
                            <th class="col-collapse" data-search="nombre1">NOMBRES</th>
                            <th class="col-collapse" data-search="apellido1">APELLIDOS</th>
                            <th class="col-collapse" data-search="titular">TIPO BENFICIARIO</th>
                            <th class="col-collapse" data-search="titular">SEXO</th>
                            <th class="col-collapse" data-search="parentesco">PARENTESCO</th>
                            <th class="col-collapse">PARTICIPACIÓN</th>
                            <th class="btn-actions no-responsive" style="width: 80px;">ACCIONES</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php $counter=1;
                         foreach($bene as $bn): ?>
                         <?php $key_exc = DwSecurity::getKey($bn->id, 'excluir_bene'); ?>
                         <?php $key_upd = DwSecurity::getKey($bn->id, 'editar_bene'); ?>
                            <tr>
                                <td><?php echo $counter; ?></td>
                                <td><?php echo $bn->cedula; ?></td>
                                <td><?php echo ($bn->nombre1." ".$bn->nombre2); ?></td>
                                <td><?php echo ($bn->apellido1." ".$bn->apellido2);?></td>
                                <td><?php echo ($bn->descripcion); ?></td>
                                <td><?php switch ($bn->sexo){
                                            case 'F':
                                                echo "FEMENINO";
                                                break;
                                            case 'M':
                                                echo "MASCULINO";
                                                break;
                                    }?></td>
                                <td><?php echo $bn->parentesco;?></td>
                                <td><?php echo $bn->participacion."%"; ?></td>
                                <td><?php echo DwHtml::buttonTable('Modificar beneficiario', "beneficiarios/beneficiario/editar/$key_upd/", NULL, 'info', 'edit'); ?>
                                <?php if((Session::get('perfil_id')<=3) && ($bn->estado_beneficiario==1) ){ 
                                echo DwHtml::buttonTable('Excluir Beneficiario', "beneficiarios/beneficiario/excluir/$key_exc/", array('class'=>'js-confirm', 'confirm-title'=>'Excluir Titular', 'confirm-body'=>'¿Está seguro de Excluir el Beneficiario? <br/>'), 'danger', 'repeat');
                                }?> </td>
                            </tr>
                             <?php $counter++; ?>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>

            <div class="form-actions">
                        <?php echo DwButton::cancel('beneficiarios/titular/listar/'); ?>
            </div>
            </div><!--Cierre tab1-->
            <div class="tab-pane" id="tab2">
            <?php echo DwForm::hidden('beneficiario.titular_id', NULL, $idtitular); ?>
                <div class="row-fluid">
                     <div class="span3">
                        <?php echo DwForm::dbSelect('beneficiario.parentesco_id', 'descripcion', array('config/parentesco', 'getListadoParentesco'), NULL, array('class'=>'input-xlarge input-required  show-errors'), NULL, 'Parentesco' ); ?>
                    </div>
                    <div class="span3">
                        <?php echo DwForm::select('beneficiario.sexo', array(''=>'Seleccione:','M'=>'Masculino', 'F'=>'Femenino'), array('class'=>'input-xlarge input-required show-error'), NULL, 'Sexo:'); ?>
                    </div>

                </div>
                <div class="row-fluid">
                    <div class="span3">
                        <?php echo DwForm::select('beneficiario.nacionalidad', array(''=>'Seleccione:','V'=>'Venezolana', 'E'=>'Extranjera'), array('class'=>'input-xlarge input-required show-error'), NULL, 'Nacionalidad:'); ?>
                    </div>
                    <div class="span3">
                        <?php echo DwForm::text('beneficiario.cedula', array('class'=>'input-xlarge mask-pint input-numeric input-required show-error'), NULL, 'Cédula de Identidad'); ?>
                    </div>
                    <div class="span3">
                        <?php echo DwForm::select('beneficiario.estado_civil', array(''=>'Seleccione:', 'S'=>'Soltero', 'c'=>'Concubinato','C'=>'Casado', 'D'=>'Divorciado', 'V'=>'Viudo'), array('class'=>'input-xlarge input-required show-error'), NULL, 'Estado Civil'); ?>
                    </div>
                    <div class="span3">
                        <?php echo DwForm::date('beneficiario.fecha_nacimiento', array('class'=>'input-large input-required mask-date input-date show-errors'), date("Y-m-d"), 'Fecha de Nacimiento'); ?>
                    </div>
                </div>
                <div class="row-fluid">
                    <div class="span3">
                        <?php echo DwForm::text('beneficiario.nombre1', array('class'=>'input-xlarge mask-alpha input-required show-error'), NULL, 'Primer Nombre'); ?>
                    </div>
                    <div class="span3">
                        <?php echo DwForm::text('beneficiario.nombre2', array('class'=>'input-xlarge mask-alpha show-error'), NULL, 'Segundo Nombre'); ?>
                    </div>
                    <div class="span3">
                        <?php echo DwForm::text('beneficiario.apellido1', array('class'=>'input-xlarge input-required mask-alpha show-error'), NULL, 'Primer Apellido'); ?>
                    </div>
                    <div class="span3">
                        <?php echo DwForm::text('beneficiario.apellido2', array('class'=>'input-xlarge mask-alpha show-error'), NULL, 'Segundo Apellido'); ?>
                    </div>
                </div>
                <div class="row-fluid">
                    <div class="span3">
                        <?php echo DwForm::tel('beneficiario.participacion', array('class'=>'input-xlarge input-numeric input-required mask-pint show-error'), NULL, 'Participación'); ?>
                    </div>
                    <div class="span3">
                        <?php echo DwForm::select('titular.grupo_sanguineo', array(''=>'Seleccione:', 'O-'=>'O-', 'O+'=>'O+','A-'=>'A-', 'A+'=>'A+', 'AB+'=>'AB+', 'AB-'=>'AB-'), array('class'=>'input-xlarge show-error'), NULL, 'Grupo Sanguineo'); ?>
                    </div>
                    <div class="span3">
                        <?php echo DwForm::tel('beneficiario.celular', array('class'=>'input-xlarge input-numeric mask-pint show-error'), NULL, 'Celular'); ?>
                    </div>
                    <div class="span3">
                        <?php echo DwForm::tel('beneficiario.telefono', array('class'=>'input-xlarge input-numeric mask-pint show-error'), NULL, 'Teléfono'); ?>
                    </div>
                </div>
                <div class="row-fluid">
                 <table class="table table-responsive">
                    <tr><label>Discapacidad</label>
                    <?php foreach($discapacidad as $dis) { ?>
                        <td> 
                            <input type="checkbox" name="discapacidad[]" id="discapacidad[]" value="<?php echo $dis->iddiscapacidad; ?>"> <?php echo $dis->discapacidad; ?>
                        </td>
                        <?php }?> 
                    </tr>
                </table>    
                </div>
                <div class="row-fluid">

                </div>
             <div class="row-fluid">
                <?php echo DwForm::hidden('beneficiario.fotografia', NULL, 'default.png'); ?>
                <?php echo DwForm::hidden('beneficiario.beneficiario_tipo_id', NULL, ''); ?>
                    <div class="form-actions">
                        <?php echo DwButton::save('Guardar beneficiario'); ?>
                        <?php echo DwButton::reset('form'); ?>
                        <?php echo DwButton::cancel('beneficiarios/titular/listar/'); ?>
                    </div>
            </div>

    <?php echo DwForm::close(); ?>
            </div><!--Cierre del tab2-->

            <div class="tab-pane" id="tab3">

            <div class="row fileupload-buttonbar">
                <!-- ########################### FOTOGRAQFIA ############################## -->
                    <div class="span2">
                        <span class="btn btn-success fileinput-button">
                            <i class="icon-plus icon-white"></i>
                            <span>Seleccione Fotografía...</span>
                            <input id="fotografia" type="file" name="fotografia" class="input-large">
                        </span>
                    </div>

                    <div id="upload-progress" class="span1 fileupload-progress fade">
                        <div class="progress progress-success progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100">
                            <div class="bar" style="width:0%;"></div>
                        </div>
                    </div>

                    <div class="span3 dw-text-right">
                        <div class="span2 dw-picture-profile dw-text-center dw-text-middle dw-shadow-dark" style="margin-top: 5px">
                            <?php echo DwHtml::img('upload/personas/default.png', 'Imágen de muestra', array('id'=>'img-persona')); ?>
                        </div>
                    </div>
            </div>
        </div>
</div>

<?php View::partial('jquery.file-upload'); ?>
<script type="text/javascript">
    $(function(){
        var cedula = document.getElementById("beneficiario_cedula");
        var telefono = document.getElementById("beneficiario_telefono");
        var celular = document.getElementById("beneficiario_celular");
        var participacion = document.getElementById("beneficiario_participacion");
        cedula.maxLength = 11;
        telefono.maxLength = 11;
        celular.maxLength = 11;
        participacion.maxLength = 3;
    })
</script>
<!-- para validad que si se marca ninguno en patologias desactive las demas -->
<script type='text/javascript'>
$(document).ready(function(){  
       $("#discapacidad").click(function() {  
            if($("#discapacidad").is(':checked')) {  
                alert("Está activado");  
            } else {  
                alert("No está activado");  
            }  
        });  
      
    });  
</script>

<!-- Script ṕara darle el valor al tipo de beneficiario  -->
<script type='text/javascript'>
$("#beneficiario_parentesco_id").change(function(){
    var parentesco = $('#beneficiario_parentesco_id').val();
    if(parentesco<=5){
        $("#beneficiario_beneficiario_tipo_id").val("1");
    }
    else{
        $("#beneficiario_beneficiario_tipo_id").val("2");
    }
});
</script>



<!-- Script para chequear disponibilidad de participacion  -->
<script type='text/javascript'>
/*$("#beneficiario_participacion").change(function(){
    $.ajax({
          type: "POST",
          url: "<?php echo PUBLIC_PATH . 'beneficiarios/beneficiario/getParticipacion/'; ?>",
          data: "sucursal_id=" + sucursal_id,
          success: function(html){
            $("#div_departamento").html(html);
          }
        });
});*/
</script>

<script type="text/javascript">
    $('#fotografia').fileupload({
        url: '<?php echo PUBLIC_PATH; ?>sistema/usuario/upload/',
        dataType: 'json',
        maxFileSize: 2000000, //2MB
        acceptFileTypes: /(\.|\/)(gif|jpe?g|png)$/i,
        start: function() {
            $("#dw-message").empty();
            $('#upload-progress').removeClass('fade');
            $('.bar').parent().removeClass('progress-danger').addClass('progress-success');
            $('[type=submit]').attr('disabled', 'disabled');
        },
        progress: function (e, data) {
            var progress = parseInt(data.loaded / data.total * 100, 10);
            $('.bar').css('width',progress + '%');
        },
        add: function (e, data) {
            var jqXHR = data.submit()
            .done(function (result, textStatus, jqXHR) {
                if(textStatus!='success' || result.error!=null) {
                    $('.bar').parent().removeClass('progress-success').addClass('progress-danger');
                    DwMessage('Oops! el archivo no se ha podido cargar. <br />Detalle del error: '+(result.error!=null) ? result.error : textStatus);
                } else {
                    DwMessage('El archivo se ha cargado correctamente!', 'success');
                    $("#persona_fotografia").val(result.name);
                    $("#img-persona").attr('src', '<?php echo PUBLIC_PATH; ?>img/upload/personas/'+result.name);
                }
            })
            .fail(function (jqXHR, textStatus, errorThrown) {
                if(textStatus!=null){
                    DwMessage('Oops! el archivo no se ha podido cargar. <br />Detalle del error: '+textStatus);
                    $('.bar').parent().removeClass('progress-success').addClass('progress-danger');
                    setTimeout(function() { $('#upload-progress').addClass('fade'); }, 1000);
                } else {
                    DwMessage('Oops! al parecer el archivo no es una imágen válida. <br />Intenta con otro archivo.');
                    $('.bar').parent().removeClass('progress-success').addClass('progress-danger');
                    $('#upload-progress').addClass('fade');
                }
            })
            .always(function () {
                setTimeout(function() { $('#upload-progress').addClass('fade'); $('.bar').css('width','0%'); }, 1000);
                $('[type=submit]').removeAttr('disabled');
            });
        }
    });
</script>
