<?php View::notify(); ?>

<script type="text/javascript">
    $(function() {
        $('table').dwGrid({
            form_search: true,
            form_action: '<?php echo PUBLIC_PATH; ?>beneficiario/beneficiario/buscar/',
            form_load_data : 'dw-shell-content',
            order_attr: '<?php echo (APP_AJAX) ? 'class="dw-ajax dw-spinner"' : ''; ?>',
            order_action: $.KumbiaPHP.publicPath+"beneficiario/beneficiario/listar/"
        });
    });
</script>

<div class="container-fluid dw-shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <div class="btn-toolbar btn-toolbar-top">
        <div class="btn-actions">
            <?php echo DwHtml::button("beneficiarios/beneficiario/agregar/", 'agregar', array('class'=>'btn-success'), 'check', APP_AJAX); ?>
        </div>
    </div>

    <div class="dw-overflow" id="data-result">

        <table class="table table-bordered table-hover table-striped table-condensed table-responsive">
            <thead>
                <tr>
                    <th>NUM</th>
                    <th class="col-collapse" data-search="cedula">CEDULA</th>
                    <th class="col-collapse" data-search="nombre1">NOMBRE</th>
                    <th class="col-collapse" data-search="apellido1">APELLIDO</th>
                    <th class="col-collapse" data-search="titular">TITULAR</th>
                    <th class="col-collapse" data-search="parentesco">PARENTESCO</th>
                    <?if(APP_OFFICE) { //Si está activa la opción de oficinas ?>
                    <th class="col-collapse" data-search="sucursal">SUCURSAL</th>
                    <? } ?>
                    <th class="col-collapse" data-search="estado_usuario">ESTADO</th>
                    <th class="btn-actions no-responsive" style="width: 150px;">ACCIONES</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($beneficiarios->items as $beneficiario): ?>
                    <?php $key_shw = DwSecurity::getKey($beneficiario->id, 'shw_beneficiario'); ?>
                    <?php $key_upd = DwSecurity::getKey($beneficiario->id, 'upd_beneficiario'); ?>
                    <?php $key_ina = DwSecurity::getKey($beneficiario->id, 'bloquear_usuario'); ?>
                    <?php $key_rea = DwSecurity::getKey($beneficiario->id, 'reactivar_usuario'); ?>
                    <tr>
                        <td><?php echo $beneficiarios->counter; ?></td>
                        <td><?php echo $beneficiario->cedula; ?></td>
                        <td><?php echo $beneficiario->nombre1; ?></td>
                        <td><?php echo $beneficiario->apellido1; ?></td>
                        <td><?php echo $beneficiario->titular_id; ?></td>
                        <td><?php echo $beneficiario->parentesco; ?></td>
                        <?if(APP_OFFICE) { //Si está activa la opción de oficinas ?>
                        <td><?php echo $beneficiario->sucursal; ?></td>
                        <? } ?>
                        <td><?php // echo ($usuario->estado_usuario == EstadoUsuario::ACTIVO) ? '<span class="label label-success" title="'.$usuario->descripcion.'" rel="tooltip">Activo</span>' : '<span class="label label-important" title="'.$usuario->descripcion.'" rel="tooltip">Bloqueado</span>'; ; ?></td>
                        <td>
                            <?php echo DwHtml::buttonTable('Ver beneficiario', "beneficiarios/beneficiario/ver/$key_shw/", NULL, 'warning', 'search'); ?>
                            <?php echo DwHtml::buttonTable('Modificar beneficiario', "beneficiarios/beneficiario/editar/$key_upd/", NULL, 'info', 'edit'); ?>
                            
                        </td>
                    </tr>
                    <?php $beneficiarios->counter++; ?>
                <?php endforeach; ?>
            </tbody>
        </table>

    </div>

    <?php View::partial('paginators/default', false, array('page'=>$beneficiarios, 'url'=>"beneficiarios/beneficiario/listar/$order/")); ?>

</div>
