<?php View::notify(); ?>

<script type="text/javascript">
    $(function() {
        $('table').dwGrid({
            order_attr: '<?php echo (APP_AJAX) ? 'class="dw-ajax dw-spinner"' : ''; ?>',
            order_action: $.KumbiaPHP.publicPath+"config/profesion/listar/"
        });
    });
</script>

<div class="container-fluid dw-shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <div class="btn-toolbar btn-toolbar-top">
        <div class="btn-actions">
            <?php echo DwHtml::button("config/profesion/agregar/", 'agregar', array('class'=>'btn-success'), 'check', APP_AJAX); ?>
        </div>
    </div>

    <div class="dw-overflow">

        <table class="table table-bordered table-hover table-striped table-condensed table-responsive">
            <thead>
                <tr>
                    <th>NUM</th>
                    <th class="col-collapse" data-search="sucursal">NOMBRE</th>
                    <th class="col-collapse" data-search="direccion">DESCRIPCION</th>
                    <th class="btn-actions no-responsive" style="width: 100px;">ACCIONES</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($sucursales->items as $sucursal): ?>
                    <?php $key_upd = DwSecurity::getKey($sucursal->id, 'upd_sucursal'); ?>
                    <?php $key_del = DwSecurity::getKey($sucursal->id, 'del_sucursal'); ?>
                    <tr>
                        <td><?php echo $sucursales->counter; ?></td>
                        <td><?php echo $sucursal->sucursal; ?></td>
                        <td><?php echo $sucursal->direccion; ?></td>
                        <td><?php echo $sucursal->ciudad; ?></td>
                        <td><?php echo $sucursal->celular; ?></td>
                        <td><?php echo $sucursal->telefono; ?></td>
                        <td><?php echo $sucursal->fax; ?></td>
                        <td>
                            <?php echo DwHtml::buttonTable('Modificar Profeson', "config/profesion/editar/$key_upd/", null, 'info', 'edit'); ?>
                            <?php echo DwHtml::buttonTable('Eliminar Profesion', "config/profesion/eliminar/$key_del/", array('class'=>'js-confirm', 'confirm-title'=>'Eliminar profesion', 'confirm-body'=>'Está seguro de eliminar esta sucursal? <br />Recuerda que esta operación no se puede reversar.'), 'danger', 'ban-circle'); ?>
                        </td>
                    </tr>
                    <?php $sucursal->counter++; ?>
                <?php endforeach; ?>
            </tbody>
        </table>

    </div>

    <?php View::partial('paginators/default', false, array('page'=>$sucursales, 'url'=>"config/profesion/listar/$order/")); ?>

</div>