<?php View::notify(); ?>

<div class="container-fluid dw-shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <div class="btn-toolbar btn-toolbar-top">
        <div class="btn-actions">
            <?php echo DwHtml::button("sistema/configuracion/", 'basic', array('class'=>'btn-success '), 'asterisk', APP_AJAX); ?>
            <?php echo DwHtml::button("sistema/configuracion/seguridad/", 'config. Seguridad', array('class'=>'btn-success active'), 'asterisk', APP_AJAX); ?>
            <?php echo DwHtml::button("sistema/configuracion/routes/", 'routes', array('class'=>'btn-warning'), 'random', APP_AJAX); ?>
            <?php echo DwHtml::button("sistema/configuracion/databases/", 'databases', array('class'=>'btn-warning'), 'hdd', APP_AJAX); ?>
        </div>
    </div>

    <?php echo DwForm::open('', 'post', array('id'=>'form', 'class'=>'dw-validate', 'style-form'=>'form-horizontal')); ?>


                <?php echo DwForm::fieldset("Configuraciones de Seguridad"); ?>
                <div class="row-fluid">
                    <div class="span4">
                        <?php echo DwForm::number('seguridad.nro_intentos_fallidos', array('class'=>'input-large input-required show-error input-numeric data-toggle="tooltip" title="Ingrese razón social de la empresa'), NULL, 'N° Intentos: ','Cantidad de Inicios de Sesión Fallido'); ?>
                    </div>
                    <div class="span4">
                        <?php echo DwForm::number('seguridad.nro_pregunta_seguridad', array('class'=>'input-large input-required input-numeric show-error data-toggle="tooltip" title="Ingrese Rif de la empresa"'), NULL, 'N° Preguntas: ','Cantidad de Preguntas Secretas'); ?>
					</div>
                </div>
                <div class="row-fluid">
                    <div class="span4">
                        <?php echo DwForm::number('seguridad.nro_claves_anteriores', array('class'=>'input-large input-required show-error input-numeric data-toggle="tooltip" title="Ingrese representante legal de la empresa"'), NULL, 'N° Claves: ','N° de Claves Historicas'); ?>
                    </div>
                    <div class="span4">
                        <?php echo DwForm::number('seguridad.dias_caducidad_clave', array('class'=>'input-large input-required input-numeric show-error data-toggle="tooltip" title="Ingrese telefono de la empresa"'), NULL, 'Dias Caducidad Clave:','Duración de la Clave en Días' ); ?>
                    </div>
                </div>
                <div class="row-fluid">
                    <div class="span4">
                        <?php echo DwForm::number('seguridad.dias_aviso_caducidad_clave', array('class'=>'input-large input-required input-numeric show-error data-toggle="tooltip" title="Ingrese telefono de la empresa"'), NULL, 'Alerta Vencimiento Clave: ','N° de Dias emitir alerta'); ?>
                    </div>
                    <div class="span4">
                        
                    </div>
                </div>


                                <?php echo DwForm::fieldset(); ?>


   


        <div class="row-fluid">
            <div class="form-actions">
                <?php echo DwButton::submit('Guardar configuración', 'check'); ?>
                <?php echo DwButton::cancel(); ?>
            </div>
        </div>


    <?php echo DwForm::close(); ?>


</div>

<script type="text/javascript">
    $(function(){
        $("#form-modal").submit(function(){
            if(validForm($(this).attr('name'), false)) {
                variable = $('#variable');
                valor = $("#valor");
                $('<div class="control-group">'+
                '<label for="custom_'+variable.val()+'" class="control-label">'+variable.val()+':<span class="req">*</span></label>'+
                '<div class="controls">'+
                '<input id="custom_'+variable.val()+'" class="field text input-required show-errors" type="text" value="'+valor.val()+'" name="custom['+variable.val()+']">'+
                '<p class="help-block"> </p>'+
                '</div></div>').appendTo('#append-config');
                variable.attr('value', '');
                valor.attr('value', '');
                DwSpinner('hide');
                $("#form-add-config").modal('hide');
            }
            return false;
        });
    });
</script>
