<div class="page-header">
    <h1><?php echo ucwords("$model"), ": <span>$action_name</span>" ?></h1>
</div>
<?php View::content() ?>
<?php
View::partial('backend/barra_superior_listas', FALSE, array('opciones' => FALSE));
$dt = new DataTable($results);
$dt->addHeaders('Ver', 'Editar', 'Eliminar');
$dt->imgLink('figuras/ver.png', Router::get('controller_path') . '/ver');
$dt->imgLink('figuras/editar.png', Router::get('controller_path') . '/editar');
$dt->imgLinkConfirm('figuras/eliminar.png', Router::get('controller_path') . '/borrar');
echo $dt->render('class="table table-bordered table-striped"');
?>