<div class="page-header">
    <h1><?php echo ucwords("$model"), ": <span>$action_name</span>" ?></h1>
</div>
<?php if ($result) : ?>
    <ul>
        <?php foreach ($result->fields as $field) : ?>
            <li><strong><?php echo $result->alias[$field] ?> :</strong>  <?php eh($result->$field) ?></li>
        <?php endforeach ?>
    </ul>

    <div class="actions">
        <a href="../crear/" class="btn primary">Crear registro</a>
        <a href="../editar/<?php echo $result->id ?>" class="btn info">Editar</a>
        <a href="../" class="btn">Listado</a>
        <a class="btn error" title="¿Seguro que quiere borrar?" href="../borrar/<?php echo $result->id ?>" onclick="return confirm('¿Está seguro?');">Borrar</a>
    </div>
<?php else : ?>
    <?php header("HTTP/1.0 404 Not Found") ?>
    <h1>No existe</h1>
    <div class="actions">
        <a href="../">Listado</a>
        <a href="../crear/">Crear registro</a>
    </div>
<?php endif ?>