<?php View::notify(); ?>

<div class="container-fluid dw-shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <?php echo DwForm::open('', 'post', array('id'=>'form', 'class'=>'dw-validate')); ?>

        <div class="row-fluid">
            <div class="span6">
                <?php echo DwForm::text('proveedor.rif', array('class'=>'input-xxlarge input-required show-error'), $proveedor->rif, 'Rif'); ?>
            </div>
            <div class="span6">
                <?php echo DwForm::text('proveedor.razon_social', array('class'=>'input-xxlarge input-required show-error'), $proveedor->razon_social, 'Razon Social'); ?>
            </div>
        </div>

        <div class="row-fluid">
            <div class="span6">
                <?php echo DwForm::text('proveedor.nombre_corto', array('class'=>'input-xxlarge input-required show-error'), $proveedor->nombre_corto, 'Alias'); ?>
            </div>
            <div class="span6">
                <?php echo DwForm::text('proveedor.telefono1', array('class'=>'input-xxlarge input-required mask-alphanum show-error'), $proveedor->telefono1, 'Telefono1'); ?>
            </div>
        </div>
        <div class="row-fluid">
            <div class="span6">
                <?php echo DwForm::text('proveedor.telefono2', array('class'=>'input-xxlarge input-required mask-alphanum  show-error'), $proveedor->telefono2, 'Telefono 2'); ?>
            </div>
            <div class="span6">
                <?php echo DwForm::text('proveedor.fax', array('class'=>'input-xxlarge mask-alphanum show-error'), $proveedor->fax, 'Fax'); ?>
            </div>
        </div>

         <div class="row-fluid">
            <div class="span6">
                <?php echo DwForm::dbSelect('proveedor.pais_id', 'nombre', array('params/pais', 'getListadoPais'), NULL, array('class'=>'input-xxlarge input-required mask-pint show-errors'), NULL, 'Pais'); ?>
            </div>
            <div class="span6">
                <?php echo DwForm::dbSelect('proveedor.estado_id', 'nombre', array('params/estado', 'getListadoEstado'), NULL, array('class'=>'input-xxlarge input-required mask-pint show-errors'), NULL, 'Estado'); ?>
            </div>
        </div>
        <div class="row-fluid">
            <div class="span6">
                <?php echo DwForm::dbSelect('proveedor.municipio_id', 'nombre', array('params/municipio', 'getListadoMunicipio'), NULL, array('class'=>'input-xxlarge input-required mask-pint show-errors'), NULL, 'Municipio'); ?>
            </div>
            <div class="span6">
                <?php echo DwForm::dbSelect('proveedor.parroquia_id', 'nombre', array('params/parroquia', 'getListadoParroquia'), NULL, array('class'=>'input-xxlarge input-required mask-pint show-errors'), NULL, 'Parroquia'); ?>
            </div>
        </div>
        <div class="row-fluid">
            <div class="span6">
                <?php echo DwForm::text('proveedor.direccion', array('class'=>'input-xxlarge input-required show-error'), $proveedor->direccion, 'Dirección'); ?>
            </div>
            <div class="span6">
                <?php echo DwForm::email('proveedor.correo_electronico', array('class'=>'input-xxlarge show-error'), $proveedor->correo_electronico, 'Correo Electronico'); ?>
        </div>
       
        <div class="row-fluid">
            <div class="span12">
                <?php echo DwForm::textarea('proveedor.observacion', array('class'=>'input-xxlarge show-error'), $proveedor->observacion, 'Observación'); ?>
            </div>
            
        </div>
    

            <?php echo DwForm::hiddenKey('proveedor.id', $proveedor->id); ?>
        </div>

        <div class="row-fluid">
            <div class="form-actions">
                <?php echo DwButton::save('Guardar Proveedor'); ?>
                <?php echo DwButton::reset('form'); ?>
                <?php echo DwButton::cancel(); ?>
            </div>
        </div>

    <?php echo DwForm::close(); ?>

</div>