<label>Municipio<span class="req">*</span></label>
<?php
    echo Form::dbSelect("proveedor.municipio_id", 'nombre', array('municipio','buscar',$estado_id), '           -  Seleccione  -           ');
?>		
 
<script type='text/javascript'>
$("#proveedor_municipio_id").click(function(){
    var municipio_id     =   $('#proveedor_municipio_id').val();
        $.ajax({
          type: "POST",
          url: "<?php echo PUBLIC_PATH . 'proveedorsalud/proveedor/getParroquiaMunicipio/'; ?>",
          data: "municipio_id=" + municipio_id,
          success: function(html){
            $("#div_parroquia").html(html);
          }
        });
});
</script>