<?php View::notify(); ?>
<script type="text/javascript">
    $(function() {
        $('table').dwGrid({
            form_search: true,
            form_action: '<?php echo PUBLIC_PATH; ?>proveedorsalud/proveedor/buscar/',
            form_load_data : 'dw-shell-content',
            order_attr: '<?php echo (APP_AJAX) ? 'class="dw-ajax dw-spinner"' : ''; ?>',
            order_action: $.KumbiaPHP.publicPath+"proveedorsalud/proveedor/listar/"
        });
    });
</script>

<div class="container-fluid dw-shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <div class="btn-toolbar btn-toolbar-top">
        <div class="btn-actions">
            <?php echo DwHtml::button("proveedorsalud/proveedor/agregar/", 'agregar', array('class'=>'btn-success'), 'check', APP_AJAX); ?>
        </div>
    </div>

    <div class="dw-overflow"  id="data-result">

        <table class="table table-bordered table-hover table-striped table-condensed table-responsive">
            <thead>
                <tr>
                    <th>NUM</th>
                    <th class="col-collapse" data-search="rif">RIF</th>
                    <th class="col-collapse" data-search="nombre">NOMBRE</th>
                    <th class="col-collapse" data-search="correo">CORREO</th>
                    <th class="col-collapse" data-search="observacion">DIRECCIÓN</th>
                    <th class="btn-actions no-responsive" style="width: 100px;">ACCIONES</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($proveedores->items as $proveedor): ?>
                    <?php $key_upd = DwSecurity::getKey($proveedor->id, 'upd_proveedor'); ?>
                    <?php $key_del = DwSecurity::getKey($proveedor->id, 'del_proveedor'); ?>
                    <tr>
                        <td><?php echo $proveedores->counter; ?></td>
                        <td><?php echo $proveedor->rif; ?></td>
                        <td><?php echo $proveedor->nombre_corto; ?></td>
                        <td><?php echo $proveedor->correo_electronico; ?></td>
                        <td><?php echo $proveedor->direccion; ?></td>
                        <td>
                            <?php echo DwHtml::buttonTable('Modificar Proveedor', "proveedorsalud/proveedor/editar/$key_upd/", null, 'info', 'edit'); ?>
                            <?php echo DwHtml::buttonTable('Eliminar Proveedor', "proveedorsalud/proveedor/eliminar/$key_del/", array('class'=>'js-confirm', 'confirm-title'=>'Eliminar proveedor', 'confirm-body'=>'Está seguro de eliminar este proveedor? <br />Recuerda que esta operación no se puede reversar.'), 'danger', 'ban-circle'); ?>
                        </td>
                    </tr>
                    <?php $proveedores->counter++; ?>
                <?php endforeach; ?>
            </tbody>
        </table>

    </div>

    <?php View::partial('paginators/default', false, array('page'=>$proveedores, 'url'=>"proveedorsalud/proveedor/listar/$order/")); ?>

</div>
