<div class="page-header">
    <h1>Configuraci&oacute;n De la Aplicación</h1>
</div>
<?php View::content() ?>
<?php echo Form::open(NULL, 'post', 'class="form-horizontal"') ?>
<fieldset>
    <legend>General</legend>
    <div class="control-group">
        <label class="control-label" for="config_name">T&iacute;tulo del Proyecto : </label>
        <div class="controls">
            <?php echo Form::text('config.name') ?>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label" for="config_production">Proyecto en Producci&oacute;n : </label>
        <div class="controls">
            <?php echo Form::select('config.production', array('On' => 'Si', 'Off' => 'No')) ?>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label" for="config_dbdate">Formato de Fechas : </label>
        <div class="controls">
            <?php echo Form::text('config.dbdate') ?>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label" for="config_debug">Debug : </label>
        <div class="controls">
            <?php echo Form::select('config.debug', array('On' => 'Si', 'Off' => 'No')) ?>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label" for="config_log_exceptions">Mostrar Excepciones : </label>
        <div class="controls">
            <?php echo Form::select('config.log_exceptions', array('On' => 'Si', 'Off' => 'No')) ?>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label" for="config_charset">Codificaci&oacute;n de Caracteres : </label>
        <div class="controls">
            <?php echo Form::text('config.charset') ?>
        </div>
    </div>
</fieldset>
<div class="control-group">
    <label class="control-label" for="config_cache_driver">Driver de Cache : </label>
    <div class="controls">
        <?php echo Form::text('config.cache_driver') ?>
        </div>
    </div>
    <fieldset>
        <legend>Seguridad</legend>
        <div class="control-group">
            <label class="control-label" for="config_minimo_clave">Caracteres M&iacute;nimo Clave : </label>
            <div class="controls">
            <?php echo Form::text('config.minimo_clave') ?>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label" for="config_guardar_auditorias">Auditorias Activa : </label>
        <div class="controls">
            <?php echo Form::select('config.guardar_auditorias', array('On' => 'Si', 'Off' => 'No')) ?>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label" for="config_guardar_auditorias">Intentos de Acceso : </label>
        <div class="controls">
            <?php echo Form::select('config.intentos_acceso', array(1 => 1, 2, 3, 4, 5, 6, 7, 8, 9, 10)) ?>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label" for="config_recordar_sesion">Permitir Recordar Sesión : </label>
        <div class="controls">
            <?php echo Form::select('config.recordar_sesion', array('On' => 'Si', 'Off' => 'No')) ?>
        </div>
    </div>
</fieldset>
<fieldset>
    <legend>Otros</legend>
    <div class="control-group">
        <label class="control-label" for="config_registro">M&oacute;dulo de Registro Activo : </label>
        <div class="controls">
            <?php echo Form::select('config.registro', array('On' => 'Si', 'Off' => 'No')) ?>
        </div>
    </div>
</fieldset>
<div class="form-actions">
    <?php echo Form::submit('Guardar Configuración', 'class="btn btn-primary"') ?>
        </div>
<?php echo Form::close() ?>