<?php
$li_i=000;

$li_i++;
//$gi_total=45;
$arbol["sistema"][$li_i]="SPG";
$arbol["nivel"][$li_i]=0;
$arbol["nombre_logico"][$li_i]="Procesos";
$arbol["nombre_fisico"][$li_i]="";
$arbol["id"][$li_i]="001";
$arbol["padre"][$li_i]="000";
$arbol["numero_hijos"][$li_i]=4;
$li_i++;
$arbol["sistema"][$li_i]="SPG";
$arbol["nivel"][$li_i]=1;
$arbol["nombre_logico"][$li_i]="Comprobantes";
$arbol["nombre_fisico"][$li_i]="";
$arbol["id"][$li_i]="002";
$arbol["padre"][$li_i]="001";
$arbol["numero_hijos"][$li_i]=1;
$li_i++;
$arbol["sistema"][$li_i]="SPG";
$arbol["nivel"][$li_i]=2;
$arbol["nombre_logico"][$li_i]="Ejecución Financiera";
$arbol["nombre_fisico"][$li_i]="sigesp_spg_p_comprobante.php";
$arbol["id"][$li_i]="003";
$arbol["padre"][$li_i]="002";
$arbol["numero_hijos"][$li_i]=0;
$li_i++;
$arbol["sistema"][$li_i]="SPG";
$arbol["nivel"][$li_i]=1;
$arbol["nombre_logico"][$li_i]="Apertura";
$arbol["nombre_fisico"][$li_i]="";
$arbol["id"][$li_i]="004";
$arbol["padre"][$li_i]="001";
$arbol["numero_hijos"][$li_i]=2;
$li_i++;
$arbol["sistema"][$li_i]="SPG";
$arbol["nivel"][$li_i]=2;
$arbol["nombre_logico"][$li_i]="Mensual";
$arbol["nombre_fisico"][$li_i]="sigesp_spg_p_apertura.php";
$arbol["id"][$li_i]="005";
$arbol["padre"][$li_i]="004";
$arbol["numero_hijos"][$li_i]=0;
$li_i++;
$arbol["sistema"][$li_i]="SPG";
$arbol["nivel"][$li_i]=2;
$arbol["nombre_logico"][$li_i]="Trimestral";
$arbol["nombre_fisico"][$li_i]="sigesp_spg_p_apertura_trim.php";
$arbol["id"][$li_i]="006";
$arbol["padre"][$li_i]="004";
$arbol["numero_hijos"][$li_i]=0;
$li_i++;
$arbol["sistema"][$li_i]="SPG";
$arbol["nivel"][$li_i]=1;
$arbol["nombre_logico"][$li_i]="Modificaciones Presupuestarias";
$arbol["nombre_fisico"][$li_i]="";
$arbol["id"][$li_i]="007";
$arbol["padre"][$li_i]="001";
$arbol["numero_hijos"][$li_i]=4;
$li_i++;
$arbol["sistema"][$li_i]="SPG";
$arbol["nivel"][$li_i]=2;
$arbol["nombre_logico"][$li_i]="Rectificaciones";
$arbol["nombre_fisico"][$li_i]="sigesp_spg_p_rectificaciones.php";
$arbol["id"][$li_i]="008";
$arbol["padre"][$li_i]="007";
$arbol["numero_hijos"][$li_i]=0;

$li_i++;

$arbol["sistema"][$li_i]="SPG";
$arbol["nivel"][$li_i]=2;
$arbol["nombre_logico"][$li_i]="Insubsistencias";
$arbol["nombre_fisico"][$li_i]="sigesp_spg_p_insubsistencias.php";
$arbol["id"][$li_i]="009";
$arbol["padre"][$li_i]="007";
$arbol["numero_hijos"][$li_i]=0;
$li_i++;
$arbol["sistema"][$li_i]="SPG";
$arbol["nivel"][$li_i]=2;
$arbol["nombre_logico"][$li_i]="Traspasos";
$arbol["nombre_fisico"][$li_i]="sigesp_spg_p_traspaso.php";
$arbol["id"][$li_i]="010";
$arbol["padre"][$li_i]="007";
$arbol["numero_hijos"][$li_i]=0;
$li_i++;
$arbol["sistema"][$li_i]="SPG";
$arbol["nivel"][$li_i]=2;
$arbol["nombre_logico"][$li_i]="Credito/Ingreso Adicional";
$arbol["nombre_fisico"][$li_i]="sigesp_spg_p_adicional.php";
$arbol["id"][$li_i]="011";
$arbol["padre"][$li_i]="007";
$arbol["numero_hijos"][$li_i]=0;

$li_i++;
$arbol["sistema"][$li_i]="SPG";
$arbol["nivel"][$li_i]=1;
$arbol["nombre_logico"][$li_i]="Programación de Reportes";
$arbol["nombre_fisico"][$li_i]="";
$arbol["id"][$li_i]="012";
$arbol["padre"][$li_i]="001";
$arbol["numero_hijos"][$li_i]=2;
$li_i++;
$arbol["sistema"][$li_i]="SPG";
$arbol["nivel"][$li_i]=2;
$arbol["nombre_logico"][$li_i]="Mensual";
$arbol["nombre_fisico"][$li_i]="sigesp_spg_p_progrep.php";
$arbol["id"][$li_i]="013";
$arbol["padre"][$li_i]="012";
$arbol["numero_hijos"][$li_i]=0;
$li_i++;
$arbol["sistema"][$li_i]="SPG";
$arbol["nivel"][$li_i]=2;
$arbol["nombre_logico"][$li_i]="Trimestral";
$arbol["nombre_fisico"][$li_i]="sigesp_spg_p_progrep_trim.php";
$arbol["id"][$li_i]="014";
$arbol["padre"][$li_i]="012";
$arbol["numero_hijos"][$li_i]=0;
$li_i++;
$arbol["sistema"][$li_i]="SPG";
$arbol["nivel"][$li_i]=0;
$arbol["nombre_logico"][$li_i]="Reportes";
$arbol["nombre_fisico"][$li_i]="";
$arbol["id"][$li_i]="015";
$arbol["padre"][$li_i]="000";
$arbol["numero_hijos"][$li_i]=1;
$li_i++;
$arbol["sistema"][$li_i]="SPG";
$arbol["nivel"][$li_i]=1;
$arbol["nombre_logico"][$li_i]="Acumulado por Cuentas";
$arbol["nombre_fisico"][$li_i]="sigesp_spg_r_acum_x_cuentas.php";
$arbol["id"][$li_i]="016";
$arbol["padre"][$li_i]="015";
$arbol["numero_hijos"][$li_i]=0;
$li_i++;
$arbol["sistema"][$li_i]="SPG";
$arbol["nivel"][$li_i]=1;
$arbol["nombre_logico"][$li_i]="Mayor Analitico";
$arbol["nombre_fisico"][$li_i]="sigesp_spg_r_mayor_analitico.php";
$arbol["id"][$li_i]="017";
$arbol["padre"][$li_i]="015";
$arbol["numero_hijos"][$li_i]=0;
$li_i++;
$arbol["sistema"][$li_i]="SPG";
$arbol["nivel"][$li_i]=1;
$arbol["nombre_logico"][$li_i]="Listado de Apertura";
$arbol["nombre_fisico"][$li_i]="sigesp_spg_r_listado_apertura.php";
$arbol["id"][$li_i]="018";
$arbol["padre"][$li_i]="015";
$arbol["numero_hijos"][$li_i]=0;
$li_i++;
$arbol["sistema"][$li_i]="SPG";
$arbol["nivel"][$li_i]=1;
$arbol["nombre_logico"][$li_i]="Modificaciones Presupuestarias No Aprobadas";
$arbol["nombre_fisico"][$li_i]="sigesp_spg_r_modificaciones_presupuestarias.php";
$arbol["id"][$li_i]="019";
$arbol["padre"][$li_i]="015";
$arbol["numero_hijos"][$li_i]=0;
$li_i++;
$arbol["sistema"][$li_i]="SPG";
$arbol["nivel"][$li_i]=1;
$arbol["nombre_logico"][$li_i]="Comprobante Formato 1";
$arbol["nombre_fisico"][$li_i]="sigesp_spg_r_comprobante_formato1.php";
$arbol["id"][$li_i]="020";
$arbol["padre"][$li_i]="015";
$arbol["numero_hijos"][$li_i]=0;
$li_i++;
$arbol["sistema"][$li_i]="SPG";
$arbol["nivel"][$li_i]=1;
$arbol["nombre_logico"][$li_i]="Comprobante Formato 2";
$arbol["nombre_fisico"][$li_i]="sigesp_spg_r_comprobante_formato2.php";
$arbol["id"][$li_i]="021";
$arbol["padre"][$li_i]="015";
$arbol["numero_hijos"][$li_i]=0;
$li_i++;
$arbol["sistema"][$li_i]="SPG";
$arbol["nivel"][$li_i]=1;
$arbol["nombre_logico"][$li_i]="Disponibilidad Presupuestaria";
$arbol["nombre_fisico"][$li_i]="sigesp_spg_r_disponibilidad.php";
$arbol["id"][$li_i]="022";
$arbol["padre"][$li_i]="015";
$arbol["numero_hijos"][$li_i]=0;
$li_i++;
$arbol["sistema"][$li_i]="SPG";
$arbol["nivel"][$li_i]=1;
$arbol["nombre_logico"][$li_i]="Listado de Cuentas Presupuestarias";
$arbol["nombre_fisico"][$li_i]="sigesp_spg_r_cuentas.php";
$arbol["id"][$li_i]="023";
$arbol["padre"][$li_i]="015";
$arbol["numero_hijos"][$li_i]=0;
$li_i++;
$arbol["sistema"][$li_i]="SPG";
$arbol["nivel"][$li_i]=1;
$arbol["nombre_logico"][$li_i]="Resumen del Presupuesto de Gasto Por Partida(0704)";
$arbol["nombre_fisico"][$li_i]="sigesp_spg_r_comparados_forma0704.php";
$arbol["id"][$li_i]="024";
$arbol["padre"][$li_i]="015";
$arbol["numero_hijos"][$li_i]=0;
$li_i++;
$arbol["sistema"][$li_i]="SPG";
$arbol["nivel"][$li_i]=1;
$arbol["nombre_logico"][$li_i]="Resumen del Presupuesto (0705)";
$arbol["nombre_fisico"][$li_i]="sigesp_spg_r_comparados_forma0705.php";
$arbol["id"][$li_i]="025";
$arbol["padre"][$li_i]="015";
$arbol["numero_hijos"][$li_i]=0;
$li_i++;
$arbol["sistema"][$li_i]="SPG";
$arbol["nivel"][$li_i]=1;
$arbol["nombre_logico"][$li_i]="Ejecución Financiera  del Presupuesto de Gastos(0707)";
$arbol["nombre_fisico"][$li_i]="sigesp_spg_r_comparados_ejecucion_financiera_formato3.php";
$arbol["id"][$li_i]="026";
$arbol["padre"][$li_i]="015";
$arbol["numero_hijos"][$li_i]=0;
$li_i++;
$arbol["sistema"][$li_i]="SPG";
$arbol["nivel"][$li_i]=1;
$arbol["nombre_logico"][$li_i]="Ejecución Financiera Mensual del Presupuesto de Gastos(0402)";
$arbol["nombre_fisico"][$li_i]="sigesp_spg_r_comparados_forma0402.php";
$arbol["id"][$li_i]="027";
$arbol["padre"][$li_i]="015";
$arbol["numero_hijos"][$li_i]=0;
$li_i++;
$arbol["sistema"][$li_i]="SPG";
$arbol["nivel"][$li_i]=1;
$arbol["nombre_logico"][$li_i]="Ejecución Financiera de los Proyectos del Ente(0413)";
$arbol["nombre_fisico"][$li_i]="sigesp_spg_r_comparados_forma0413.php";
$arbol["id"][$li_i]="028";
$arbol["padre"][$li_i]="015";
$arbol["numero_hijos"][$li_i]=0;
$li_i++;
$arbol["sistema"][$li_i]="SPG";
$arbol["nivel"][$li_i]=1;
$arbol["nombre_logico"][$li_i]="Ejecución Financiera de las Acciones Centralizadas del Ente(0414)";
$arbol["nombre_fisico"][$li_i]="sigesp_spg_r_comparados_forma0414.php";
$arbol["id"][$li_i]="029";
$arbol["padre"][$li_i]="015";
$arbol["numero_hijos"][$li_i]=0;
$li_i++;
$arbol["sistema"][$li_i]="SPG";
$arbol["nivel"][$li_i]=1;
$arbol["nombre_logico"][$li_i]="Ejecución Financiera de las Acciones Especificas(0415)";
$arbol["nombre_fisico"][$li_i]="sigesp_spg_r_comparados_forma0415.php";
$arbol["id"][$li_i]="030";
$arbol["padre"][$li_i]="015";
$arbol["numero_hijos"][$li_i]=0;
$li_i++;
$arbol["sistema"][$li_i]="SPG";
$arbol["nivel"][$li_i]=1;
$arbol["nombre_logico"][$li_i]="Presupuesto de Caja (0717)";
$arbol["nombre_fisico"][$li_i]="sigesp_spg_r_comparados_forma0717.php";
$arbol["id"][$li_i]="031";
$arbol["padre"][$li_i]="015";
$arbol["numero_hijos"][$li_i]=0;
$li_i++;
$arbol["sistema"][$li_i]="SPG";
$arbol["nivel"][$li_i]=1;
$arbol["nombre_logico"][$li_i]="Distribucion Mensual del Presupuesto";
$arbol["nombre_fisico"][$li_i]="sigesp_spg_r_distribucion_mensual_presupuesto.php";
$arbol["id"][$li_i]="032";
$arbol["padre"][$li_i]="015";
$arbol["numero_hijos"][$li_i]=0;
$li_i++;
$arbol["sistema"][$li_i]="SPG";
$arbol["nivel"][$li_i]=1;
$arbol["nombre_logico"][$li_i]="Distribucion Trimestral del Presupuesto";
$arbol["nombre_fisico"][$li_i]="sigesp_spg_r_distribucion_trimestral_presupuesto.php";
$arbol["id"][$li_i]="033";
$arbol["padre"][$li_i]="015";
$arbol["numero_hijos"][$li_i]=0;
$li_i++;
$arbol["sistema"][$li_i]="SPG";
$arbol["nivel"][$li_i]=1;
$arbol["nombre_logico"][$li_i]="Unidades Ejecutoras";
$arbol["nombre_fisico"][$li_i]="sigesp_spg_r_unidades_ejecutoras.php";
$arbol["id"][$li_i]="034";
$arbol["padre"][$li_i]="015";
$arbol["numero_hijos"][$li_i]=0;
$li_i++;
$arbol["sistema"][$li_i]="SPG";
$arbol["nivel"][$li_i]=1;
$arbol["nombre_logico"][$li_i]="Ejecucion de Compromisos";
$arbol["nombre_fisico"][$li_i]="sigesp_spg_r_ejecucion_compromisos.php";
$arbol["id"][$li_i]="035";
$arbol["padre"][$li_i]="015";
$arbol["numero_hijos"][$li_i]=0;
$li_i++;
$arbol["sistema"][$li_i]="SPG";
$arbol["nivel"][$li_i]=1;
$arbol["nombre_logico"][$li_i]="Compromisos no Causados";
$arbol["nombre_fisico"][$li_i]="sigesp_spg_r_compromisos_no_causados.php";
$arbol["id"][$li_i]="036";
$arbol["padre"][$li_i]="015";
$arbol["numero_hijos"][$li_i]=0;
$li_i++;
$arbol["sistema"][$li_i]="SPG";
$arbol["nivel"][$li_i]=1;
$arbol["nombre_logico"][$li_i]="Compromisos Causados Parcialmente";
$arbol["nombre_fisico"][$li_i]="sigesp_spg_r_compromisos_causados_parcialmente.php";
$arbol["id"][$li_i]="037";
$arbol["padre"][$li_i]="015";
$arbol["numero_hijos"][$li_i]=0;
$li_i++;
$arbol["sistema"][$li_i]="SPG";
$arbol["nivel"][$li_i]=1;
$arbol["nombre_logico"][$li_i]="Compromisos Causados no Pagados";
$arbol["nombre_fisico"][$li_i]="sigesp_spg_r_compromisos_causados_no_pagados.php";
$arbol["id"][$li_i]="038";
$arbol["padre"][$li_i]="015";
$arbol["numero_hijos"][$li_i]=0;
$li_i++;
$arbol["sistema"][$li_i]="SPG";
$arbol["nivel"][$li_i]=1;
$arbol["nombre_logico"][$li_i]="Operacion por Especifica";
$arbol["nombre_fisico"][$li_i]="sigesp_spg_r_operacion_por_especifica.php";
$arbol["id"][$li_i]="039";
$arbol["padre"][$li_i]="015";
$arbol["numero_hijos"][$li_i]=0;
$li_i++;
$arbol["sistema"][$li_i]="SPG";
$arbol["nivel"][$li_i]=1;
$arbol["nombre_logico"][$li_i]="Ejecutado por Partida";
$arbol["nombre_fisico"][$li_i]="sigesp_spg_r_ejecutado_por_partida.php";
$arbol["id"][$li_i]="040";
$arbol["padre"][$li_i]="015";
$arbol["numero_hijos"][$li_i]=0;
$li_i++;
$arbol["sistema"][$li_i]="SPG";
$arbol["nivel"][$li_i]=1;
$arbol["nombre_logico"][$li_i]="Operación por Banco";
$arbol["nombre_fisico"][$li_i]="sigesp_spg_r_operacion_por_banco.php";
$arbol["id"][$li_i]="041";
$arbol["padre"][$li_i]="015";
$arbol["numero_hijos"][$li_i]=0;
$li_i++;
$arbol["sistema"][$li_i]="SPG";
$arbol["nivel"][$li_i]=1;
$arbol["nombre_logico"][$li_i]="Resumen Proveedor/Beneficiario";
$arbol["nombre_fisico"][$li_i]="sigesp_spg_r_resumen_prov_bene.php";
$arbol["id"][$li_i]="042";
$arbol["padre"][$li_i]="015";
$arbol["numero_hijos"][$li_i]=0;
$li_i++;
$arbol["sistema"][$li_i]="SPG";
$arbol["nivel"][$li_i]=1;
$arbol["nombre_logico"][$li_i]="Modificaciones Presupuestarias Aprobadas";
$arbol["nombre_fisico"][$li_i]="sigesp_spg_r_modificaciones_presupuestarias_aprobadas.php";
$arbol["id"][$li_i]="043";
$arbol["padre"][$li_i]="015";
$arbol["numero_hijos"][$li_i]=0;
$li_i++;
$arbol["sistema"][$li_i]="SPG";
$arbol["nivel"][$li_i]=1;
$arbol["nombre_logico"][$li_i]="Disponibilidad Presupuestaria Formato # 2";
$arbol["nombre_fisico"][$li_i]="sigesp_spg_r_disponibilidad_formato2.php";
$arbol["id"][$li_i]="044";
$arbol["padre"][$li_i]="015";
$arbol["numero_hijos"][$li_i]=0;
$li_i++;
$arbol["sistema"][$li_i]="SPG";
$arbol["nivel"][$li_i]=1;
$arbol["nombre_logico"][$li_i]="Resumen de Ejecucion Financiera de Presupuesto de Gasto";
$arbol["nombre_fisico"][$li_i]="sigesp_spg_r_resumen_ejecucion_financiera.php";
$arbol["id"][$li_i]="045";
$arbol["padre"][$li_i]="015";
$arbol["numero_hijos"][$li_i]=0;

$li_i++;
$arbol["sistema"][$li_i]="SPG";
$arbol["nivel"][$li_i]=1;
$arbol["nombre_logico"][$li_i]="Transferencias Intercompañias";
$arbol["nombre_fisico"][$li_i]="";
$arbol["id"][$li_i]="046";
$arbol["padre"][$li_i]="001";
$arbol["numero_hijos"][$li_i]=1;

$li_i++;
$arbol["sistema"][$li_i]="SPG";
$arbol["nivel"][$li_i]=2;
$arbol["nombre_logico"][$li_i]="Modificaciones Presupuestarias Aprobadas";
$arbol["nombre_fisico"][$li_i]="sigesp_spg_p_transferir_traspasos.php";
$arbol["id"][$li_i]="047";
$arbol["padre"][$li_i]="046";
$arbol["numero_hijos"][$li_i]=0;

$li_i++;
$arbol["sistema"][$li_i]="SPG";
$arbol["nivel"][$li_i]=1;
$arbol["nombre_logico"][$li_i]="Resultado de Traspasos Presupuestarios Intercompañia";
$arbol["nombre_fisico"][$li_i]="sigesp_spg_r_traspasos.php";
$arbol["id"][$li_i]="048";
$arbol["padre"][$li_i]="015";
$arbol["numero_hijos"][$li_i]=0;

$li_i++;
$arbol["sistema"][$li_i]="SPG";
$arbol["nivel"][$li_i]=1;
$arbol["nombre_logico"][$li_i]="Reverso/Cierre de Presupuesto de Gasto";
$arbol["nombre_fisico"][$li_i]="sigesp_spg_p_cerrarpre.php";
$arbol["id"][$li_i]="049";
$arbol["padre"][$li_i]="001";
$arbol["numero_hijos"][$li_i]=0;

$li_i++;
$arbol["sistema"][$li_i]="SPG";
$arbol["nivel"][$li_i]=2;
$arbol["nombre_logico"][$li_i]="Asientos Presupuestarios y Contables";
$arbol["nombre_fisico"][$li_i]="sigesp_spg_p_trans_asipre.php";
$arbol["id"][$li_i]="050";
$arbol["padre"][$li_i]="046";
$arbol["numero_hijos"][$li_i]=0;
$li_i++;
$arbol["sistema"][$li_i]="SPG";
$arbol["nivel"][$li_i]=1;
$arbol["nombre_logico"][$li_i]="Estado de Resultado";
$arbol["nombre_fisico"][$li_i]="sigesp_spg_r_instructivo_estado_resultado.php";
$arbol["id"][$li_i]="051";
$arbol["padre"][$li_i]="015";
$arbol["numero_hijos"][$li_i]=0;
$li_i++;
$arbol["sistema"][$li_i]="SPG";
$arbol["nivel"][$li_i]=1;
$arbol["nombre_logico"][$li_i]="Consolidado de Ejecucion Trimestral de Gastos y Aplicaciones Financieras";
$arbol["nombre_fisico"][$li_i]="sigesp_spg_r_instructivo_consolidado_ejecucion_trimestral.php";
$arbol["id"][$li_i]="052";
$arbol["padre"][$li_i]="015";
$arbol["numero_hijos"][$li_i]=0;
$li_i++;
$arbol["sistema"][$li_i]="SPG";
$arbol["nivel"][$li_i]=1;
$arbol["nombre_logico"][$li_i]="Ejecucion Trimestral de Gastos y Aplicaciones Financieras";
$arbol["nombre_fisico"][$li_i]="sigesp_spg_r_ejecucion_trimestral.php";
$arbol["id"][$li_i]="053";
$arbol["padre"][$li_i]="015";
$arbol["numero_hijos"][$li_i]=0;

$li_i++;
$arbol["sistema"][$li_i]="SPG";
$arbol["nivel"][$li_i]=1;
$arbol["nombre_logico"][$li_i]="Ejecucion Financiera de Presupuesto de Gasto";
$arbol["nombre_fisico"][$li_i]="sigesp_spg_r_ejecucion_financiera.php";
$arbol["id"][$li_i]="054";
$arbol["padre"][$li_i]="015";
$arbol["numero_hijos"][$li_i]=0;

$li_i++;
$arbol["sistema"][$li_i]="SPG";
$arbol["nivel"][$li_i]=1;
$arbol["nombre_logico"][$li_i]="Eliminar Comprobantes";
$arbol["nombre_fisico"][$li_i]="sigesp_spg_p_eliminar_comprobante.php";
$arbol["id"][$li_i]="055";
$arbol["padre"][$li_i]="001";
$arbol["numero_hijos"][$li_i]=0;

$li_i++;
$arbol["sistema"][$li_i]="SPG";
$arbol["nivel"][$li_i]=1;
$arbol["nombre_logico"][$li_i]="Ejecucion Financiera de los Proyectos / Acciones Centralizadas del Organo";
$arbol["nombre_fisico"][$li_i]="sigesp_spg_r_instructivo_06_ejec_fin_pry_acc.php";
$arbol["id"][$li_i]="056";
$arbol["padre"][$li_i]="015";
$arbol["numero_hijos"][$li_i]=0;

$li_i++;
$arbol["sistema"][$li_i]="SPG";
$arbol["nivel"][$li_i]=1;
$arbol["nombre_logico"][$li_i]="Ejecucion Financiera de las Acciones Especificas del Organo";
$arbol["nombre_fisico"][$li_i]="sigesp_spg_r_instructivo_06_ejec_fin_acc_esp.php";
$arbol["id"][$li_i]="057";
$arbol["padre"][$li_i]="015";
$arbol["numero_hijos"][$li_i]=0;

$li_i++;
$arbol["sistema"][$li_i]="SPG";
$arbol["nivel"][$li_i]=1;
$arbol["nombre_logico"][$li_i]="Informacion Mensual de la Ejecucion Financiera";
$arbol["nombre_fisico"][$li_i]="sigesp_spg_r_instructivo_06_inf_men_eje_fin.php";
$arbol["id"][$li_i]="058";
$arbol["padre"][$li_i]="015";
$arbol["numero_hijos"][$li_i]=0; 

$li_i++;
$arbol["sistema"][$li_i]="SPG";
$arbol["nivel"][$li_i]=1;
$arbol["nombre_logico"][$li_i]="Presupuesto Modificado Detallado por Fuentes de Financiamiento";
$arbol["nombre_fisico"][$li_i]="sigesp_spg_r_modif_fuente_finan.php";
$arbol["id"][$li_i]="059";
$arbol["padre"][$li_i]="015";
$arbol["numero_hijos"][$li_i]=0;

$li_i++;
$arbol["sistema"][$li_i]="SPG";
$arbol["nivel"][$li_i]=1;
$arbol["nombre_logico"][$li_i]="Modificación del Presupuesto Programado (Mensual)";
$arbol["nombre_fisico"][$li_i]="sigesp_spg_p_modprog.php";
$arbol["id"][$li_i]="060";
$arbol["padre"][$li_i]="001";
$arbol["numero_hijos"][$li_i]=0;

$li_i++;
$arbol["sistema"][$li_i]="SPG";
$arbol["nivel"][$li_i]=1;
$arbol["nombre_logico"][$li_i]="Modificación del Presupuesto Programado (Trimestral)";
$arbol["nombre_fisico"][$li_i]="sigesp_spg_p_modprog_trimestral.php";
$arbol["id"][$li_i]="061";
$arbol["padre"][$li_i]="001";
$arbol["numero_hijos"][$li_i]=0; 

$li_i++;
$arbol["sistema"][$li_i]="SPG";
$arbol["nivel"][$li_i]=1;
$arbol["nombre_logico"][$li_i]="Ejecución Presupuestaria Mensual de Gasto";
$arbol["nombre_fisico"][$li_i]="sigesp_spg_r_ejecucion_financiera_mensual.php";
$arbol["id"][$li_i]="062";
$arbol["padre"][$li_i]="015";
$arbol["numero_hijos"][$li_i]=0; 


$li_i++;
$arbol["sistema"][$li_i]="SPG";
$arbol["nivel"][$li_i]=1;
$arbol["nombre_logico"][$li_i]="Modificaciones al Programado";
$arbol["nombre_fisico"][$li_i]="sigesp_spg_r_modif_programado.php";
$arbol["id"][$li_i]="048";
$arbol["padre"][$li_i]="015";
$arbol["numero_hijos"][$li_i]=0;

$arbol["sistema"][$li_i]="SPG";
$arbol["nivel"][$li_i]=1;
$arbol["nombre_logico"][$li_i]="Cuadro Resumen de Fideicomisos";
$arbol["nombre_fisico"][$li_i]="sigesp_spg_r_resumen_fideicomiso.php";
$arbol["id"][$li_i]="063";
$arbol["padre"][$li_i]="015";
$arbol["numero_hijos"][$li_i]=0;
$li_i++;

$arbol["sistema"][$li_i]="SPG";
$arbol["nivel"][$li_i]=1;
$arbol["nombre_logico"][$li_i]="Presupuesto Modificado Detallado por Fuente de Financiamiento";
$arbol["nombre_fisico"][$li_i]="sigesp_spg_r_modif_fuente_finan.php";
$arbol["id"][$li_i]="064";
$arbol["padre"][$li_i]="015";
$arbol["numero_hijos"][$li_i]=0;
$li_i++;

$arbol["sistema"][$li_i]="SPG";
$arbol["nivel"][$li_i]=1;
$arbol["nombre_logico"][$li_i]="Modificaciones al Programado";
$arbol["nombre_fisico"][$li_i]="sigesp_spg_r_modif_programado.php";
$arbol["id"][$li_i]="065";
$arbol["padre"][$li_i]="015";
$arbol["numero_hijos"][$li_i]=0;
$li_i++;

$arbol["sistema"][$li_i]="SPG";
$arbol["nivel"][$li_i]=1;
$arbol["nombre_logico"][$li_i]="Listado de Fuentes de Financiamiento";
$arbol["nombre_fisico"][$li_i]="sigesp_spg_r_fuente.php";
$arbol["id"][$li_i]="066";
$arbol["padre"][$li_i]="015";
$arbol["numero_hijos"][$li_i]=0;
$li_i++;

$gi_total=$li_i;
?>